- postcss.js
Support `core-cms` as `CUSTOM_ASSET_DIR` in image build configuration.
> This will allow us to combine `dockerhub_repo` and `CUSTOM_ASSET_DIR` into one parameter.
- [FP-981](https://jira.tacc.utexas.edu/browse/FP-981)
1. Change custom asset build logic:
- __Before__: <del><em>Always</em> build custom stylesheets.</del>
- __After__: <ins><em>If</em> <strong>not</strong> `core-cms`, <em>then</em> build custom stylesheets.</ins>
2. Include (from submodule) new `core-cms` directory that just has a `README.md`.
See https://github.com/TACC/cms-site-resources/pull/38.
> Quick: Create & Skip empty Core cms directory

- taccsite_cms/static/site_cms/css/src/_imports/branding_logos.css
- taccsite_cms/static/site_cms/css/src/_imports/components/c-footer.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.css
Minor visual darkening of the dark gray of the header and footer.
This is part of the [Frontera Homepage Redesign](https://github.com/TACC/Core-CMS/issues/157) that is being propagated to Core.
- GH-157
- Change color of header and footer to be darkest (TACC standard) primary color.
- Change colors of header and footer to use CSS variables a.k.a. custom properties.
This is already tested in context via https://frontera-portal.tacc.utexas.edu/home-2021-03/ or (if launched) https://frontera-portal.tacc.utexas.edu/ and locally by developer with other related changes via https://github.com/TACC/Core-CMS/pull/174.
1. Ensure header text color is `#FFFFFF`.
1. Ensure header background color is `#222222`.
1. Ensure footer text color is `#FFFFFF`.
1. Ensure footer background color is `#222222`.
> GH-157: Header & Footer: Update Colors. Use Vars

- taccsite_cms/static/site_cms/css/src/_imports/elements/html-elements.css
This is part of the [Frontera Homepage Redesign](https://github.com/TACC/Core-CMS/issues/157) that is being propagated to Core.
- Set a minimum width for all page `body`'s.
- Explicitly set TACC line-height of `1.4` to override Bootstrap.
- GH-157
This is already tested in context via https://frontera-portal.tacc.utexas.edu/home-2021-03/ or (if launched) https://frontera-portal.tacc.utexas.edu/ and locally by developer with other related changes via https://github.com/TACC/Core-CMS/pull/174.
> __Tip:__ Use "Inspect Element" context menu to access Developer Tools to investigate CSS for body element.
1. Ensure active `body` line-height is `1.4`.
1. Ensure active `body` line-height comes from TACC CSS.
1. Ensure active `body` min-width is `290px`.
> GH-157: Body Tag: Explicit Line Height & Min-Width

- taccsite_cms/static/site_cms/css/src/_imports/elements/tacc-search-bar.css
Fix a Core bug that was revealed by [Frontera Homepage Redesign](https://github.com/TACC/Core-CMS/issues/157).
Set search bar font to be Roboto, so per-project styles do __not__ override it. — [source](https://confluence.tacc.utexas.edu/x/cYAZCg)
- GH-157
This is already tested in context via https://frontera-portal.tacc.utexas.edu/home-2021-03/ or (if launched) https://frontera-portal.tacc.utexas.edu/ and locally by developer with other related changes via https://github.com/TACC/Core-CMS/pull/174.
1. Ensure header search bar font is explicitly\* Roboto.
\* Explicitly as in defined within the element, not inherited from page.
> GH-157: Search Bar: Match Portal Font (Roboto)

- taccsite_cms/static/site_cms/css/src/_imports/components/c-read-more.css
- taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
- taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.html
- taccsite_cms/static/site_cms/css/src/_imports/objects/o-site.css
- taccsite_cms/static/site_cms/css/src/_imports/tools/x-article-link.css
- taccsite_cms/static/site_cms/css/src/_imports/tools/x-layout.css
- taccsite_cms/static/site_cms/css/src/_imports/tools/x-truncate.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-article-list.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-article-list.html
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-article-preview.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-article-preview.html
- taccsite_cms/static/site_cms/css/src/_imports/trumps/u-empty.css
- taccsite_cms/static/site_cms/css/src/site.css
- taccsite_cms/static/site_shared/css/src/_imports/settings/color.css
- taccsite_cms/static/site_shared/css/src/_imports/tools/x-center.css
- Create many new stylesheets.
- Update some related stylesheets.
- Import only two stylesheets into `site.css`\*
- Add to color settings.
> \* The rest are imported by [Frontera's temporary homepage template stylesheet](https://github.com/TACC/cms-site-resources/compare/task/GH-35-redesign-home-page).
- GH-157
- Import new object and utility into `site.css`.
- Add new object for sections.
- Add new scope styles for article lists.
- Add new mixins.
- Add new component for read more.
- Tweak existing section for site layout to support oddity of section's object.
- Add new utility to support hiding content with a paper trail that can lead to the context/reason.
- Add RGB versions of colors (and note color deviations to avoid).
This is already tested in context via …
> GH-157: Add New Stylesheets for Frontera Redesign

- taccsite_cms/settings.py
- taccsite_cms/signal_processor.py
On a document publish, unpublish, or delete event, we want the cms index to rebuild. This adds a new signal processor that hooks into Haystack, and subclasses the [BaseSignalProcessor](https://django-haystack.readthedocs.io/en/master/signal_processors.html#default-basesignalprocessor) [class](https://github.com/django-haystack/django-haystack/blob/master/haystack/signals.py#L7).
An improvement would be to add/remove the document from the index instead of rebuilding, but I had trouble updating the index with the instance object returned from the `post_publish` signal. Since we have relatively few documents and activity on each cms, the occasional [rebuild_index](https://django-haystack.readthedocs.io/en/master/management_commands.html#rebuild-index) call will not be a resource burden.
1. …
> task/FP-982: Add `rebuild_index` haystack signal processor

- taccsite_cms/static/build/README.md
Delete a `build/README.md` from an outdated and otherwise empty build directory.
> Noop: Delete outdated README.md

- taccsite_cms/static/site_cms/js/nav_portal.js
- taccsite_cms/templates/nav_portal.html
Postponing merge to ensure no other Portal CMS accidentally deploys this without [TACC/Core-Portal PR #390](https://github.com/TACC/Core-Portal/pull/390).
- Must **only** be deployed **with _or_ after** [TACC/Core-Portal PR #390](https://github.com/TACC/Core-Portal/pull/390).
- Should be deployed **with** [taccaci/frontera-tech-docs PR #18](https://bitbucket.org/taccaci/frontera-tech-docs/pull-requests/18).
**Replace** replicated Portal nav template code and unique update script **with** common code to load external markup.
- Portal & Docs: [FP-1015](https://jira.tacc.utexas.edu/browse/FP-1015)
- CMS: GH-195
- CMS: https://github.com/TACC/Core-CMS/pull/211
- Portal: https://github.com/TACC/Core-Portal/pull/390
- Docs: https://bitbucket.org/taccaci/frontera-tech-docs/pull-requests/17/fp-101 …
> GH-195: Clone Portal Nav

- package.json
- Update support for `env()` (new commit for GH-191).
- Allow GH-101 to _continue to_ work off of important change in GH-191 to relevant files.
> This is the _second_ time I've merged in GH-191 code; the first was https://github.com/TACC/Core-CMS/pull/221.
See https://github.com/TACC/Core-CMS/pull/192 (as of b81f789).
> Task/gh 101 header redesign  env variables (update)

- conf/css/.postcssrc.yml
- conf/css/freeze_variables/.postcssrc.yml
- package-lock.json
- package.json
- taccsite_cms/static/site_cms/css/src/_imports/_tests/postcss-preset-env.css
- taccsite_cms/static/site_cms/css/src/_imports/components/c-branding.css
- taccsite_cms/static/site_cms/css/src/_imports/components/c-logo.css
- taccsite_cms/static/site_cms/css/src/_imports/elements/html-elements.css
- taccsite_cms/static/site_cms/css/src/_imports/settings/border.css
- taccsite_cms/static/site_cms/css/src/_imports/settings/font.css
- taccsite_cms/static/site_cms/css/src/_imports/tools/selectors.css
- taccsite_cms/static/site_cms/css/src/_imports/tools/x-arrow.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/README.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/for-docs.header.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.twig.html
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-portal-nav.css
- taccsite_cms/static/site_cms/css/src/_themes/constants.json
- taccsite_cms/static/site_cms/css/src/_themes/export.js
- taccsite_cms/static/site_cms/css/src/_themes/theme.default.json
- taccsite_cms/static/site_cms/css/src/_themes/theme.has-dark-logo.json
- taccsite_cms/static/site_cms/css/src/site.header.css
- taccsite_cms/templates/cms_menu.html
- taccsite_cms/templates/header.html
- taccsite_cms/templates/header_branding.html
- yarn.lock
Redesign the nav dropdowns and the CMS nav.
> The search bar and portal nav button have not been redesigned yet. Their final design _might_ change.
Summary:
- Support [custom selectors](https://preset-env.cssdb.org/features#custom-selectors).
- For variable freezing, support [custom environment variables](https://preset-env.cssdb.org/features#environment-variables).
- Install [`merge-lite`](https://www.npmjs.com/package/merge-lite).
- Add `arrow` mixin to CSS.
- Document the kinds of "Trumps" that are in our CSS.
- Add stylesheet `trumps/for-docs.header.css`.
- Rewrite `trumps/s-header.css`.
- Add Theme "constants".
- Fix docs header colors by loading colors in `site.header.css`.
Bug Fixes:
- #55
- #29
- #129
<details><summary>Complete List</summary>
- __New__: Support [custom …
> GH-101: Navigation Bar (Sans Search & Portal Nav Button)

- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-portal-nav.css
- taccsite_cms/static/site_cms/css/src/_themes/constants.json
- taccsite_cms/static/site_cms/css/src/_themes/theme.default.json
- taccsite_cms/static/site_cms/css/src/_themes/theme.has-dark-logo.json
Redesign the portal nav link / menu toggle.
GH-101
- Use new portal `env()` vars for nav padding.
- No custom logo width (related to portal nav via navbar padding).
- Remove border between search and portal nav.
- Add Portal nav styles.
- Add new portal `env()` vars for nav padding.
- Comment on header link background color `env()` var value.
- Add new header `env()` var for portal nav background color.
- Revert/Remove commented Frontera code.
Skipped.
1. Build CSS with CMS setting/secret `_THEME` set to `None`.
1. Confirm Portal nav link style matches [CMS-Common Components > Navigation Light-mode](https://xd.adobe.com/view/b37b291a-7798-4814-90f3-7ac63c48a3e0-e628/screen/fb70e7c7-f8ad-40a8-ad2d-f211fa36c05f/specs/).
1. Build CSS with CMS setting/secret `_THEME` set to `'has-dark-logo'`. …
> Task/gh 101 header redesign  portal nav

- taccsite_cms/static/site_cms/css/src/_imports/components/c-branding.css
- taccsite_cms/static/site_cms/css/src/_imports/components/c-logo.css
- taccsite_cms/static/site_cms/css/src/_imports/elements/html-elements.css
- taccsite_cms/static/site_cms/css/src/_imports/tools/media-queries.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.compressed.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.expanded.css
- taccsite_cms/static/site_cms/css/src/site.header.css
- taccsite_cms/templates/cms_menu.html
- taccsite_cms/templates/header.html
- taccsite_cms/templates/header_branding.html
- Design the mobile navbar.
- Better responsive design for header.
- Technical improvements.
> The search bar, icons, menu toggle, and mobile portal nav have **not** been re-styled yet.
- #101
Major:
- __New__: Add compressed and expanded navbar styles in two files.
- __New__: Increase body min-width (to prevent wrap of navbar toggle).
- __New__: Remove condition for navbar breakpoint; now it's always 992px.
- __New__: Migrate some `s-header` CSS to `[…].expanded` and `[…].compressed`.
- __New__: Use `top` to position arrows isntead of `margin`.
- __New__: Truncate nav links.
- __New__: Style dropdowns.
- __New__: Add nav link text span wrappers (to prevent truncation of menu arrows).
<details>
<summary>Minor</summary>
- __Minor__: Remove branding images style that is made redundant.
- …
> GH-101: Navigation Bar (Responsive Design Sans Search & Icons)

- taccsite_cms/static/site_cms/css/src/_imports/components/c-branding.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/for-docs.header.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.compressed.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.expanded.css
- taccsite_cms/static/site_cms/css/src/_themes/constants.json
- taccsite_cms/static/site_cms/css/src/site.header.css
- taccsite_cms/templates/header.html
- Finish styling mobile navbar menu.
- Style mobile navbar menu toggle button.
- Style mobile brand bar.
- Style mobile brandbar and navbar height.
> The search bar and portal menu icons have **not** been re-styled yet.
- #101
- __New__: Import all icon styles (not just some).
- __New__: Support mobile brandbar.
- __New__: Support mobile vs. desktop navbar & brandbar heights.
- __New__: Support mobile logo.
- __New__: Support mobile navbar collabsible menu.
- __New__: Add new theme constants for navbar & branbar heights.
- __New__: Add navbar menu button text.
- Resize screen width.
- Compare the following elements to design when header navigation is mobile versus desktop:
- brand bar height
- brand bar separators height
- brand bar images heights
- nav bar height
- nav bar menu …
> GH-101: Navigation Bar (Mobile Menus & Toggle)

- taccsite_cms/static/site_cms/css/src/_imports/trumps/for-docs.header.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-portal-nav.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-portal-nav.html
Use Cortal icons for Portal nav.
> The search bar and portal nav have **not** been re-styled yet.
- #101
- _Minor_: Tweak a comment (related cuz it's also icon hack).
- _Minor_: Migrate Portal nav styles to `s-portal-nav.css`.
- __New__: Add hack to swap FA icons with Cortal icons.
- _Minor_: Update CSS sample `s-portal-nav.html`.
1. Load on wide screen (so header navigation uses desktop layout).
1. Ensure icons are new, from Cortal, and not from FontAwesome.
<details>
- icons should show and look different than before
- icons should use Cortal font
- icons should **not** use Font Awesome font
</details>
1. Ensure no other styles have changed.
1. Load on small screen (so header navigation uses mobile layout).
1. Ensure Portal nav is usable and has icons.
1. Ensure no other styles have …
> Hack: GH-101: Use Cortal icons sans markup change

- conf/css/.postcssrc.yml
- taccsite_cms/static/site_cms/css/src/_imports/_tests/postcss-preset-env.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.compressed.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.expanded.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-portal-nav.css
- taccsite_cms/templates/header.html
- Finish styling mobile navbar menu.
- Style mobile navbar menu toggle button.
- Style mobile brand bar.
- Style mobile brandbar and navbar height.
> The search bar, icons, and portal nav have **not** been re-styled yet.
- #101
- __New__: Use CSS for margin instead of `ml-auto`
- _Minor_: Make header code DRY (now that CMS nav imports are identical).
- _Minor_: Use custom selector for consistency
- __Fix__: Fix navbar toggle color
- __New__: New mobile menu layout for search bar and portal nav
- _Minor_: Support `:not` with multiple elements.
- _Minor_: Edit existing relevant CSS to be consistent and accurately organized.
- __Fix__: Reduce oversized dropdown toggle ("chevron")
- __New__: Swap "Log Out" & "My Account" icons
1. Resize screen width.
1. Compare the following elements to …
> GH-101: Mobile Menu (Search & Portal Layout)

- taccsite_cms/static/site_cms/css/src/_imports/tools/x-article-link.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-article-preview.css
- To Frontera hero banner, add articles.
- Update relevant Core code to support Frontera hero banner articles.
#233
- __Fix__: Ensure position of stretched link is top left; ignore container padding.
- _Minor_: Only truncate article previews if they are in a standard article list.
- __Fix__: Ensure expected space actually shows after the prefix for an article preview date.
- __New__: Add Frontera hero banner article styles (and related tweaks).
> __Notice__: Tested via changing snippet `GH-35: CSS (Frontera): Templates: Home […]` on https://frontera-portal.tacc.utexas.edu/home-2021-03. The snippet is pasted code from local build. _Testing locally is difficult, because I would need to recreate the page content via CMS actions (cloning CMS content across servers is not yet convenient)._ …
> GH-233: Frontera Hero Banner Styles - Quick

- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-portal-nav.css
- taccsite_cms/templates/nav_portal.html
Load portal nav with no width, then transition it to "natural" width.
> The login icon has not ben restyled yet. The location of portal nav in mobile has not moved, yet.
- #101
- _Minor_: Add missing specificity to a Portal Nav selector.
- __New__: Make Portal Nav _gently push_—**not** abruptly shove—Search Bar aside after it loads.
1. Load CMS.
2. Ensure Portal Nav gently pushed search to the left.
3. Load Docs.
4. Ensure Portal Nav gently pushed search to the left.
5. Load Portal.
6. Ensure Portal Nav loads before search i.e. search is not pushed anywhere.
1. Does not work on Docs unless Docs has (commits from) branch `task/GH-101-header-redesign`.
2. (pre-existing defect) The width of Portal Nav on CMS & Docs differs from Portal (may be related to font size of whitespace).
> GH-101: Portal Nav (Load with Transition / Animation)

- taccsite_cms/static/site_cms/css/src/_imports/_tests/postcss-extend.css
- taccsite_cms/static/site_cms/css/src/_imports/tools/x-mobile-button.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.compressed.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.expanded.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-portal-nav.html
Make portal nav icon, text, and dropdown match design.¹
> The location of portal nav in mobile has not moved, yet.
¹ See "Known Issues" 1.
- #101
- __New__: Add CSS plugin test for nested @extend's.
- __New__: Add & Use mixin "mobile button".
- __Fix__: Limit large nav link padding to CMS links.
- __Fix__: Limit nav icon spacing depending on nav and screen width.
- __New__: Split icon styles between compressed and expanded.
- __New__: Add missing markup for `s-portal-nav` sample HTML.
0. Resize window to be narrow (≤991px).
1. Load CMS.
2. Ensure Portal Nav icon, when logged _in_ **and** when logged _out_, match design.¹
3. Ensure logged in toggle is on the right.
1. Load Docs.
2. Ensure Portal Nav icon, when logged _in_ ~~**and** when logged _out_~~, match design.¹²
3. Ensure logged in …
> GH-101: Portal Nav Mobile - Link Style

- taccsite_cms/static/site_cms/css/src/_imports/tools/media-queries.css
- taccsite_cms/static/site_cms/css/src/_imports/tools/x-mobile-button.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.compressed.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.expanded.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-portal-nav.css
- taccsite_cms/static/site_cms/css/src/_themes/constants.json
Change portal nav layout to be "pushdown" menu instead of "dropdown" menu.¹
> The location of portal nav in mobile was not moved as was planned for this PR.
¹ See "Known Issues" 1.
- #101
- __New__: Convert "mobile button" layout from flex to grid.
- Update "mobile button" instances accordingly.
- __New__: Add more nav media queries.
- _Minor_: Use new constants.
- __New__: Shove Portal Nav up into Search Bar row (do not properly share 1 row).
- __Fix__: Ensure icon spacing is accurate given different nav states.
- __Fix__: Add background for Portal Nav & Search Bar "row".
- __New__: Make all mobile dropdown menu items have same font size.
- __New__: Retain wide portal nav for one breakpoint within collapsed navbar.
- __New__: Limit Portal Nav load transition to when navbar is expanded.
- …
> GH-101: Portal Nav Mobile - Layout Change

- taccsite_cms/static/site_cms/css/src/_imports/_tests/postcss-preset-env.css
- Test whether custom media queries are constant.
- Prevent need to research this later by providing proof.
@tacc-wbomar considered variable custom media queries as a solution to a problem in GH-101.¹
<details>
<summary>Footnotes</summary>
¹ The problem was (A) breakpoint-aware markup differed between CMS (updated header) and Portal+Docs (header not updated yet) **and** (B) GH-101 was intend to update the header without _requiring_ (immediate) update to Portal+Docs **where** (A) prevented (B). The solution was to change custom media query definitions at runtime within Portal+Docs selectors.
</details>
> Quick: New Test: Custom Media Queries are Constant

- taccsite_cms/static/site_cms/css/src/_imports/tools/media-queries.css
- taccsite_cms/templates/header.html
Make CMS match Portal & Docs navbar collapse breakpoint.
> __Caveat__: This makes a _stand-alone CMS_ navbar collapse for a wider screen than it did before (and than is necessary). _For CMS's that have a Portal, there is no change._
</details>
- __New__/__Fix__: Use `navbar-expand-lg` (for now) to match Portal & Docs.
- Load Docs, CMS, and Portal.
- Ensure all three have the same navbar styling and collapsing at these breakpoints:
- ≥ 1200px
- 576px – 1200px
- < 576px 
- Ideally CSS can change media queries to match diff markup per subsite.
- But there is __not__ a feasible CSS way to do this.
- And the effort for a way it can be done (nesting rules) is too great.
- So great an effort I might as well update Portal & Docs markup.
> Hotfix: GH-101: Match Portal+Docs Nav Breakpoint

- taccsite_cms/default_secrets.py
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-style-guide.css
- taccsite_cms/static/site_cms/css/src/template.style-guide.css
- taccsite_cms/templates/style_guide.html
Create a basic template and stylesheet for any kind of style guide. Use cases:
- __Pattern Library__*
- Design System
- Writing Style Guide
- Coding Style Guide
\* This is the first use case.
* #253
* __New__: Add `style-guide` template to secrets.
* __New__: Add `style-guide` stylesheets.
* __New__: Add `style-guide` template.
1. Add new entry to `_CMS_TEMPLATES` secrets.
2. Create a page with template "Style Guide".
3. Add "Text" plugin to page and confirm:
- large space above text
- larger space below text
4. Add several nested "Style" plugins to page, each using a `<section>` tag, and confirm:
- top-level `<section>`s have thick border and large space between them
- low-level `<section>`s have thin border and small space between them
This solution is:
- manually populated
- …
> GH-253: Initial Pattern Library Template & Styles

- taccsite_cms/default_secrets.py
- taccsite_cms/settings.py
- taccsite_cms/templates/header.html
- By default, disable search index for SAD CMS (because it does not support search).
- Allow disabling of search for Portal sites (because it can cause 504 on CMS publish).
- [FP-1099](https://jira.tacc.utexas.edu/browse/FP-1099)
- __New__: Add `FEATURE['search']`
- __New__: Isolate search settings behind `FEATURE['search']` toggle
- __New__: Only render search bar for Portals with `FEATURE['search']` set to anything _except_ `False`.
<details>
<summary>Compare Values & Effects</summary>
| `FEATURE['search']` | Portal | Portal CMS | SAD CMS |
| --- | --- | --- | --- |
| `(truthy)` | __allow__ _search_ | __allow__ _index_ | __allow__ _search_ & __allow__ _index_ |
| `(falsy)` | __allow__ _search_ | __allow__ _index_ | __no__ _search_ bar & __never__ _index_ |
| `False` | __no__ _search_ …
> FP-1099: Search Index - Disable for SAD CMS & Allow Disabling for Portal CMS

- taccsite_cms/contrib/bootstrap4_djangocms_link/cms_plugins.py
- taccsite_cms/contrib/bootstrap4_djangocms_picture/cms_plugins.py
- taccsite_cms/settings.py
Restore support for plugins that `djangocms_bootstrap4` removes (in favor of its own).
_(Because we do not need Bootstrap for every image, link, etcetera.)_
- Register new TACC plugin to reregister `LinkPlugin` (if Bootstrap's respective plugin is present).
- Register new TACC plugin to reregister `PicturePluign` (if Bootstrap's respective version is present).
<details>
<summary>"Generic" ▸ "Image" and "Bootstrap4" ▸ "Picture / Image"</summary>
</details>
<details>
<summary>"Generic" ▸ "Link" and "Bootstrap4" ▸ "Link / Button"</summary>
(skipped, inconvenient given cross-branch progress on my local environment)
</details>
- Ensure that both plugins, "Generic" ▸ "Image" and "Bootstrap4" ▸ "Picture / Image", are available and functional.
- Ensure that both plugins, "Generic" ▸ "Link" and …
> Quick: Support Non-Bootstrap Link & Picture Plugins

- taccsite_cms/contrib/taccsite_sample/cms_plugins.py
- taccsite_cms/contrib/taccsite_sample/constants.py
- taccsite_cms/contrib/taccsite_sample/defaults.py
- taccsite_cms/contrib/taccsite_sample/models.py
- taccsite_cms/contrib/taccsite_sample/templates/sample.html
Updates to meet the standards set by plugins in GH-93.
- Rename `defaults.py` to `constants.py`.
- Rename `user_name` to `DEFAULT_USER_NAME`.
- Change `<h1>` to `<p>`.
1. Add plugin.
2. Confirm initial value is "Guest".
3. Run test cases i.e. #190 "Developer Testing".
4. (Optional) Manually test as CMS user i.e. #190 "CMS User Testing".
> Quick: Polish Sample (Greet User) Plugin

- taccsite_cms/contrib/taccsite_blockquote/cms_plugins.py
- taccsite_cms/contrib/taccsite_blockquote/models.py
- taccsite_cms/contrib/taccsite_offset/cms_plugins.py
- taccsite_cms/contrib/taccsite_offset/models.py
- taccsite_cms/contrib/taccsite_sample/cms_plugins.py
- taccsite_cms/contrib/taccsite_sample/helpers.py
- taccsite_cms/contrib/taccsite_sample/models.py
- taccsite_cms/contrib/taccsite_sample/tests.py
Update old plugins to have formatting and naming consistent with incoming GH-93 plugins.
- new lines
- organizational comments
- rename `utils.py` to `helpers.py`
- remove what would become redundant `documentation`
- use internationalization formatting for user-facing strings with variables
- improve & add docblocks
> Quick: Clean Up Plugins to Match GH-93 Plugins

- taccsite_cms/signal_processor.py
As it was, the cms elasticsearch index would rebuild for every publish and unpublish event sent from the cms. This means a new rebuild event for every cms model or snippet on a page. This task pares down the `rebuild_index` event for only signals derived from the `cms.models.pagemodel.Page` model, resulting in only one `rebuild_index` event for a given page publication or unpublication.
- https://jira.tacc.utexas.edu/browse/FP-1099
1. Edit a page with more than one type of object in it, i.e. many text boxes, alerts, etc.
2. Publish the page, and in the logs ensure the following text only appears once.
```
core_cms         | Removing all documents from your index because you said so.
core_cms_elasticsearch | {"type": "server", "timestamp": "XXXX", "level": "INFO", "component": …
```
> bug/FP-1099: Only rebuild index on `Page` type for `publish` or `unpublish` events

- taccsite_cms/contrib/helpers.py
- taccsite_cms/contrib/taccsite_static_article_preview/templates/static_article_preview.html
__Problem__:
> unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'
__Solution__:
Fix bad logic that lead to None being assumed to be string and/or date.
- __New__: Fix bad date logic.
- _No Op_: Consistent markup (for dates).
1. Add an instance of an Allocations Article Preview plugin (with minimum info) to a page.
2. Edit the plugin instance: add valid Start Date, but no End Date.
3. Save change.
4. Page must **not** crash.
> Hotfix: GH-93: Clearer & Accurate Date Logic

- CHANGELOG.md
- Add https://github.com/TACC/Core-CMS/releases/tag/v2.6.2 to change log.
- Add https://github.com/TACC/Core-CMS/releases/tag/v2.1.1 to change log.
- Edit (shorten) name of https://github.com/TACC/Core-CMS/releases/tag/v2.1.0.
The branch name is different because this release originally had initial A2CPS support which was removed (from the release) to allow deploy of release that had tested CMS image.
> v2.5.2: Changelog

- taccsite_cms/static/site_cms/css/src/_imports/tools/x-truncate.css
Support a custom property (variable) and a fallback value (the original value) for the value of a rule in the `x-truncate` "tool" stylesheet.
- Swap static value for dynamic value with fallback.
Ignoring, because:
- This small change was successfully tested during development of [#75](https://github.com/TACC/Core-CMS/issues/75) (still in progress as of 2021-08-03).
- This small change is already proven to be reliable via [some merged Core-Portal PR by me I have trouble finding](https://github.com/TACC/Core-Portal/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Amerged+author%3Atacc-wbomar+).
- This feature is documented by MDN: [Using CSS custom properties @ Custom property fallback values](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#custom_property_fallback_values …
> Quick: Support Variable in x-truncate CSS

- taccsite_cms/static/site_cms/css/src/_imports/components/c-see-all-link.css
- taccsite_cms/static/site_cms/css/src/site.css
Create CSS component for any "See all" / "See more" links.
- GH-298
- Create new CSS component stylesheet.
- Import new stylesheet into Core `site.css`.
1. If you do not have a CMS environment, then prepare one with [Wiki: Test CMS Changes](https://github.com/TACC/Core-CMS/wiki/Test-CMS-Changes).
2. Checkout branch `task/GH-298-add-see-all-component--quick/support-and-add-snippets`.
3. Add new snippet to test page.
4. Create Snippet plugin with:
- __HTML__: ["Markup" from `c-see-all-link.css`](https://github.com/TACC/Core-CMS/blob/task/GH-298-add-see-all-component/taccsite_cms/static/site_cms/css/src/_imports/components/c-see-all-link.css#L7-L10)
- __Template__: `snippets/spaceless-markup.html`
5. Test that the following is rendered:
- With page template "Fullwidth" (`fullwidth.html`)\*: …
> GH-298: Add "See All" Link Component

- taccsite_cms/static/site_cms/css/src/_imports/components/c-data-list.css
- taccsite_cms/static/site_cms/css/src/_imports/components/c-data-list.html
- taccsite_cms/static/site_cms/css/src/site.css
Create CSS component for "Data List" (borrow and improve [similar Portal component](https://github.com/TACC/Core-Portal/pull/116)).
Just the component (re-usable styles) for GH-75.
- Create new CSS component stylesheet.
- Import new stylesheet into Core `site.css`.
> **Alternative**: To test with a plugin instead of a snippet—or test #308 at the same time—then checkout branch `task/GH-75-styles--GH-75-plugin` instead.
1. If you do not have a CMS environment, then prepare one with [Wiki: Test CMS Changes](https://github.com/TACC/Core-CMS/wiki/Test-CMS-Changes).
2. Checkout this branch.
3. Add new snippet to test page.
4. Create Snippet plugin with:
- __HTML__: ["Markup" from `c-data-list.html`](https://github.com/TACC/Core-CMS/blob/task/GH-75-styles/taccsite_cms/static/site_cms/css/src/_imp …
> GH-75: Data List - Styles / Component

- taccsite_cms/templates/snippets/README.md
- taccsite_cms/templates/snippets/spaceless-markup.html
The PR https://github.com/TACC/Core-CMS-Resources/pull/66 depends on this PR.
- Document and regulate snippet support.\*
- Add one useful snippet.†
- Allow use of snippets via committed code.‡
\* Mostly a migration of [TACC/Core-CMS-Resources:`example-cms/snippets`](https://github.com/TACC/Core-CMS-Resources/tree/3627509/example-cms/snippets). \
† Used for testing PR https://github.com/TACC/Core-CMS/pull/300.
‡ Existing snippets may now have their HTML field emptied and their Template field populated.
1. If you do not have a CMS environment, then prepare one with [Wiki: Test CMS Changes](https://github.com/TACC/Core-CMS/wiki/Test-CMS-Changes).
3. Add new Snippet plugin to test page.
4. Create snippet with:
- __HTML__: (any markup that has space between tags; …
> Quick: Support Snippets & Add 1 Useful Snippet

- taccsite_cms/static/site_cms/css/src/_imports/branding_logos.css
- taccsite_cms/static/site_cms/css/src/_imports/elements/html-elements.css
- taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
- taccsite_cms/static/site_cms/css/src/_imports/settings/color.css
- taccsite_cms/static/site_cms/css/src/_imports/settings/font.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-header.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-portal-nav.css
- taccsite_cms/static/site_cms/css/src/site.css
- taccsite_cms/templates/snippets/typography-guide.html
Standardize font sizes and known colors, and known usage of them based on available designs.
- __New__: Set site text color and font size.
- __New__: Set site heading styles.
- _Minor_: Do not assume `dt` font weight is bold.
- __New__: Set site link styles.
- _Minor_: Set text color and font size variables.
- _Minor_: Prevent new dropdown text bug.
- #98
1. If no environment, then [prepare to test CMS changes](https://github.com/TACC/Core-CMS/wiki/Test-CMS-Changes).
2. Add new snippet to test page.
3. Create Snippet plugin with:
- __HTML__: (none)
- __Template__: `snippets/typography-guide.html`
- [screenshot "GH-98 - Snippet Form"](https://user-images.githubusercontent.com/62723358/129333183-65ab88b6-dbf0-4b19-9b10-3f3a06f13fbe.png)
4. Test that the following is rendered with the …
> GH-98: Typography

- taccsite_cms/static/site_cms/css/src/_imports/settings/color.css
Restore missing variable (deleted via https://github.com/TACC/Core-CMS/pull/312).
- Restore variable.
Before
After
Difficult to test because homepage is not quickly reproducible locally, but I have it.
This variable is used by section object banner (from Frontera homepage redesign).
> Hotfix: Restore variable deleted during GH-98

- taccsite_cms/static/site_cms/css/src/_imports/settings/font.css
Fix font size that was saved wrong in https://github.com/TACC/Core-CMS/pull/312.
In the [reference document](https://confluence.tacc.utexas.edu/x/nh4FDg), I typed `26px` (good, from Designer) but did not update the `rem` value below from `2.4rem` (old) to `2.6rem` (new). __Bad Wes.__
_P.S. I have checked calculation (see "Math Applied" in doc) to confirm the value is 26 (not 24)._
> Quick: Fix wrong global font size 2.4 → 2.6

- taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
- taccsite_cms/static/site_cms/css/src/_imports/settings/color.css
Support border between sections, like [Frontera System Specs page](https://xd.adobe.com/view/90e6b252-0293-4243-7748-11d94a0763d0-e6d7/screen/ff0348ff-577d-450a-bef0-5326f3f7c705/specs/).
N/A
_The result will be seen when GH-88 is used to build a [Frontera System Specs page](https://xd.adobe.com/view/90e6b252-0293-4243-7748-11d94a0763d0-e6d7/screen/ff0348ff-577d-450a-bef0-5326f3f7c705/specs/)._
- __Fix__: Change incorrect border color to closes available (from [standard colors](https://github.com/TACC/Core-CMS/blob/main/taccsite_cms/static/site_cms/css/src/_imports/settings/color.css#L22-L30)) to match Design.
- _Minor_: Fix indentation on a standard color variable.
1. On the CMS, create markup like:
```
<div class="o-section o-section--style-light">content above line</div>
<div …
```
> Quick: Make borders visible between light sections

- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-style-guide.css
- taccsite_cms/templates/style_guide.html
Tweak styles for manual pattern library a.k.a. style guide.
- Do __not__ rely on `<section>` tags.
- Space content via heading tags.
- Include breadcrumbs (and extend standard).
1. Add `('style_guide.html', 'Style Guide'),` entry to `_CMS_TEMPLATES` in `secrets.py`. 
2. Select "Style Guide" as template for a test page.
3. On the test Style Guide page, add sections and multiple headings of different levels.
<details>
<summary>Samples</summary>
- [c-data-list.html.txt](https://github.com/TACC/Core-CMS/files/7035336/c-data-list.html.txt)
- a Snippet plugin with:
- HTML: (none)
- Template: `snippets/typography-guide.html`
</details>
3. (Optional) On the test Style Guide page, perform manual testing of complex CSS:
<details>
<summary>Markup & Checks</summary>
- heading as direct, first child …
> Quick: GH-253: Tweak Style Guide CSS

- taccsite_cms/default_secrets.py
- taccsite_cms/templates/fullwidth.html
- Closes #331
- e60ba1d Rename template from "Fullwidth" to "Full Width".
- 0c4a38f Remove excess code from `fullwidth.html` Template.
- afa0672 Related https://github.com/TACC/Core-CMS-Resources/pull/73.
N/A to Core. See "Related PRs".
Related yet Independent PRs:
- https://github.com/TACC/Core-CMS-Resources/pull/69
- https://github.com/TACC/Core-CMS-Resources/pull/73
> GH-331: Cleanup Fullwidth Template

- taccsite_cms/settings.py
Remove errant comma in `settings.py`.
I am surprised more branches aren't failing, given that this caused a server crash on `task/GH-101...`.
> Hotfix: Remove errant comma in settings

- taccsite_cms/contrib/bootstrap4_djangocms_link/cms_plugins.py
- taccsite_cms/contrib/bootstrap4_djangocms_picture/cms_plugins.py
- taccsite_cms/contrib/taccsite_data_list/cms_plugins.py
- taccsite_cms/contrib/taccsite_data_list/models.py
- taccsite_cms/contrib/taccsite_sample/cms_plugins.py
- taccsite_cms/contrib/taccsite_system_monitor/cms_plugins.py
- taccsite_cms/contrib/taccsite_system_monitor/models.py
Use `gettext` instead of `gettext_lazy`.
None. Hotfix during testing after FP-1194 (#341).
N/A
> Tested on [dev.tup](https://dev.tup.tacc.utexas.edu/) around 2021-09-17 @ 18:00 ([build](https://jenkins01.tacc.utexas.edu/job/Core_CMS/206/), [deploy](https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/561/)).
1. Have a CMS expectant server with a fresh CMS database.
2. Build an image off branch `task/FP-1194--submod-updates-for-testing--test-fix-for-tup`.\*
3. Deploy the image.
4. Ensure build and deploy succeed and site does not crash.
<details><summary>Footnotes</summary>
_\* This branch has the commit in this PR. It was cherry-picked to here. This branch is used for testing instead of `hotfix/support…`, because `hotfix/support…` is based off of `main` which was merged while its …
> Hotfix/FP-1194: Use gettext_lazy Not gettext (fixed tup-cms deploy)

- .gitignore
Support git-ignoring `settings_...py` files with suffixes and prefixes.\*
_\* So that `protx.settings_custom.py` and `settings_custom.protx.py` would both be ignored._
<details>
<summary>Suffixes</summary>
Gray files are ignored.
</details>
<details>
<summary>Prefixes</summary>
Not screen captured, but worked.
</details>
1. Add these files (where `___` is whatever text you want):
- `___.settings_custom.py`
- `___.settings_local.py`
- `settings_custom.___.py`
- `settings_local.___.py`
2. Confirm Git ignores all those files.
In `.gitignore`:
- move `settings_....py` to proper location
- support settings with prefixes and/or suffixes
> Quick: .gitignore: support settings w/ suffixes

- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-inline-dl.css
Restore bold for `<dt>` elements on Guide pages.
Closes #353.
- Add `font-weight: bold` to relevant file loaded by Guide stylesheet.
<details><summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Build: https://jenkins01.tacc.utexas.edu/job/Core_CMS/219
> Deploy: https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/606
1. Load a CMS that has page using the "Guide: Portal Technology Stack" template.
2. Scroll to bottom of page.
3. Check that "Frontend" and "Environment" _non-bulleted_ list items start with bold term.
> GH-353: Fix Missing Bold for Guide Pages

- taccsite_cms/static/site_cms/css/src/_imports/elements/html-elements.css
- taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
- taccsite_cms/static/site_cms/css/src/_imports/settings/color.css
- taccsite_cms/static/site_cms/css/src/_imports/tools/x-layout.css
- taccsite_cms/static/site_cms/css/src/_imports/tools/x-overlay.css
- https://github.com/TACC/Core-CMS-Resources/pull/94
The bulk of the UTRC styles and changes to Frontera required by changes to Core.
New UTRC Homepage and relevant Core fixes.
- [UTRC-356](https://jira.tacc.utexas.edu/browse/UTRC-356)
These changesets __are__ in this PR (even though they are closed).
- TACC/Core-CMS#367
- TACC/Core-CMS#361
- TACC/Core-CMS#363
- TACC/Core-CMS#362
- TACC/Core-CMS#365
- TACC/Core-CMS#366
<details>
<summary>Before Fixes</summary>
> Build: [job #225](https://jenkins01.tacc.utexas.edu/job/Core_CMS/225)
> Deploy: https://pprd.utrc.tacc.utexas.edu/custom-homepage (via [job #614](https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/614))
> Deploy: https://prod.utrc.tacc.utexas.edu/ (via [job #615](https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/615)) …
> UTRC-356: New UTRC Homepage & Relevant Core Fixes

- taccsite_cms/static/site_cms/css/src/_imports/elements/html-elements.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-document.css
- https://github.com/TACC/Core-CMS/pull/360
Which makes the missing top margin obvious for `<h1>` (which is used—rightly so—by UTRC).
- Use (browser) default margin-top values for headings.
- Thus support a `margin-top` for `<h1>`'s (and other headings on all pages, consistently).
- [CEPWMA-672](https://jira.tacc.utexas.edu/browse/CEPWMA-672)
| `<h1>` | Typography | Guide | Standard | Full Width |
| :-: | :-: | :-: | :-: | :-: |
| <img width="1151" alt="UTRC H1 Test" src="https://user-images.githubusercontent.com/62723358/135287801-aab80e12-82c0-4348-9d76-2a2690b71d02.png"> | ![Typography (MIgrate Styles Removed)](https://user-images.githubusercontent.com/62723358/135290646-3687cebd-7190-45df-b853-78720e4db589.png) | <img width="1298" alt="Guide Page (Happens to be the Typography page …
> FP-1234: Add Missing Top Margin for Headings

- taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
Fix a comment and move styles within the same rule.
- Fix a comment typo.
- Move related exisitng styles to under updated comment.
> Noop: Fix Comment Typo & Move Styles Down Under It

- taccsite_cms/templates/header_branding.html
- taccsite_cms/templates/header_logo.html
Fix typo (age unknown) in Core that preventing branding links from opening in new window (without JavaScript*).
_This was noticed on Brainmap, but affects all CMS's._
> \* Some CMS's has a JavaScript snippet that incidentally, dynamically fixes this.
- Fix typo so that `target` attribute renders value from settings.
0. Know how to [Test CMS Changes](https://github.com/TACC/Core-CMS/wiki/Test-CMS-Changes).
1. Load up CMS using [Frontera's `settings.custom.py`](https://github.com/TACC/Core-CMS-Resources/blob/main/frontera-cms/settings_custom.py#L28-L37) (because it meets requirements).
<details><summary>Requirements</summary>
- value of 3rd entry in array is external link
- value of 4th entry in array is `"_blank"`
</details>
2. Confirm that rendered link has `target="_blank"`
> Hotfix: Fix Branding Links not Opening in New Window

- taccsite_cms/settings.py
Better `INDEX_NAME` configuration. Aligns defaults with usage in `secrets.py`.
> Update settings.py: Haystack Connection `INDEX_NAME`

- taccsite_cms/static/site_cms/css/src/_imports/objects/o-offset-content.css
- https://github.com/TACC/Core-CMS-Resources/pull/109
Ensure "offset content" elements are full width on narrow windows.
[FP-1338](https://jira.tacc.utexas.edu/browse/FP-1338)
| Narrow Window | Wide Window |
| - | - |
| ![Narrow Window](https://user-images.githubusercontent.com/62723358/141350606-7d0b190d-1f2a-452a-a5f1-d3d2055b2ebc.png) | ![Wide Window](https://user-images.githubusercontent.com/62723358/141350603-b445e6f3-031e-490c-b881-28c51a568307.png) |
1. Open https://texascale-dev.tacc.utexas.edu/2020/feature-stories/twisted-physics/.
2. On wide window, find offset content (content offset from flow of article text).
3. Ensure offset content:
- _does **not**_ span 100% of container
- is offset
- text wraps around one end of it
4. On narrow window, find the content that was offset (it …
> Hotfix/FP-1338: Offset Content to be Full Width on Narrow Window

- taccsite_cms/templates/standard.html
- to also fix UTRC, https://github.com/TACC/Core-CMS-Resources/pull/108
Avoid horizontal scrollbar on pages known to use sections. (I am the only one adding sections, until [FP-1318](https://jira.tacc.utexas.edu/browse/FP-1318).)
[FP-1332](https://jira.tacc.utexas.edu/browse/FP-1332)
1. Load these pages to test:
- https://pprd.frontera-portal.tacc.utexas.edu/system [^0] (uses Core Standard template)
- https://pprd.utrc.tacc.utexas.edu/ [^0] (uses UTRC Home template)
1. Verify window has **no** horizontal scrollbar.
[^0]: Deployed via https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/849/ which loads image from branch `main--v3-3-0-with-hotfixes`.
This is not a long-term solution. Via [FP-1318](https://jira.tacc.utexas.edu/browse/FP-1318), I will fix the problem at the source (I do …
> Hotfix/FP-1332: Horz. Scrollbar Caused by Sections

- taccsite_cms/static/site_cms/css/src/_imports/objects/o-site.css
Do not hide header dropdown menus underneath body content.
[FP-1331](https://jira.tacc.utexas.edu/browse/FP-1331)
1. Load these pages to test:
- https://pprd.frontera-portal.tacc.utexas.edu/system [^0]
- https://pprd.frontera-portal.tacc.utexas.edu/ [^0]
1. Be logged into portal.
1. Login to Portal.
2. Return to CMS.
2. Open Portal dropdown menu.
3. Verify dropdown menu can be seen (test both pages).
[^0]: Deployed via https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/849/ which loads image from branch `main--v3-3-0-with-hotfixes`.
This [removed code](https://github.com/TACC/Core-CMS/pull/404/files#diff-a246d241c0f3a3caf41f81713609e56f78fb0dfdb873536a8867f87356f0df00L26-L29) had solved a problem that has since been solved by [other …
> Hotfix/FP-1331: Do Not Hide Header Drodpowns

- taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
Ensure callout title is always white, even inside a section which tries to color headings.
[FP-1333](https://jira.tacc.utexas.edu/browse/FP-1333)
1. Load https://pprd.frontera-portal.tacc.utexas.edu/system. [^0]
1. Scroll down to Callout.
2. Verify title is white.
3. Change `o-section--style-light` class of the ancestor `<section>` to `o-section--style-dark`.
4. Verify title is _still_ white.
[^0]: Deployed via https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/851/ which loads image from branch `main--v3-3-0-with-hotfixes`.
In [FP-1318](https://jira.tacc.utexas.edu/browse/FP-1318), I will move this and related styles to a new [trump](https://confluence.tacc.utexas.edu/x/IAA9Cw) file `s-section.css`.
<details>
<summary>Why?</summary>
Because a ["scope" (`s-`) …
> Hotfix/FP-1333: Callout Title Color

- taccsite_cms/templates/guides/getting_started.html
Remove sentence from Getting Started template.
- [Slack message from T.B.](https://tacc-team.slack.com/archives/C02HKF81CBA/p1637078725004400) (but **keep** _first_ sentence, **remove** _second_ sentence)
| Before (i.e. actual current state) | After (note: this is approximated) |
| - | - |
| ![Getting Started BEFORE](https://user-images.githubusercontent.com/62723358/142032907-48e62003-2c5b-4583-89fc-799bbf766fbb.png) | ![Getting Started AFTER (faked)](https://user-images.githubusercontent.com/62723358/142032912-e4f3400e-955e-4717-831c-0b72dad4aa16.png) |
| | Image is faked. Testing would show it as this, though. |
This is okay for Core, even though it was reported for 3Dem ([question](https://tacc-team.slack.com/archives/C02HKF81CBA/p1637080535007500), …
> Quick: Remove sentence from Getting Started doc

- taccsite_cms/static/site_cms/css/src/_imports/components/c-callout.css
- taccsite_cms/static/site_cms/css/src/_imports/tools/x-article-link.css
Prevent Callout clickable area from taking up whole page.
- [FP-1418](https://jira.tacc.utexas.edu/browse/FP-1418)
| - | - |
| ![FP-1418 After](https://user-images.githubusercontent.com/62723358/146276240-964491cd-c1fa-4e41-abc0-79e14878c7d9.png) |  ![FP-1418 Before](https://user-images.githubusercontent.com/62723358/146276245-c8e66819-4ce9-4adc-895d-8fd4427fb620.png) |
0. Create/Test an instance of Callout plugin (on branch/server with fix).
1. Ensure clickable area is contained within its blue box.
> FP-1418: Callout Link Clickable Area Fix

- taccsite_cms/static/site_cms/css/src/_imports/elements/html-elements.css
- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-document.css
Move color and border styles for code and sample computer output to the Guide page styles with which it belongs.
Migrate CSS for `<code>` and `<samp>` to `s-document.css` stylesheet (from stylesheet that is loaded by `site.css`).
1. Create a `<code>` element on a page that _is **not**_ using a Guide page template.
2. Test that `<code>` element _does **not**_ have a border nor a background color.
3. Review a `<code>` element on a page that _**is**_ using a Guide page template.
4. Test that `<code>` element _**does**_ have a border nor a background color.
<details>
<summary>Background</summary>
This CSS was for doc page but put in Site, because I thought it was styled well enough for global use. Then during BM-6 I used `<code>` inside Callout... ugly, so unsuitable for Site CSS.
</details>
> Quick: Move Code & Samp CSS from Site to Doc Page

- taccsite_cms/static/site_cms/css/src/_imports/components/c-card.css
- taccsite_cms/static/site_cms/css/src/_imports/components/c-card.html
- taccsite_cms/static/site_cms/css/src/site.css
Add "Card" UI pattern, for only "Frontera About page" right now:
```
.c-card .c-card--frontera-about-page
```
<details>
<summary><strong>About the Name</strong></summary>
> Suggestions Welcome
This pattern is only designed for one page ([Frontera About](https://xd.adobe.com/view/f3dad8d1-88ee-40eb-b8da-667b00e4f876-a689/screen/8bb9a7de-c5b2-493b-b897-d967ca8a57ec/specs/)). It might be used on some TACC pages\*. So, for now, the style can be `c-card--frontera-about-page`. It can have a new name in the future. The old name can still work. Here's how:
1. In CSS, change `.old-name` to `.new-name`.
2. In CSS, add `.old-name { @extend .new-name; }`.
_\* [TACC Services, User](https://xd.adobe.com/view/75cebc14-7368-4453-bb25-f975528952ac-209d/screen/c0898d6b-2fd9-472a-bcd7-1ae9d4f9a015/) (see …
> FP-1290: Card UI Pattern (Frontera About Page)

- taccsite_cms/static/site_cms/css/src/_imports/tools/x-layout.css
Developer-facing tweaks to CSS documentation.
- Fix a typo.
- Add deprecation note.
> Minor: Fix: x-layout CSS docblock typo

- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-article-list.css
Make sure clickable area of article list link always opens new page.
* [FP-1408](https://jira.tacc.utexas.edu/browse/FP-1408)
Prevent clickable area from changing shape while link is actively being clicked i.e. during `:active` state.
[FP-1408.Prod.vs.Local.mov](https://user-images.githubusercontent.com/62723358/149438828-4253b8d3-96cd-4435-ac88-bf2b30f2c70a.mov)
> ℹ️ Bug is now not reproducible on prod (cuz of snippet-based fix). You can reproduce the bug on pre-prod.
> **local**: [setup instructions](https://github.com/TACC/Core-CMS/wiki/Test-CMS-Changes) — recreating page takes too long  
> **remote (sans fix)**: [pprd.frontera-portal.tacc.utexas.edu](https://pprd.frontera-portal.tacc.utexas.edu/)  
> **remote (with fix)** (via jenkins): …
> FP-1408: (Frontera) Fix Clickable Area of Article List Link

- taccsite_cms/settings.py
Quickly create existing TACC Section _pattern_ via already-installed Django Style _plugin_.
_CMS Admin/Designer has approved (via private review), but implementation should have dev review._
* [FP-1318](https://jira.tacc.utexas.edu/browse/FP-1318)
To our default `settings`:
* Add `DJANGOCMS_STYLE_CHOICES` ([docs](https://github.com/django-cms/djangocms-style#configuration)).
* to allow user to quickly create light Section or dark Section
* Add `DJANGOCMS_STYLE_TAGS` ([docs](https://github.com/django-cms/djangocms-style#configuration)).
* to support `<aside>`
* to document expected usage
* to reference [proof-of-concept improvement](https://github.com/TACC/Core-CMS/compare/poc/djangocms_style-automatic-tag)
> ⚠️ This video shows more class choices, because it includes #419 also. …
> FP-1318: Create Section Pattern via Style Plugin

- taccsite_cms/static/site_cms/css/src/_imports/components/c-callout.css
Change Callout pattern's grid's row and column dimensions to fix [FP-1502](https://jira.tacc.utexas.edu/browse/FP-1502) bug.
[FP-1502](https://jira.tacc.utexas.edu/browse/FP-1502)
| State | Image |
| - | - |
| Before | <img width="1170" alt="FP-1502 Broken" src="https://user-images.githubusercontent.com/62723358/153504081-a1c705c5-665e-43db-96f6-a627b034a549.png"> |
| After | <img width="1170" alt="FP-1502 Fixed" src="https://user-images.githubusercontent.com/62723358/153504005-5973f9d2-b4e2-41a8-bbe9-69ad92bf6e0d.png"> |
1. Create a Callout pattern (`.c-callout` with `img` and `h2` and `p`).
2. Ensure the image is taller than the description and title together.
3. Confirm no excess vertical space between title and description.
> FP-1502: Fix Callout Title Height

- taccsite_cms/static/site_cms/css/src/_imports/components/c-callout.css
Removed dotted underline added to Callout links when in :focus state.
* [FP-1359](https://jira.tacc.utexas.edu/browse/FP-1359)
- Added a `:focus` selector for the `a.c-callout` selector which specifies no text decoration on focus state.
1. On local Core-CMS, duplicate the 'Quick Start Guide' Style object from [dev Frontera](https://dev.fronteraweb.tacc.utexas.edu/system/) and all of its nested objects.
2. In Style object, change 'o-section--style-light' to 'o-section--style-dark'.
3. In Developer Tools, on the `<a>` (the blue box), click "Force element state" and then click ":focus".
4. Confirm that no dotted underline appears on the callout text.
Before: 
After:
> bug/FP-1359: Callout Plugin Active+Focus State Anomaly within Dark Section

- taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
- taccsite_cms/static/site_cms/css/src/_imports/tools/x-fake-border.css
Fix UI bugs introduced in Section pattern since their new code in #433.
- __[FP-1524](https://jira.tacc.utexas.edu/browse/FP-1524)__
- Review Ticket: [FP-1530](https://jira.tacc.utexas.edu/browse/FP-1530)
<details>
<summary>Use <code>box-shadow</code>, not <code>::before</code> to extend section backgrounds.</summary>
- Add the `box-shadow` solution (tiny).
- Remove the `::before` solution (massive).
- Move the `border` code.
- Note [FP-1470](https://jira.tacc.utexas.edu/browse/FP-1470) tasks.
</details>
<details open>
<summary>Round 2</summary>
| | Before | After, Main | After, Detail
| - | - | - | - |
| Frontera Home | ![FP-1524 Frontera Home Before](https://user-images.githubusercontent.com/62723358/155414880-4cf9a5d4-2b20-4b64-b579-b912d6917689.png) | ![FP-1524 Frontera Home New …
> FP-1524: Section Pattern: Simpler Extended Background

- docker-compose.dev.yml
Update ElasticSearch version by changing out base image for docker service.
* [FP-1540](https://jira.tacc.utexas.edu/browse/FP-1540)
* Update `elasticsearch` image to one with version `7.17.0`.
> **Instructions for Others After Merge**
> Local environments may have a security issue. Please checkout Core-CMS `main` branch and pull the latest, then run `docker compose -f docker-compose.dev.yml up --force-recreate --build elasticsearch`. (If you have a _custom_ docker compose file, update it to match the change from [PR #456](https://github.com/TACC/Core-CMS/pull/456/files) and run the command but reference your custom file.)
1. Re-build `elasticsearch` container.
2. Enter shell in `elasticsearch` container.
3. Run `curl -XGET 'http://localhost:9200`. …
> FP-1540: Hotfix: Update ES to Fix Security Issue

- taccsite_cms/templates/snippets/manual-pattern-library/o-grid.html
- taccsite_cms/templates/snippets/manual-pattern-library/o-section.html
Add `id` markup attributes to manual pattern library snippets.
- Slugify pattern lib snippet content.
- Add text as value of new `id` attr in heading.
> Quick: ID Attrs for Manual Pattern Lib. Snippets

- taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
- taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.html
- taccsite_cms/static/site_cms/css/src/_imports/tools/x-fake-border.css
- Add third Section style for [new About page design][design].
- Use variables for DRY-er Section code.
_Code rearranged for legibility, so changes may be easier to review via [split diff](https://github.blog/2014-09-03-introducing-split-diffs/)._
* [FP-1470](https://jira.tacc.utexas.edu/browse/FP-1470)
- Add `.o-section--style-muted`.
- Change `.o-section` code to use more variables.
- Add `.x-fake-border--inset-horz-bottom` & `...--inset-horz-both`.
- Change `.x-fake-border` code to use more variables.
ℹ  Window size for testing and screenshots was 991px.
| Where | Before | After |
| - | - | - |
| Patterns | [FP-1470 Patterns Local Before](https://user-images.githubusercontent.com/62723358/156847320-8e5abc4d-a105-4620-8a5f-003f1db69b29.jpeg) | [FP-1470 Patterns Local …
> FP-1470: Section Pattern: Third Style (and Fix to Dark Style)

- taccsite_cms/templates/README.md
Fix a typo... well, really remove underscore that was accurate before a major change.
> Noop: FIx Typo in Templates README

- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-document.css
- taccsite_cms/templates/guides/data_transfer.globus.html
- taccsite_cms/templates/guides/data_transfer.html
- Shrink […] Data Transfer guide images consistently on wide screens.
- Link images so they open in new tab. (Add bug fix for it.)
* __fixes: [FP-1410](https://jira.tacc.utexas.edu/browse/FP-1410)__
* _created after work began: [FP-1542](https://jira.tacc.utexas.edu/browse/FP-1542) (to replace the URLs with ones to locally-available images)_
- delete redundant code
- add `<a>`'s
- set absolute max-width for images, but otherwise (i.e. mobile) let images grow to fill screen
- shrink one image a little extra
- prevent new bug of really large invisible link
1. Load these pages[^1]:
- https://dev.cep.tacc.utexas.edu/guides/data-transfer-guide/
- https://dev.cep.tacc.utexas.edu/guides/globus-data-transfer-guide/
2. Scroll to see all images while on wide screen.
3. Scroll to see all images …
> FP-1410: Shrink Guide Images & Add Links to Open in New Tab

- taccsite_cms/settings.py
Fix build error.
<details>
```
Mar 23 10:49:16 dev.cep.tacc.utexas.edu portal_cms[27210]: django.core.exceptions.ImproperlyConfigured: The app module <module 'taccsite_custom.README-cms' (namespace)> has multiple filesystem locations (['/code/taccsite_custom/README-cms', '/code/./taccsite_custom/README-cms']); you must configure this app with an AppConfig subclass with a 'path' class attribute.
```
</details>
* [v3.5.0](https://github.com/TACC/Core-CMS/releases/tag/v3.5.0)
* https://github.com/TACC/Core-CMS-Resources/pull/125
- __Ignore `_readme` in `taccsite_custom` when installing apps.__
- `taccsite_custom`
- Rename `README-cms` to `_readme-cms`.
- Rename `_readme-cms/static` and `.../templates` to `_static/` and `_templates/`.
- Add step for new project: "Read `/_readme-cms`."
1. …
> Hotfix/Resolve README CMS Deploy Fail

- Dockerfile
> Would recommend changing line 1 of [Dockerfile] to:
> `FROM python:3.8-buster as python-base`
> 
> in order to always pick up patch versions of 3.8 on new builds
> — [Sal in PR #448](https://github.com/TACC/Core-CMS/pull/448/files/394751dd3bcd98c5622a76d92b96aaf4bce899a9#r833424225)
> chore(python): support 3.8.N+ base image

- taccsite_cms/settings.py
Altering the bare except when importing custom files to ModuleNotFoundError so that any issues with existing custom files can be seen.
1. Put an error in one of the optional custom files (i.e. settings_custom.py secret.py or settings_local.py)
2. Ensure that error is raised
> Improve handling of missing custom settings

- bin/build-css-via-cli.js
Fix styles build failure by updating input path in styles build command.
<details><summary>How did this happen?</summary>
#489 test case was not specific enough. If first build is not cleared, and second build fails, number of files built is the same. Test case did not mention clearing first build nor checking for build errors.
</details>
- [FP-1648](https://jira.tacc.utexas.edu/browse/FP-1648)
- fixes https://github.com/TACC/Core-CMS/pull/489
- change `--input` path to only include CSS files (not include everything)
```
npm ci
npm run build
```
1. See how many stylesheets are built on `v3.7.0` tag:
- `git checkout v3.7.0`
- `npm ci`
- `npm run build`
- `find taccsite_cms/static/site_cms/css/build -type f | wc -l`
1. Clear CSS build output:
- `rm -rf …
> feat(fp-1648): only build css files

- taccsite_cms/_settings/form_plugin.py
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.forms.css
- taccsite_cms/static/site_cms/css/src/_imports/elements/form.css
- taccsite_cms/static/site_cms/css/src/_imports/settings/color.css
- taccsite_cms/templates/djangocms_forms/form_template/default.html
Miscellaneous bug fixes and updates for form plugin.
- [FP-1700](https://jira.tacc.utexas.edu/browse/FP-1700)
- [TUP-285](https://jira.tacc.utexas.edu/browse/TUP-285)
- builds off https://github.com/TACC/Core-CMS/pull/500
- referenced by https://github.com/TACC/Core-CMS/pull/498
See commit messages.
| website | status | notes |
| - | :-: | - |
| [frontera (pprd)](https://pprd.frontera-portal.tacc.utexas.edu/test/tup-230-form-plugin/) | ✓ |
| [core (dev)](https://dev.cep.tacc.utexas.edu/test/tup-230-form-plugin/?edit_off=true) | ✓ |
| [apcd (pprd)](https://apcd-qa.tacc.utexas.edu/test/tup-230-form-plugin/) | ✓ |
| tup (dev) | ⓧ | pending [FP-1700](https://jira.tacc.utexas.edu/browse/FP-1700) to appropriately prevent [deploy failure](https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/1 …
> V3.6.0/form plugin fixes

- bin/build-css.js
- package-lock.json
- package.json
Remove extraneous dependency by using Core-Styles Node module, not CLI.
- inspired by [TUP-274](https://jira.tacc.utexas.edu/browse/TUP-274)
- remove devDependency `node-cmd`
- change how Core-Styles is used (Node module, not CLI)
Ensure `npm run build` still works e.g.
0. Checkout `main`.
1. Comment [`.gitignore`'s `build`](https://github.com/TACC/Core-CMS/blob/7b62db1/.gitignore#L15).
2. Delete `taccssite_cms/static/site_cms/css/build`.
3. Build `npm run build --project=frontera-cms`.
4. Stage `taccssite_cms/static/css/build`.
5. Checkout `quick/remove-need-for-node-cmd-dep`.
6. Build `npm run build --project=frontera-cms`.
7. Verify no un-staged changes (besides `.gitignore`).
> chore(core-styles): build css via JS not CLI

- taccsite_cms/templates/assets_site_delayed.html
Support icons even if Portal is not active.
- [FP-1706](https://jira.tacc.utexas.edu/browse/FP-1706)
- in template, remove portal conditional around icon load
0. Have setting `INCLUDES_CORE_PORTAL` set to `False`.
1. Use a Font Awesome icon on a page.
2. Verify icon shows.
We do not want FA icons, but there is at least one usage.
Usage: Frontera homepage, "(→) See All News"
> fix: load fa icons even if no portal

- README.md
- package-lock.json
- package.json
- taccsite_cms/static/site_cms/css/src/site.css
Prevent `<figure>` element styles from bleeding into other patterns e.g. `.s-system-specs`.
- [FP-1663](https://jira.tacc.utexas.edu/browse/FP-1663)
- builds off https://github.com/TACC/Core-CMS/pull/495
- requires https://github.com/TACC/tup-ui/pull/17
__<sup>please review even if merged;</sup>__ <sup>it is a beta version change merged into a testing branch<sup>[^2]
- do not load `<figure>` element styles
- load core-styles at https://github.com/TACC/tup-ui/pull/17
| server | page |
| - | - |
| frontera | https://dev.fronteraweb.tacc.utexas.edu/system/ |
| cep | https://dev.cep.tacc.utexas.edu/design-system/ui-patterns/c-callout/ |
| cep | https://dev.cep.tacc.utexas.edu/design-system/ui-patterns/bootstrap-figure/ |
<details><summary>1. Verify System Monitor <code>&lt;figure&gt;</code> …
> After/tup 271  fp 1663 system spec figure styles

- package-lock.json
- package.json
- taccsite_cms/static/site_cms/css/src/site.css
Fix accidentally hiding Frontera header underneath its homepage banner.
I.e. Updates `.o-section--banner` and `main` styles in `o-section.css` from Core Styles.
- [FP-1666](https://jira.tacc.utexas.edu/browse/FP-1666)
- builds off https://github.com/TACC/Core-CMS/pull/495
- requires https://github.com/TACC/tup-ui/pull/19
__<sup>please review even if merged;</sup>__ <sup>it is a beta version change merged into a testing branch<sup>[^2]
- load core-styles at https://github.com/TACC/tup-ui/pull/19
- prevent styles build error / do **not** load file that is deleted by @tacc/core-styles@0.6.0-beta.1
| server | page |
| - | - |
| frontera | https://dev.fronteraweb.tacc.utexas.edu/ |
| cep | https://dev.cep.tacc.utexas.edu/design-system/ui-patterns/o-section/ |
<details><summary>1. Verify banner …
> After/tup 271  fp 1666 frontera header hidden

- README.md
- bin/build-css-via-cli.js
- package-lock.json
- package.json
- taccsite_cms/static/site_cms/css/.postcssrc.yml
- taccsite_cms/static/site_cms/css/README.md
- taccsite_cms/static/site_cms/css/src/README.md
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.css
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.item.css
- taccsite_cms/static/site_cms/css/src/_imports/settings/color.css
- taccsite_cms/static/site_cms/css/src/_imports/settings/font.css
- taccsite_cms/static/site_cms/css/src/_imports/settings/space.css
- taccsite_cms/templates/snippets/manual-pattern-library/c-callout.html
- taccsite_cms/templates/snippets/manual-pattern-library/c-nav.content.html
- taccsite_cms/templates/snippets/manual-pattern-library/o-grid.content.html
- taccsite_cms/templates/snippets/manual-pattern-library/o-section.content.html
Load core styles from new monorepo instead of recent standalone repo.
For TUP, a monorepo ([TACC/tup-ui](https://github.com/TACC/tup-ui/)) houses core styles, core components, and new UI client.
- [TUP-271](https://jira.tacc.utexas.edu/browse/TUP-271)
- mimics https://github.com/TACC/Core-Portal/pull/651
- load `@tacc/core-styles` from [TACC/tup-ui:/libs/core-styles](https://github.com/TACC/tup-ui/tree/tup-starter-nx--core-styles-integration/libs/core-styles) instead of [TACC/Core-Styles](https://github.com/TACC/Core-Styles)
- update paths to stylesheets
- update symlinks to sample markup
See [How to Test Core-Styles Version Change](https://github.com/TACC/Core-CMS/wiki/How-to-Test-Core-Styles-Version-Change).
[`TUP-271-cms.log`](https://github.com/TACC/Core-CMS/files/8970388/TUP-271-cms.l …
> TUP-271: Use Core-Styles from TUP-UI

- taccsite_cms/settings.py
- taccsite_cms/templatetags/get_url_match.py
Add `get_url_match` filter to render string that matches given pattern from current page URL.
This supports annual stylesheets for Texascale.
<details><summary>✓ To Do</summary>
- [~~FP-1652~~](https://jira.tacc.utexas.edu/browse/FP-1652) — _do without for now_
</details>
- [FP-1439](https://jira.tacc.utexas.edu/browse/FP-1439)
- required by https://github.com/TACC/Core-CMS-Resources/pull/148
- mirrors https://github.com/TACC/Core-CMS/pull/490
- add `get_url_match` template filter
- have texascale use `get_url_match` i.e. [TACC/Core-CMS-Resources#148](https://github.com/TACC/Core-CMS-Resources/pull/148)
**Local**. Have two pages that use Texascale templates and each has a year in it's url, e.g.:
* http://localhost:8000/texascale/2019/
* http://localhost:8000/texascale/2018/
**Remote**. …
> V3.4.0/fp 1439 yearly site theme for texascale

- README.md
Improve/Fix NPM link instructions.
<details>
0. Current commands listed are **not** working and are **not** what I use successfully.
- I always add `--save-dev` to the `npm link` command **and** remember **not** to commit the `package.json` change.
2. Core-Styles has recently moved to [a new repo](https://github.com/TACC/tup-ui/tree/main/libs/core-styles).
3. I found https://hirok.io/posts/avoid-npm-link, which suggests [npx link](https://github.com/privatenumber/link).
</details>
None
- Reduced `npm link` instructions.
- Replaced [`npm link`](https://docs.npmjs.com/cli/v8/commands/npm-link) with [`npx link`](https://github.com/privatenumber/link).
Run these commands (change `path-to/core-styles`). Expect no errors.
```
npm ci
npx link path-to/core-styles # e.g. npx link …
```
> docs(README): npm link instructions

- package-lock.json
- package.json
Load CSS changes to fix overflow management on section banners:
- fix from core-styles (tup-ui)
- adapt to new markup from taccsite_custom (Core-CMS-Resources)
---
⚠️ This fix requires changing markup via CMS admin. I will do so on prod immediately after deploy. See "Notes". ⚠️
---
- [FP-1723](https://jira.tacc.utexas.edu/browse/FP-1723)
- requires https://github.com/TACC/tup-ui/pull/29
- requires https://github.com/TACC/Core-CMS-Resources/pull/152
1. Open [frontera (pre-prod)](https://pprd.frontera-portal.tacc.utexas.edu); see **no** banner overflow.
1. Open [frontera (dev)](https://dev.fronteraweb.tacc.utexas.edu); see **no** banner overflow.
1. Compare **responsive design**[^1] to [frontera (prod)](https://frontera-portal.tacc.utexas.edu); see **no** difference.
1. Open [utrc …
> fix(core-styles, frontera, utrc): fp-1723 section banner overflow mgmt

- taccsite_cms/templates/base.html
Auto-updated current year for __default__ footer.
_This is a minimal fix. If admin add s custom content too footer, admin must still keep year up to date._
N/A
- replace manual year with template logic to get current year
1. Load a CMS that this branch and no content in its footer.
2. Confirm footer shows default text and current year.
> fix(templates): programatic current year in footer

- taccsite_cms/static/djangocms_text_ckeditor/css/cms.ckeditor.css
Implement the #568 fix from PR #590 until we update our ckeditor to v5.
This will save H.P. (main CMS admin/designer) so many tiny bits of time, because she must resize a modal every time she wants to edit source, which is many times everyday.
N/A
- extend `djangocms-text-ckeditor` css
- duplicate the relevant fix
1. Be logged into CMS as admin.
2. Add a Text plugin instance.
3. Edit Text plugin instance content as source (the "[<>] Source" button, top-right).
4. Confirm the textarea (in which to edit source markup) fills available vertical space.
<sub>I am using Dark Reader browser extension; that is why it is dark gray, not white.</sub>
> fix(django): implement djangocms-text-ckeditor#568

- taccsite_cms/_settings/auth.py
- taccsite_cms/settings.py
- Isolate the `LDAP_ENABLED` setting.
- Document how to disable LDAP.
- [TUP-321](https://jira.tacc.utexas.edu/browse/TUP-321)
- replaces https://github.com/TACC/Core-CMS/pull/535
1. Disable LDAP on a server following the steps: https://dev.tup.tacc.utexas.edu/
2. Try to login with LDAP credentials.
3. Verify you cannot login.
N/A
> TUP-321: Make it Clearer How to Disable LDAP Settings

- poetry.lock
- pyproject.toml
Adds the ipython package to the environment, via `poetry add ipython`
By default, django will use ipython for the django shell if it is installed:
https://docs.djangoproject.com/en/2.2/ref/django-admin/#shell
1. Build image: `make build`
2. Start it up: `make start`
3. Bring up django shell from within container:
```
docker exec -it core_cms bash
./manage.py shell
```
4. Confirm ipython is installed.
**Before (without ipython):**
**After (with ipython):**
> Add ipython to django shell

- package-lock.json
- package.json
- taccsite_cms/static/site_cms/css/src/site.css
Load a Core-Styles that has `o-float-content--left|right`.
- [ECEP-215](https://jira.tacc.utexas.edu/browse/ECEP-215)
- requires https://github.com/TACC/Core-Styles/pull/42
- load core-styles that has the new class
1. Load test pages:
- https://prod.ecep.tacc.utexas.edu/resources/toolkits-guides/landscape-reports-image-test/ (clears float)
- https://prod.ecep.tacc.utexas.edu/resources/toolkits-guides/landscape-reports-image/ (does not clear float)
- https://prod.ecep.tacc.utexas.edu/resources/models-state-change/how-change-state/
2. Verify narrow screen shows full width image.
3. Verify medium screen shows floated image.
| | 1680px | 992px | 768px |
| - | - | - | - |
| test  1 | ![test 1 1680px](https://user-images.githubusercontent.com/62723358/184014708-dc76730f-76f1-4c45-83f1-4995839109 …
> feat: ecep-215 o-float-content--left|right

- pyproject.toml
- taccsite_cms/_settings/form_plugin.py
Ensure file upload works i.e. install form plugin at https://github.com/avryhof/djangocms-forms/commit/d8a69ef.
- [FP-1782](https://jira.tacc.utexas.edu/browse/FP-1782)
- remove comment about known issue that had been fixed
- remove comment about known issue that is recently fixed i.e. https://github.com/avryhof/djangocms-forms/issues/14
- remove warning about feature limitations
Not yet remotely deployed.
1. Create form plugin instance.
2. Add field for "File Upload".
3. Submit form.
4. In "Site administration", open "Form submissions".
5. Open your submission there.
6. Confirm uploaded file is listed (as a link).
7. Confirm you can open/download the file.
| my local form | list uploaded file | view uploaded file |
| - | - | - |
| …
> fix: fp-1782 form plugin file upload

- taccsite_cms/_settings/email.py
1. Do not add default e-mail settings to use a remote mail server.
2. Warn others not to accidentally do the same.
- [FP-1823](https://jira.tacc.utexas.edu/browse/FP-1823)
- required by https://github.com/TACC/Core-CMS-Resources/pull/165
- required by https://github.com/TACC/Core-CMS-Custom/pull/7
- remove hard-coded remote e-mail server from a comment
- change default e-mail setting to send mail content to console
- warn developer about misuse of e-mail settings
1. Clone repo [TACC/Core-CMS] **or** [TACC/Core-CMS-Custom].
2. Set it up to run a CMS configured for APCD.
- For [TACC/Core-CMS], follow its `/README.md`.
- For [TACC/Core-CMS-Custom], follow its `/apcd-cms/README.md`.
3. Create a form using the Form plugin.
4. Configure the form to send an e-mail upon submission.
5. Submit the …
> fix(settings): fp-1823 do not support email server by default

- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.forms.css
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.forms.hacks.css
Temporary solution for unsupported field configuration of the Django CMS Form plugin. For a Multi Checkbox field that is Required, render a message to alarm admins (so they do not use this broken combination) and a message to warn users (in case admin ignored error), so users know how to bypass the problem.
- [FP-1808](https://jira.tacc.utexas.edu/browse/FP-1808)
- relied on by https://github.com/TACC/Core-CMS-Custom/pull/8
- import new hack stylesheet
- author messages for user and admin about unsupported form field
Remote: https://apcd-qa.tacc.utexas.edu/test/fp-1773-e-mail-test/
or Local: https://localhost:8000
0. Log in to CMS running off this branch.
2. Create form on a Django CMS page with a Multi-Checkbox field.
3. Ensure the Multi-Checkbox field you add is required. (Check the box …
> feat(css): fp-1808 warning, unsupported form field

- package-lock.json
- package.json
- taccsite_cms/static/site_cms/css/src/_imports/components/c-button.css
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.forms.css
- **Buttons should be automatic width by default.**
- Fix button font size, given Core Styles update.
- More specific selector for Django CMS form button styles.
- [FP-1791](https://jira.tacc.utexas.edu/browse/FP-1791)
- requires https://github.com/TACC/Core-Styles/pull/49
- required by https://github.com/TACC/Core-CMS-Custom/pull/37
- **Load auto width for buttons from Core Styles.**
- Use accurate font-size variable.
- Add `[type="submit"]` because not every button is primary.
- Add `.form-button` because it should appear in a search.
Pages:
- https://apcd-qa.tacc.utexas.edu/register/request-to-submit
- https://apcd-qa.tacc.utexas.edu/register/request-to-submit-form
Steps:
1. Submit button is brown.
2. All form buttons are as wide as their text content (plus padding).
3. All form …
> fix(css): fp-1791 button auto width & django cms form button tweak

- taccsite_cms/urls.py
Only set CMS "core/portal/nav" URL if "INCLUDES_PORTAL_NAV = True".
<details><summary><strong>Background</strong></summary>
1. Portal's intercepts "core/markup/nav/" URL.
2. CMS (via new "feature") intercepts "core/markup/nav/" URL.﹡
3. CMS’s takes precedence (instead of Portal’s, as I planned).
4. CMS Portal nav template is (intentionally) empty.
5. Login button (i.e. Portal nav) is not visible.
﹡Intended as a fallback for when Portal is not present. Source: #557
</details>
- fixes https://github.com/TACC/Core-CMS/pull/557
- add a comment
- **add condition for CMS portal nav URL**
1. Test CMS with a local Portal instance.
<sup>See wiki article [Test CMS Changes](https://github.com/TACC/Core-CMS/wiki/Test-CMS-Changes) sections "Via …  on Local Portal", or teach me a simpler way.</sup>
2. …
> fix: tup-340 portal nav not loading

- package.json
- taccsite_cms/settings.py
Serve the Pattern Library as static files.﹡
<sup>﹡ Until WMA can provide a solution that is better (see "Notes").</sup>
- [FP-1500](https://jira.tacc.utexas.edu/browse/FP-1500)
- feat: serve ui pattern library as static files (3e85136)
- fix: remove alternate local server for pattern library (00c0f66)
Remote: https://dev.tup.tacc.utexas.edu/static/ui/index.html
1. Load CMS.
2. Open `/static/ui/index.html`.
3. See Pattern Library.
| Localhost | TUP CMS |
| - | - |
| ![fp-1500](https://user-images.githubusercontent.com/62723358/199261054-8f0872f5-8591-4039-8416-2e9841249d0d.png) | ![fp-1500 on tup](https://user-images.githubusercontent.com/62723358/199265961-4d72ba01-c144-440e-b410-cff789669150.png) |
<details><summary>My <strong>complaints</strong> (I accept for now) about this …
> feat: fp-1500 serve ui pattern lib (as static files)

- package-lock.json
- package.json
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.forms.css
- taccsite_cms/static/site_cms/css/src/site.css
Add APCD styles (for Django form plugin classes).
- [FP-1828](https://jira.tacc.utexas.edu/browse/FP-1828)
- requires https://github.com/TACC/Core-Styles/pull/56
- required by https://github.com/TACC/Core-CMS-Custom/pull/42
- feat: load [related Core Styles](https://github.com/TACC/Core-Styles/pull/56)
- fix: no `.help-text` margin if after a label
- fix: allow `.help-text` child elements' to retain their font style
- chore: remove unnecessary .`field-wrapper` item alignment
- feat: style "asterisk" text for required **and** _not_-required fields
See https://github.com/TACC/Core-CMS-Custom/pull/42.
> feat(css): fp-1828 move apcd styles to core

- taccsite_cms/templates/cms_menu.html
- taccsite_cms/templatetags/limit_visibility_in_menu.py
Feature﹡ to limit menu visibility for pages based on user group.
<sup>﹡ Actually, a noop example implementation and expected usage.</sup>
- [FP-1837](https://jira.tacc.utexas.edu/browse/FP-1837)
- required by https://github.com/TACC/Core-CMS-Custom/pull/46
- use new template tag to make menu item render conditional
- add new template tag with example menu view permission logic
1. Have a local CMS with pages in navigation.
2. Checkout this branch.
3. Load CMS.
4. Verify all your pages that have been visible in menu before this branch are still visible in menu.
See https://github.com/TACC/Core-CMS-Custom/pull/46.
Documentation: [Django CMS - Developer Guide - Limit Menu Visibility per User Group](https://confluence.tacc.utexas.edu/display/~wbomar/Django+CMS+-+Developer+Guide+-+Limit+Menu+Vis …
> feat: fp-1837 limit nav menu item visibility by group

- bin/build-css.js
- package-lock.json
- package.json
- taccsite_cms/static/site_cms/css/src/_imports/components/c-button.css
- taccsite_cms/static/site_cms/css/src/_imports/elements/irregular-link.css
- taccsite_cms/static/site_cms/css/src/_imports/settings/color.css
- taccsite_cms/static/site_cms/css/src/site.css
- taccsite_ui/fractal.config.js
- taccsite_ui/styles/cms
- taccsite_ui/styles/projects
- Many major and minor fixes to demo.
- Load a few new patterns.
- requires https://github.com/TACC/Core-Styles/pull/66
- feat(css): allow making all hyperlinks irregular
- fix(css): rely on core styles colors 
- fix(css): c-button font size to ignore --as-link 
- fix(css): let core-styles control c-button max-width ([it got fixed](https://github.com/TACC/Core-Styles/commit/369b5a1))
- feat(core-styles): load newly added or documented patterns 
- fix(taccsite_ui): build & load core-styles to fix broken paths in demo
- fix(core-styles): load relevant fixes
See https://github.com/TACC/Core-Styles/pull/66.
> fix: pattern demo repair suite

- taccsite_cms/templatetags/limit_visibility_in_menu.py
The CMS News menu children do/can not have a `reverse_id`. So when `limit_visibility_in_menu.py` looks for it in one of those, a fatal error occurrs.
- [TUP-118](https://jira.tacc.utexas.edu/browse/TUP-118)
<sub>I found the bug while implementing CMS News on TUP.</sub>
- check for `reverse_id` before using it
1. [Install CMS News.](https://confluence.tacc.utexas.edu/pages/viewpage.action?pageId=265425804)
2. [Add an article.](https://confluence.tacc.utexas.edu/pages/viewpage.action?pageId=182911007#UserGuideBlog/NewsInstructions-FromanEmptyCMS)
3. Load any CMS page (not the admin interface).
> fix(templatetags): limit visibility + cms news = crash

- taccsite_cms/static/djangocms_text_ckeditor/css/cms.ckeditor.css
Fix Plugin editor height being too small (when within Text plugin editor).
- [FP-1949](https://jira.tacc.utexas.edu/browse/FP-1949)
- changed remote URL to revert [#541](https://github.com/TACC/Core-CMS/pull/541) "fix"
- added comment about [#540](https://github.com/TACC/Core-CMS/pull/540) fix
- **added CSS to fix height of editor**
1. Open CMS page in Edit mode.
2. Add Text plugin instance.
3. While in Text plugin instance, add any Plugin (via 🧩 icon).
4. Verify height of plugin editor window is as tall as containing element.
| - | - |
| ![actual](https://user-images.githubusercontent.com/62723358/206763337-95a4151c-99ec-4e3b-b06d-47994b575e69.png) | ![expected](https://user-images.githubusercontent.com/62723358/206763364-b90de5f6-dcf8-4527-9f8e-e6772c8d8170.png) |
> fix(ckeditor): full-height edit plugin inside text

- taccsite_cms/settings.py
Make "Text" plugin instance allow inline elements outside `<p>` tags. ([Source](https://stackoverflow.com/a/24701004/11817077))
Many new CMS components for TACC should work off of HTML elements, but having them wrapped in `<p>` tags ruins the benefit of markup based styling.
- added `autoParagraph: False` to new `CKEDITOR_SETTINGS` settings entry
1. Create a Text plugin instance.
2. Be on a line that does not have a block level element yet (no `<p>`, no `<h1>`):
1. Delete any existing content.
2. Press backspace again to remove empty block-level element (e.g. `<h1>`, `<p>`).
3. Choose an inline element from the Styles dropdown e.g. "Big".
4. Save Text content.
5. Confirm rendered markup does **not** wrap the inline element with a `<p>` tag. …
> feat(settings): wysiwyg should not force <p> tags

- taccsite_cms/static/djangocms_text_ckeditor/css/cms.ckeditor.css
Table descendants (like in `ckeditor`'s Link edit window) were affected. These styles should only affect direct table child.
- fixes https://github.com/TACC/Core-CMS/pull/574
- added direct selector syntax to ckeditor CSS to limit scope of styles
1. In a Text plugin instance.
2. Create a link (using the link icon, not plugin dropdown Link).
3. Open "Advanced" tab.
4. **Verify layout is legible (no overlapping text).**
5. Create a Link (using plugin dropdown Link, not the link icon).
6. **Verify edit area fills pop up window (i.e. re-test [#574](https://github.com/TACC/Core-CMS/pull/574)).**
| Status | Screenshot |
| - | - |
| Before | <img width="762" alt="Before" src="https://user-images.githubusercontent.com/62723358/207387717-b73b5dd9-b0da-488d-8fad-1dd962e0b17e.png"> |
| After | <img …
> fix(plugins): prevent wysiwyg css side effect

- README.md
- Restore Makefile commands to Readme.
- Update Readme so dev knows `--project` arg is required for `npm run build`.
Sanity of new or returning users.
- `make build` instead of `docker-compose build`
- `make start` instead of `docker-compose up`
N/A
> docs(README): makefile usage & required --project

- docker-compose.dev.yml
- elasticsearch.yml
Set up Elasticsearch network to limit exposure of the software on the network.
- [FP-1952](https://jira.tacc.utexas.edu/browse/FP-1952)
- mimics https://github.com/TACC/Core-Portal/pull/752
- limit network to only localhost
1. Run development environment using these new settings.
2. Test that Elasticsearch still works:
1. Add a CMS page **and** confirm re-index occurs and is accurate.[^1]
2. Publish a CMS page **and** confirm re-index occurs and is accurate.[^1]
4. Delete a CMS page **and** confirm re-index occurs and is accurate.[^1]
5. Add text to a CMS page and verify page appears in a search.
[^1]: You can check container logs for a message saying that re-index has occurred. You can check http://localhost:9201/cms-dev-cms/_search to confirm search index has expected page content. …
> feat(server): fp-1952 tighter ES network settings

- taccsite_cms/settings.py
- taccsite_cms/templates/djangocms_blog/post_detail.html
- taccsite_cms/templatetags/blog_post_is_multimedia.py
Enable Media placeholder on "Multimedia"-type posts as defined by new category slug setting.
- [TUP-258](https://jira.tacc.utexas.edu/browse/TUP-258)
- added setting to define which category posts are multimedia posts
- added template tag to identify multimedia blog posts
- added more code from plugin source `post-detail.html`
- changed post template to use media placeholder if post is multimedia
0. Have working News/Blog.
1. Add/Have blog category "Multimedia".
2. Add/Have blog post in category "Multimedia".
3. Add/Have image to that blog post.
4. Load blog post.
5. Verify that blog post uses its image as main image.
6. Add setting `TACC_BLOG_CUSTOM_MEDIA_POST_CATEGORY = 'multimedia'`.
7. Load blog post.
8. Verify that blog post does not use its image as main image.
9. Verify that blog …
> feat: "multimedia" articles use media placeholder

- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.page.multimedia.css
Do not let Multimedia article main image height exceed 680px.
- fixes #572
- added `overflow-y: hidden`
0. Follow #572 to set up an article.
1. Add custom image (#582) that is taller than 680px.
2. Confirm image does not show taller than 680px (bottom will get cut off).
| avoid this | do this |
| - | - |
| ![avoid this](https://user-images.githubusercontent.com/62723358/212160724-6d4c2ee6-aae2-4310-8987-62f76fbf8fdf.png) | ![do this](https://user-images.githubusercontent.com/62723358/212160749-16a54351-c747-4d47-a053-dfa43f7c58ff.png) |
> fix(djangocms_blog): article media overflow

- taccsite_cms/settings.py
The `TACC_BLOG_CUSTOM_MEDIA_POST_CATEGORY ` setting must exist, or it cannot be exported, thus server crash.
- fixes #582
- add `TACC_BLOG_CUSTOM_MEDIA_POST_CATEGORY` setting default value
1. Confirm site does not crash (with the error in the "UI" table "before" column).
| - | - |
| ![before](https://user-images.githubusercontent.com/62723358/212163284-577d7f36-0481-43e7-a950-f3c1e978d003.png) | ![after](https://user-images.githubusercontent.com/62723358/212163775-b186a572-e237-420c-b72d-645725ecdbc3.png) |
Alternatively, add ternary logic (export if exists), but unrealistic value is simpler.
> fix: add multimedia post custom media setting

- package-lock.json
- package.json
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.page.css
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.picture.css
- taccsite_cms/static/site_cms/css/src/site.css
- taccsite_cms/templates/djangocms_picture/default/picture.html
- If picture has caption or a link, place attributes on parent tags, not image.
- Use `c-offset-content--…` to align Pictures in a blog article.
- requires https://github.com/TACC/Core-Styles/pull/121
- required by https://github.com/TACC/tup-ui/pull/122
- fix(templates): djangcms_picture, attr's on parent fc007ff
- chore(css): site.css, remove duplicate imports  6fe36a2
- feat(css): djangcms_blog, Picture alignment  592cdbc
- fix(core-styles): inutitive figure–caption layout b1b606d
- fix(css): propagate Picture plugin Bootstrap attrs 6318fe6
- fix(css): do not try to auto clear float alignment 6345d7e
1. See ALIGNMENT "Center" and "Left" on [Outlook for the Blue Economy](https://dev.tup.tacc.utexas.edu/news/latest-news/2023/01/26/outlook-for-the-blue-economy/).
1. See ALIGNMENT "Left" …
> fix(templates): djangcms_picture, alignment issues

- taccsite_cms/templates/djangocms_blog/post_list.html
For every `li a.blog-tag-...` an article has (in its metadata), add `has-blog-tag-...` class on the `<article>`.
- part of #594
- add script to `post_list.html`
1. Load News list that has articles with tags.
2. Match each `article.post-item > header > ul.tags > li > a[class*="blog-tag-"]` class to `article.post-item` classes of the pattern `.has-blog-tag-…`* i.e.
1. given a news article with tag `test`,
2. then article has metadata tag link with class `blog-tag-test`,
3. and article has class `has-blog-tag-test`*.
<sup>* The `has-` prefix is added to replicate CSS `:has()` selector, so that CSS can select via `article:has(.blog-tag-test)` (if browser supports `:has()`) and `article.has-blog-tag-test` (if browser does not support `:has()`).</sup>
> feat(djangocms_blog): article 'has-blog-tag-...' class names

- taccsite_cms/settings.py
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.item.css
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.page.css
- taccsite_cms/templates/djangocms_blog/post_detail.html
- taccsite_cms/templatetags/blog_post_is_show_abstract.py
If tag matches setting value, article page will show the abstract.
<details><summary>Use Cases</summary>
**Actual**: So that if a user navigates to a page that they were not intended to access, the abstract can be shown to show them to where they should have been redirected. (That redirection relied on abstract having a link to an external article, but relies on JavaScript which can fail. Also, user could have pieced together the URL or received it in full via RSS.)
**Imagined:** Scientific article whose abstract should be listed before the content so all content is available together.
</details>
- borrows ideas from https://github.com/TACC/Core-CMS/pull/572
- add setting `TACC_BLOG_SHOW_ABSTRACT_TAG`
- change article list `.blog-lead` styles to **only** be for list
- change article page …
> feat(settings): TACC_BLOG_SHOW_ABSTRACT_TAG

- taccsite_cms/settings.py
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.item.css
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.page.css
- taccsite_cms/templates/djangocms_blog/post_detail.html
- taccsite_cms/templates/djangocms_blog/post_list.html
- taccsite_cms/templatetags/blog_post_is_show_abstract.py
Add CMS setting, and use JavaScript to add HTML class names, to support blog articles that redirect to external website.
- includes* #593
- requires #592
- required by TACC/tup-ui#128.
<sup>* Originally though required for this, but it is not. It remains bundled because it will eventually be used to style list items differently based on tag (or category).</sup>
See #592 and #593.
> feat: support blog article redirect via cms setting & html class

- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.item.css
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.page.css
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.page.multimedia.css
- taccsite_cms/templates/djangocms_blog/base.html
- taccsite_cms/templates/djangocms_blog/includes/blog_cats.html
- taccsite_cms/templates/djangocms_blog/includes/blog_item.html
- taccsite_cms/templates/djangocms_blog/includes/blog_meta.html
- taccsite_cms/templates/djangocms_blog/includes/blog_tags.html
- taccsite_cms/templates/djangocms_blog/post_detail.html
- taccsite_cms/templates/djangocms_blog/post_list.html
Clone and edit more templates from https://github.com/nephila/djangocms-blog/blob/1.1.1/djangocms_blog/templates/djangocms_blog/, and remove JavaScript DOM manipulation.
<details>
Rather than be so afraid of updates to templates, such that I would rather use JavaScript to change the markup, assume templates rarely change, and that their API—i.e. the context variables—do not change.
</details>
- supports https://github.com/TACC/tup-ui/pull/128 later commits
See commits (which are change-specific and polished).
I tested the changes. I skipped the recording. I am sorry.
> feat(djangocms_blog): drop scripts in favor of template overwrites

- taccsite_cms/templates/djangocms_blog/post_list.html
Ensure blog listing is wrapped in a `<div class="container">` (like it was before #596).
- fixes #596
Not recorded.
> fix(_blog): post_list.html missing div.container

- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.item.css
- taccsite_cms/templates/djangocms_blog/includes/blog_meta.html
- Do not let use click whole article as link.
- Clarify whether article is actually published or to be published.
- [TUP-258](https://jira.tacc.utexas.edu/browse/TUP-258)
- [**feat**: "To be published"](https://github.com/TACC/Core-CMS/commit/9953a425a2eb5d95de1bb02d993775ebb4087fb5)
- [**feat**: do not stretch link over list article](https://github.com/TACC/Core-CMS/commit/63acc0cabf559144bab7878458d530283af289d4)
https://user-images.githubusercontent.com/62723358/218555902-44e5d9ec-f350-483b-b167-7cba60417d65.mov
> feat(djangocms_blog): simple article link & "to be published"

- Dockerfile
Fix Poetry install URL.
- [Update Dockerfile to use new Poetry install command.](https://bitbucket.org/taccaci/frontera-tech-docs/pull-requests/30/update-dockerfile-to-use-new-poetry) taccaci/frontera-tech-docs#30
- https://github.com/TACC-Cloud/geoapi/pull/115
https://jenkins01.tacc.utexas.edu/job/Core_CMS_Build/964/console
Skipped.
> fix: poetry install url

- Dockerfile
Fix Poetry install URL and version.
- mimics [Update Dockerfile to use new Poetry install command.](https://bitbucket.org/taccaci/frontera-tech-docs/pull-requests/30/update-dockerfile-to-use-new-poetry) taccaci/frontera-tech-docs#30
- mimics https://github.com/TACC-Cloud/geoapi/pull/115
- (partially) mimics https://github.com/TACC/Core-CMS/pull/558/commits/5c4a165eef926c4d57550f5df672a0fb80788f88
- performs #601 correctly
https://jenkins01.tacc.utexas.edu/job/Core_CMS_Build/965/console
Skipped.
> fix: poetry install url & version

- taccsite_cms/settings.py
- taccsite_cms/templates/header.html
- taccsite_cms/templates/nav_search.html
- taccsite_cms/templates/nav_search.raw.html
Add and use new setting `SEARCH_QUERY_PARAM_NAME` to allow [TUP CMS](https://github.com/TACC/tup-ui/tree/main/apps/tup-cms)* to use a different query parameter.
<sup>* Or any CMS that opts for Google search.</sup>
- [TUP-437](https://jira.tacc.utexas.edu/browse/TUP-437)
- required by https://github.com/TACC/tup-ui/pull/159
- required by https://github.com/TACC/tup-ui/pull/161
- added `SEARCH_QUERY_PARAM_NAME` setting — default value "query_string"
- changed templates to use `{{SEARCH_QUERY_PARAM_NAME}}` instead of `query_string`
See https://github.com/TACC/tup-ui/pull/159.
1. Make the use of ElasticSearch conditional.
> feat(settings): tup-437, SEARCH_QUERY_PARAM_NAME

- taccsite_cms/templates/djangocms_picture/default/picture.html
Render child plugins as content in a `<figcaption>`.
- required by https://github.com/TACC/tup-ui/pull/182
- **added** template logic to `djangocms_picture` default template
1. Create a "Picture / Image (Responsive)" plugin instance.
2. Make it a link.
3. Within the "Picture / …", create a "Text" plugin instance.
4. Add text.
5. Verify the markup is:
```
<a ...>
<figure ...>
<figcaption ...>
(The text you entered in Text plugin.)
</figcaption>
</figure>
</a>
```
<sup>Tested via https://github.com/TACC/tup-ui/pull/182.</sup>
> feat(djangocms_picture): child plugins as caption

- taccsite_cms/templates/djangocms_picture/default/picture.html
Render both types of captions together in a **shared** `<figure>` and `<figcaption>`.
- fixes #609 which mismanaged double captions
- **changed** template logic
1. Create a Picture / Image (Responsive) block.
2. Add a CAPTION TEXT (via "Advanced settings").
3. Save.
4. Verify Picture […] block caption text appears beneath image (via `<figcaption>` within `<figure>`).
5. Add a Text block nested as child of the Picture […] block.
6. Add text to Text block.
7. Save.
8. Verify both caption texts appear beneath image (via `<figcaption>` within `<figure>`).
9. Remove CAPTION TEXT from Picture […] block (via "Advanced settings").
10. Save.
11. Verify Text block caption text appears beneath image (via `<figcaption>` within `<figure>`).
| model field caption | both captions | child plugin caption …
> fix(djangocms_picture): child plugins as caption

- package-lock.json
- package.json
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.css
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.item.css
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.page.css
Integrate Blog/News styles from https://github.com/TACC/tup-ui.
- adds to #587
- requires https://github.com/TACC/Core-Styles/pull/144
- required by _upcoming_tup_ui_pr_
- **added** core-styles `c-tag`
- **added** category styles (that extend core-styles `c-tag`)
- **changed** to use consistent margin under metadatas
- **removed** copy-paste styles from blog abstract/lead
- **removed** copy-paste styles from blog article content
See _upcoming_tup_ui_pr_.
> Task/tup 395 cmd news styles  from tup cms

- taccsite_cms/templates/header.html
If search bar is disabled, but portal nav is enabled, ensure portal nav is right-aligned.
- Given `INCLUDES_SEARCH_BAR = True` and `INCLUDES_PORTAL_NAV = False`
- Then `.s-cms-nav` **must not** be adjacent to `.s-portal-nav`
- required by https://github.com/TACC/tup-ui/pull/199
- **changed** to use `mr-auto` on `.s-cms-nav` instead of `ml-auto` on `s-search-bar`
1. Set `INCLUDES_SEARCH_BAR = True` and `INCLUDES_PORTAL_NAV = False`.
2. Load CMS website.
3. Verfiy header bottom bar horizontal layout is:
`logo    cms nav                            portal nav`
✓ The cms nav has auto right margin.
✓ The portal (not loaded[^1], so empty, but present) is at the far right.
[^1]: Loading portal on CMS (which would render the portal nav content) is …
> fix: portal nav not to touch cms menu if no search

- package-lock.json
- package.json
The `core-styles.base.css` now defaults to blue accent color (instead of purple).
- requires https://github.com/TACC/Core-Styles/pull/149
- accompanied by https://github.com/TACC/tup-ui/pull/203
- accompanied by https://github.com/TACC/TACC-Docs/pull/9
0. Prepare to [Test CMS Changes](https://github.com/TACC/Core-CMS/wiki/Test-CMS-Changes).
1. Add/Verify `settings_local.py` setting `TACC_CORE_STYLES_VERSION = 2`.[^1]
2. Open test server e.g. https://localhost:8000.
3. Visit a page with a link, or add a link to page (via Text or Link plugin) (via breadcrumbs on nested page).
4. Verify link color is sapphire blue _not_ purple.
| `TACC_CORE_STYLES_VERSION = 2`[^1] | `TACC_CORE_STYLES_VERSION = 0` |
| - | - |
| ![cms accent color change styles …
> feat(core-styles): change accent color from purple to blue

- package-lock.json
- package.json
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.page.css
Fix mistakes in #616 (migrating [TACC CMS](https://github.com/TACC/tup-ui/tree/main/apps/tup-cms) styles to Core-CMS).
- continues #616
- requires https://github.com/TACC/Core-Styles/pull/150
- required by https://github.com/TACC/tup-ui/pull/202
- similar to https://github.com/TACC/TACC-Docs/pull/8
- **fixes** core-styles `x-figure` & `x-blockquote` mistakes via new install
1. Verify caption and blockquote and figure match design.*
<sup>\* ⚠️ No reference. Going by memory. Sorry. It was a working meeting with designers that resulted in code snippets.</sup>
| p.caption | figure | blockquote |
| - | - | - |
| ![p caption](https://user-images.githubusercontent.com/62723358/229863702-c5636f5d-b637-4b73-9dcf-3f753767da60.png) | ![figure](https://user-images.githubusercontent.com/62723358/229863 …
> feat(css): migrate tup-cms styles to core-cms (part 2)

- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.page.css
- taccsite_cms/static/site_cms/css/src/_imports/elements/figure-caption-blockquote.css
- taccsite_cms/static/site_cms/css/src/site.cms.css
Apply figure, caption, and blockquote styles to the whole site, not just news.
- required by https://github.com/TACC/tup-ui
- **changed** location and breadth of application of `x-figure(-…)` and `x-blockquote(-…)`
1. Start up a CMS using this branch.
2. If local, `npm run build:css --project="core-cms" && docker exec -it sad_cms python manage.py collectstatic --no-input`.
3. Add figure and caption and blockquote and `p.caption` to a page (not a news article).
4. Verify the styles match those of a news article.
> feat(css): figure, caption, etc styles; whole site

- taccsite_cms/templates/assets_core.html
- taccsite_cms/templates/assets_core_cms.html
- taccsite_cms/templates/assets_core_delayed.html
- taccsite_cms/templates/assets_custom.html
- taccsite_cms/templates/assets_font.html
- taccsite_cms/templates/assets_site.html
- taccsite_cms/templates/base.html
- taccsite_cms/templates/debug_js.html
- taccsite_cms/templates/guide.html
- taccsite_cms/templates/guides/getting_started.tam.html
- taccsite_cms/templates/guides/getting_started.v2.html
- taccsite_cms/templates/header_branding.html
- taccsite_cms/templates/header_logo.html
- taccsite_cms/templates/home_portal.html
- taccsite_cms/templates/nav_search.raw.html
- taccsite_cms/templates/snippets/typography-guide.html
- taccsite_cms/templates/style_guide.html
Load `static` not `staticfiles` template tag so #626 does **not** have error.
- mimics #625
- required by #626
- **changed** all templates loading `staticfiles` to load just `static`
1. Build TUP CMS off https://github.com/TACC/tup-ui/pull/225.
2. Load CMS in browser.
3. Verify no TemplateSyntaxError.
| - | - |
| ![templatesyntaxerror](https://user-images.githubusercontent.com/62723358/235548128-8f538d81-8747-474b-908a-fbe73b41a2f9.png) | … |
> chore: load static not staticfiles

- taccsite_cms/settings.py
Mimics #630, but for #626 instead of #625.
> fix: TUP-477, set X_FRAME_OPTIONS like django 2 (for TUP CMS)

- taccsite_cms/settings.py
Fix problem caused by [Django 3 protection against clickjacking](https://docs.djangoproject.com/en/3.0/ref/clickjacking/).
- [TUP-477]
[TUP-477]: https://jira.tacc.utexas.edu/browse/TUP-477
- **added** `X_FRAME_OPTIONS = 'SAMEORIGIN'`
Test [TUP-477].
Skipped.
1. Is there an option that only sets `SAMEORIGIN` where we know we need it, and otherwise defaults to `DENY`?
2. Is that option more secure? And sensible?
> fix: TUP-477, set X_FRAME_OPTIONS like django 2

- package-lock.json
- package.json
- taccsite_cms/settings.py
- taccsite_cms/static/site_cms/css/.postcssrc.yml
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.css
- taccsite_cms/static/site_cms/css/src/site.css
- taccsite_cms/static/site_cms/css/src/site.header.css
1. Replace `env()`-based themes with simpler solutions.
2. <details><summary>Remove <code>postcss-env-function</code> deprecation warning.</summary>
```
postcss-env-function is deprecated and will be removed.
We are looking for insights and anecdotes on how these features are used so that we can design the best alternative.
Please let us know if our proposal will work for you.
Visit the discussion on github for more details.
https://github.com/csstools/postcss-plugins/discussions/192
```
</details>
- requires https://github.com/TACC/Core-CMS-Resources/pull/178
- requires https://github.com/TACC/Core-Styles/pull/164
- required by https://github.com/TACC/Core-CMS/pull/605
<sup>(because it is easier to remove themes than to support them backwards-compatibly in Core-CMS v3.10)</sup>
1. …
> chore: retire env()-based themes (Core-CMS v3.9)

- taccsite_cms/contrib/taccsite_system_monitor/static/taccsite_system_monitor/css/system_monitor.css
Fix incorrect colors on System Monitor table (only used on Frontera).
- fixes https://github.com/TACC/Core-CMS/pull/568/files#diff-4257a06b5695f2afd536fd7fb983e6cfbbced1462f96ec4d10c68e49f215a7feR31
- **changed** system monitor to unset global background color
<sup>The `<th>`s were white cuz default `--global-color-background--app` is white, and it is used to color `<th>` backgrounds.</sup>
- **changed** system monitor table color to be cell color (more specific)
<sup>The `<td>` and `<th>` colors were trumped by Core Styles table CSS.</sup>
Use the new styles instead of the old styles. I believe this can reliably be tested live.
https://github.com/TACC/Core-CMS/assets/62723358/f758daed-e5cf-454f-a1db-512714f42fa3
| - | - |
| <img width="1200" alt="before" …
> fix: (frontera) system_monitor colors

- taccsite_cms/static/site_cms/css/src/site.header.css
- taccsite_cms/static/site_cms/css/src/theme.has-dark-logo.css
1. Add default theme variables to `site.header.css`.
2. Add "has dark logo" theme variables to new `theme.has-dark-logo.css`.
- fixes #632
<sup>After which Portal would not render header colors, so legibility was broken.</sup>
- supports https://github.com/TACC/Core-Portal/pull/799
- **added** theme vars to `site.header.css`
- **added** `has-dark-logo` theme stylesheet
1. On a site running this branch, verify `/static/site_cms/css/build/theme.has-dark-logo.css` loads theme variables.
2. On Portal dashboard, verify header is black with white text.
3. Deploy both [#634] and to ProTX local or pre-prod site.
4. Add to [ProTX](https://pprd.protx.tacc.utexas.edu/) **Portal** `settings_local.py`:
```py
PORTAL_CSS_FILENAMES = [
'/static/site_cms/css/build/theme.has-dark-logo.css'
]
```
5. On …
> fix(css): add missing theme vars

- docker-compose.example-cms.yml
Port a security fix to the example docker compose files.
- mimics #579
- **add** host IP for port set in docker compose
Skipped. Should be a noop change. Please correct me if I am mistaken.
> bugfix: security for example-cms docker compose

- taccsite_cms/templates/home_portal.html
Increase the `<h2>` and `<h3>` on `home_portal.html` to `<h1>` and `<h2>`.
- follow-up to #549
1. Compare heading levels before this branch and after.
| before, _automatic_ | expectation, _manual_ | after, _automatic_ |
| - | - | - |
| ![cep auto home before hN bump](https://github.com/TACC/Core-CMS/assets/62723358/7ef435c6-a438-4648-8283-7029a0c68b54) | ![cep manual home expectation](https://github.com/TACC/Core-CMS/assets/62723358/7dbd5533-53f4-447f-9fe5-9b036560f05a) | ![cep auto home after hN bump](https://github.com/TACC/Core-CMS/assets/62723358/139a3f1d-66d4-4b5a-9770-c5e183d0e103) |
> fix(templates): bump home_portal <hN> levels

- CHANGELOG.md
Add changes to `main` that only got into Core-CMS v3.8.2.
- fixes #556
- includes #570
- required by https://github.com/TACC/Core-CMS-Resources/pull/179
> fix(brainmap-cms): #556 missing items from #570

- taccsite_cms/static/site_cms/js/modules/setTargetForExternalLinks.js
Make `pathsToExternalSite` take precedent when auto-adding `target="_blank"`.
- [DES-2498](https://jira.tacc.utexas.edu/browse/DES-2498)
- changed boolean logic to give precedence to `hasExternalRedirect`
1. Load raw updated code into a `<script>` in a snippet.
<sup>I tested on [DesignSafe](https://www.designsafe-ci.org/) via snippet [#9](https://www.designsafe-ci.org/admin/djangocms_snippet/snippet/9/change/).</sup>
2. Add `window.DEBUG = true;` in a second `<script>` **before** the first.
3. Save snippet.
4. Refresh page.
5. Verify console logs debug info form the script.
6. Verify any `pathsToExernalSite` are given `target="_blank"`.
<details><summary>Sample Code</summary>
```html
<script type="module">
window.DEBUG = true;
</script>
<script type="module">
/* PASTE UPDATED SCRIPT CODE …
```
> fix(js): DES-2498 auto new window ignores redirect

- taccsite_cms/static/site_cms/js/modules/setTargetForExternalLinks.js
Updates to JavaScript that opens link in a new tab:
- **add** pattern matching (Regex)
- **add** callback
- **deprecate** misspelled option for paths
- **add** better-named option for paths
- [DES-2496](https://jira.tacc.utexas.edu/browse/DES-2496)
- adds to recent #649
- **deprecated** `pathsToExernalSite` option
- **added** `pathsToForceSetTarget` option
- **added** `setTargetCallback` option
- **change** script to prefer `pathsToForceSetTarget`
- **change** script variables to reflect "force set target" context
<sup>This more clearly describes what user is doing, and suggests they can define the `target` value.</sup>
- **add** RegEx matching for paths
1. Load raw updated code into a `<script>` in a snippet.
<sup>I tested via [DesignSafe](https://www.designsafe-ci.org/) via snippet …
> feat(js): DES-2496 auto new tab, regex + callbacks

- package-lock.json
- package.json
- taccsite_cms/settings.py
- taccsite_cms/static/site_cms/css/src/_imports/components/lightgallery.css
- taccsite_cms/static/site_cms/css/src/core-cms.css
Style an image grid.
- styles #654
- requires https://github.com/TACC/Core-Styles/pull/169
- **changes** `package.json` to load core-styles to v2.9.0
- **adds** and loads `…/components/lightgallery.css`
1. Using CMS, create a gallery with container different size images wrapped in links.
2. Set container class to `lightgallery`.
3. Verify styles **now** match https://github.com/TACC/Core-Styles/pull/169.
4. Set container class to `s-image-grid`.
5. Verify styles **still** match https://github.com/TACC/Core-Styles/pull/169.
| `lightgallery` | `s-image-grid` | no class |
| - | - | - |
| ![s-image-grid](https://github.com/TACC/Core-CMS/assets/62723358/84636391-68f4-4ff2-b700-a8442e212632) | ![lightgallery](https://github.com/TACC/Core-CMS/assets/62723358/d52d68be-1675-44e5-bad4-e30cadcead88) …
> feat: styles v2.9.0 → s-image-grid → lightgallery

- taccsite_cms/static/site_cms/css/src/_imports/components/lightgallery.css
- taccsite_cms/static/site_cms/css/src/core-cms.css
Style an image grid.
- styles #654
- mimics #655
- requires https://github.com/TACC/Core-Styles/pull/169
- **adds** and loads `…/components/lightgallery.css`
1. Using CMS, create a gallery with container different size images wrapped in links.
2. Set container class to `lightgallery`.
3. Verify styles **now** match https://github.com/TACC/Core-Styles/pull/169.
4. Set container class to `s-image-grid`.
5. Verify styles **still** match https://github.com/TACC/Core-Styles/pull/169.
| `lightgallery` | `s-image-grid` | no class |
| - | - | - |
| ![s-image-grid](https://github.com/TACC/Core-CMS/assets/62723358/84636391-68f4-4ff2-b700-a8442e212632) | ![lightgallery](https://github.com/TACC/Core-CMS/assets/62723358/d52d68be-1675-44e5-bad4-e30cadcead88) | …
> feat: s-image-grid → lightgallery

- CHANGELOG.md
- package-lock.json
- package.json
> feat: v3.11.3

- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.picture.css
Make anchor that wraps image have excepted block behavior without losing inherit inline behavior.
- supports https://github.com/TACC/Core-Styles/pull/5
- **added** rule to use `inline-block` layout for `a.img-fluid`
See result of the style applied to https://www.tacc.utexas.edu/research/scivis-gallery/ via [TACC/tup-ui `visualization-gallery-styles`](https://github.com/TACC/tup-ui/blob/23dbed3/apps/tup-cms/src/taccsite_cms/templates/snippets/visualization-gallery-styles.html). If style is removed (via editing live markup), markup has no effect.
> fix(css): anchor around image not supporting margin

- package-lock.json
- package.json
Bump from https://github.com/TACC/Core-Styles/releases/v2.9.1 to https://github.com/TACC/Core-Styles/releases/v2.11.0.
- supports https://github.com/TACC/tup-ui/pull/218
None.
> feat: core-styles v2.9.1 to v2.11.0

- taccsite_cms/templates/djangocms_blog/post_detail.html
- taccsite_cms/templates/djangocms_blog/post_list.html
Fix UI bugs in Blog/News.
- fixes #581
- specifically [v3.12.0-alpha.1: Django 3; Redesign Blog/News + Related Patterns](https://github.com/TACC/Core-CMS/releases/tag/v3.12.0-alpha.1)
- **changes** blog templates to only use different `<hN>` if core styles v2+ is loaded
0. Have a site that has `TACC_CORE_STYLES_VERSION` not set (or set below 2).
1. Verify [a news article](https://pprd.ecep.tacc.utexas.edu/news/2023/05/18/highlights-2023-ecep-summit-oakland-california/) title uses `<h2>` on ECEP site.
2. Verify [the news listing](https://pprd.ecep.tacc.utexas.edu/news/) "News" title uses `<h2>` on ECEP site.
https://pprd.ecep.tacc.utexas.edu/news/2023/05/18/highlights-2023-ecep-summit-oakland-california/
vs.
https://ecepalliance.org/news/2023/05/18/highlights-2023-ecep-summit-oakland-califo …
> fix(dev/tup-cms): blog/news markup (bugs found on ecep)

- CHANGELOG.md
- Makefile
- docs/contributing.md
- package-lock.json
- package.json
<del>Prepare v3.12.0 release.</del>
<ins>Prepare v3.12.0-alpha.10 pre-release.</ins>
> **Warning**
> All projects that have attempted to serve this version return a 500 error.
> Problem uncertain. Solution unknown.
<details>
I had hoped this would be v3.12.0, because I thought v3.12.0-alpha.**?** deployed well on https://pprd.ecep.tacc.utexas.edu, but this branch does not deploy well now, and I can't confirm what commit had.
The following websites are _still_ **down** because of trying to deploy this CMS image:
- https://pprd.ecep.tacc.utexas.edu\
<sup>(deployed via https://github.com/TACC/Core-CMS-Custom and https://github.com/TACC/Core-CMS-Resources)</sup>
Revert of the deploy **still** serves 500.
- https://dev.fronteraweb.tacc.utexas.edu\
<sup>(deployed via …
> feat: v3.12.0-alpha.10

- taccsite_cms/settings.py
Fix server crash since https://github.com/TACC/Core-CMS/releases/tag/v3.12.0-alpha.10.
- fixes #675
- requires https://github.com/TACC/Core-CMS-Resources/pull/186
- **changed** taccsite_custom directory scan to ignore `docs/`
- **added** `frontera-cms` template redirects
1. Build CMS image.
2. Deploy CMS image.
3. Access website.
4. Check whether site loads or crashes.
Just visit website ツ.
The fixes alone seem **not** adequate for a CMS at v3.12 **and** on https://github.com/TACC/Core-CMS-Custom. Example: 
- https://github.com/TACC/Core-CMS-Custom/pull/175 — 2023-07-25
> fix: v3.12.0-alpha.10 crash (ignore docs, add redirects)

- taccsite_cms/static/site_cms/css/src/_migrations/v3-10_v3-11/README.md
Add paper trail for users searching for `v3-10_v3-11` usage.
None.
- **added** `…/v3-10_v3-11/README.md`
See [readme file preview on this branch](https://github.com/TACC/Core-CMS/blob/docs/v3.11.4-paper-trail-for-v3-10-migration/taccsite_cms/static/site_cms/css/src/_migrations/v3-10_v3-11/README.md).
> docs: paper trail for v3-10_v3-11/

- taccsite_cms/static/site_cms/css/src/_migrations/v3-10_v3-11/README.md
Add paper trail for users searching for `v3-10_v3-11` usage.
- mirrors #681
- **added** `…/v3-10_v3-11/README.md`
See [readme file preview on this branch](https://github.com/TACC/Core-CMS/blob/docs/paper-trail-for-v3-10-migration/taccsite_cms/static/site_cms/css/src/_migrations/v3-10_v3-11/README.md).
> docs: paper trail for v3-10_v3-11/ (off of main)

- taccsite_cms/static/site_cms/css/src/_migrations/v3-10_v3-11/site.v3-11-plus.css
- taccsite_cms/templates/assets_site.html
Support responsive embed of a podcast (or any audio or video).
- Texascale 2023
- mimics #684
- **added** `site.v3-11-plus.css`
<sup>to load existing `…/django-cms-video.css`</sup>
- **added** link to `site.v3-11-plus.css`
<sup>in `taccsite_cms/templates/assets_site.html`</sup>
1. Create/Open a test page.
<sup>If deployed to Texascale, you may use https://prod.texascale.tacc.utexas.edu/testing/wes-test/?edit.</sup>
2. Add a "Video player" plugin instance.
| Field | Value |
| - | - |
| TEMPLATE: | Responsive Automatic |
| LABEL: | Podcast |
| EMBED LINK: | `https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1242255460` |
3. Save plugin instance.
4. Verify podcast:
- renders
- stretches to fit available horizontal space
- is not cut off
- is functional
Relying on #684.
> fix: render/style responsive video/audio player (off of main)

- taccsite_cms/settings.py
Do not serve UI Pattern Library unless its directory exists.
<sup>Because https://github.com/TACC/Core-CMS-Custom apps typically do not sync UI demo.[^1]</sup>
Core-CMS Build: https://jenkins01.tacc.utexas.edu/job/Core_CMS_Build/1212
Core-CMS-Custom Build: …
Deploy: …
- fixes https://github.com/TACC/Core-CMS-Custom/pull/175
- fixes https://github.com/TACC/Core-CMS/releases/tag/v3.12.0-alpha.11 for https://github.com/TACC/Core-CMS-Custom
- **changes** `settings.py` to not serve `/static/ui` unless `taccsite_ui` exists
https://github.com/TACC/Core-CMS-Custom/pull/175
[^1]: https://github.com/TACC/Core-CMS-Custom will probably not serve UI demo until that demo can auto-import their custom stylesheet.
> fix: do not serve ui demo unless it exists

- taccsite_cms/settings.py
Serve the UI patternd emo if it exists.
- fixes bug caused by #688
- **fixed** outdated variable name
- **fixed** bad assignment operator
- **fixed** missing comma
1. Load.
2. Collect static.
3. Visit http://0.0.0.0:8000/static/ui/index.html.
> fix: serve ui demo if it exists

- taccsite_cms/settings.py
Sets `SESSION_COOKIE_SECURE = True` to resolve a flag set by an ISO security audit.
- mimics #695
1. In the chrome devtools, go to Application -> Cookies -> and ensure that the "Secure" column for the "sessionid" cookie is checked. See screenshot below
> hotfix: set SESSION_COOKIE_SECURE = True (off of v3.11.5)

- taccsite_cms/settings.py
Sets `SESSION_COOKIE_SECURE = True` to resolve a flag set by an ISO security audit.
- mimics #695
1. In the chrome devtools, go to Application -> Cookies -> and ensure that the "Secure" column for the "sessionid" cookie is checked. See screenshot below
> hotfix: set SESSION_COOKIE_SECURE = True (off of v3.9.5) 

- Dockerfile
- docs/develop-project.md
- package.json
- taccsite_cms/settings.py
- taccsite_cms/templates/assets_site.html
- taccsite_ui/fractal.config.js
For UI Demo:
- fix it to work on CEP and TUP
<sup>Because #692 did not seem to fix it on TUP.</sup>
- remove project-specific config
<sup>Because it wasn't working and was convoluted.</sup>
- rename to `ui-demo`
<sup>It had been `css-demo`, but it could demo JavaScript.</sup>
- document better
- fixes #692
- required by https://github.com/TACC/tup-ui/pull/308
1. Build and deploy on https://dev.cep.tacc.utexas.edu/.
2. Build and deploy on https://dev.tup.tacc.utexas.edu/.
> **Important**
> Be careful not to overwrite what else may be being tested in dev.
| dev.cep | dev.tup |
| - | - |
| ![dev cep](https://github.com/TACC/Core-CMS/assets/62723358/1e420fc6-3b74-4ebf-97d3-fdae5951aa12) | ![dev tup](https://github.com/TACC/Core-CMS/assets/62723358/347da5a6-4a19-4fa0-b361-9f91ed54458a) |
> fix: ui demo for core and clients

- taccsite_cms/settings.py
- taccsite_cms/static/site_cms/css/src/_imports/settings/font.css
Updated Texascale for CMS v3.12, and renamed it to `texascale_cms`.
- requires https://github.com/TACC/Core-CMS-Resources/pull/190
- done so Texascale can have #711
- **changed** `INSTALLED_APPS` to ignore `texascale-org` dir
- **changed** name of `texascale-org` to `texascale_cms`
> feat: texascale, cms v3.12.0 beta

- taccsite_cms/settings.py
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.css
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.page.css
- taccsite_cms/templates/djangocms_blog/post_detail.html
- taccsite_cms/templates/share_on_social.html
Add quick links to share a News article on social media.
- [TUP-87](https://jira.tacc.utexas.edu/browse/TUP-87)
- expected by #713
- **added** share links to news article
- **added** re-usable template for share links
- **added** setting `TACC_SOCIAL_SHARE_PLATFORMS` to list platforms
1. [Install blog.](https://github.com/TACC/Core-CMS/wiki/How-to-Install-DjangoCMS-Blog-i.e.-News)
2. [Create an article.](https://confluence.tacc.utexas.edu/pages/viewpage.action?pageId=182911007#UserGuideBlog/NewsInstructions-FromanEmptyCMS)
3. Open the article your created.
4. Verify social media share links show as icons.
5. Live-edit the markup: In each share link URL, replace `http://localhost:8000` with `https://www.tacc.utexas.edu`.
6. Click each, and verify it lets user share via the appropriate …
> feat: social media quick share links

- taccsite_cms/management/commands/group_perms/news_writer_advanced.py
- taccsite_cms/management/commands/group_perms/news_writer_basic.py
This reverts commit 5d1c585.
I thought I was preventing the addition of "Image" plugin (i.e. `djangocms-picture`), but I prevented addition of image files.
> Revert "feat: do not let news editors add plain images (#691)"

- docs/develop-project.md
- docs/styles-and-scripts.md
How I _currently_ manage scripts and styles, **but** not necessarily how I _should_.
- any future work by unfamiliar developers
- **added** document about adding scripts and styles
N/A
Read https://github.com/TACC/Core-CMS/blob/docs/styles-and-scripts/docs/styles-and-scripts.md.
> docs: manage scripts and styles

- docs/styles-and-scripts.md
Using `django` after backticks broke github-pages action (see https://github.com/TACC/Core-CMS/commit/bc92246), so use `html` for now.
- fixes #717
Skipped.
> hotfix: docs django syntax to html

- taccsite_cms/static/site_cms/css/src/_imports/components/c-button.css
- taccsite_cms/static/site_cms/css/src/core-cms.css
Migrate button styles from TUP-CMS.
- [FP-463](https://jira.tacc.utexas.edu/browse/FP-463)
- https://github.com/TACC/tup-ui/pull/343
- **changed** c-button to load after django-cms-forms (see 3256a83 for explanation)
- **changed** styles to c-button
1. Create a page.
2. Add a button.
3. Test that the button style matches buttons on TACC CMS.
| <ins>before</ins> bug fix<br /><ins>before</ins> button change | <ins>before</ins> bug fix<br /><ins>after</ins> button change | <ins>after</ins> bug fix<br /><ins>after</ins> button change |
| - | - | - |
| ![before bug fix, before button change](https://github.com/TACC/Core-CMS/assets/62723358/19793983-1d24-4876-9035-abef5d7f2480) | ![after bug fix, before button change](https://github.com/TACC/Core-CMS/assets/62723358/123f7ac9-5b9e-4508-86ec-66f5c …
> feat: tup-616 c-button migration

- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.picture.css
Migrated django.cms.picture.css to core-cms
- [TUP-632](https://jira.tacc.utexas.edu/browse/TUP-632)
- Migrate from [django.cms.picture.css](https://github.com/TACC/tup-ui/blob/main/apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-cms/components/django.cms.picture.css)
- CSS includes centering images
1. Zoom out and make sure image is centered. You can tick off the img.align-center class and see that the images will move to the left of the screen. Also, make sure it is importing from core-cms.css
| Before | 
| --- |
| <img width="2553" alt="Screenshot 2023-10-23 at 1 52 16 PM" src="https://github.com/TACC/Core-CMS/assets/63771558/d240965a-0101-4690-89ff-c592896e0319"> | 
| Without | 
| --- |
| <img width="2557" alt="Screenshot 2023-10-23 at 1 52 42 PM" …
> Feat/tup-632: django.cms.picture.css to core-cms

- taccsite_cms/static/site_cms/css/src/_imports/components/c-button.css
All `c-button` font-weight bold to CMS.
- [TUP-639](https://jira.tacc.utexas.edu/browse/TUP-639)
- inspired by https://github.com/TACC/Core-Styles/pull/251#discussion_r1380667528
- requires https://github.com/TACC/Core-Styles/pull/253
- required by https://github.com/TACC/tup-ui/pull/364
- **changed** c-button font-weight to always be bold
- **changed** c-button styles to use custom selector
See https://github.com/TACC/tup-ui/pull/364.
> fix: tup-639 move c-button font-weight bold to cms

- taccsite_cms/static/site_cms/css/src/_imports/components/lightgallery.css
Migrated lightgallery to core-cms.
- [TUP-633](https://jira.tacc.utexas.edu/browse/TUP-633)
- Migrate from [lightgallery](https://github.com/TACC/tup-ui/blob/main/apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-cms/components/lightgallery.css)
Spoke with H. P. and TACC is moving away from purple to blue.
**Current site has:** 
CSS: color: `var(--global-color-link-on-dark--normal) !important;`
Var: `--global-color-link-on-dark--normal: var(global-color-accent--light);`
Color: `--global-color-accent--light: #a387ed;`
**Should be:** 
CSS: color: `var(--global-color-link-on-dark--normal) !important;`
Var: `--global-color-link-on-dark--normal: var(global-color-accent--light);`
Color: `--global-color-accent--light: #86aeff;`
- Check CSS is coming from Core-CMS
- Check color …
> feat/tup-633: Migrate lightgallery to core-cms

- taccsite_cms/static/site_cms/css/src/_imports/generics/pseudo-elements.css
- taccsite_cms/static/site_cms/css/src/core-cms.css
Migrate pseudo-elements to core-cms.
- [TUP-634](https://jira.tacc.utexas.edu/browse/TUP-634)
- Migrate from [pseudo-elements](https://github.com/TACC/tup-ui/blob/main/apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-cms/generics/pseudo-elements.css)
- Added folder for generics
- Added pseudo-element to generic folder
Use the target pseudo-element on a div to see the interaction
> feat/tup-634: Migrate pseudo-elements to core-cms

- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.css
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.item.css
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.page.css
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.selectors.css
- **moved** blog app css custom selectors to their own file and imported as used
- **changed** blog app css custom selectors to use themselves
- benefits [CMD-55](https://jira.tacc.utexas.edu/browse/CMD-55)
1. `npm run build:css --project="core-cms"`
2. copy `/taccsite_cms/static/site_cms/css/build/app.blog.css` content to same stylesheet on running site
- news page
- article page
3. verify no difference
Skipped.
> chore: isolate & improve blog css custom selectors

- Dockerfile
Update the Dockerfile to remove Node deprecation warnings in CI and streamline Python dependency installation
- [WI-63](https://jira.tacc.utexas.edu/browse/WI-63)
- Use a separate Node build step to handle style building
- Update Poetry config to use the container's system Python
- expose the Poetry binary when Core-CMS is used as a base image.
> Update dockerfile to speed up builds

- package.json
Prevent warning about Node engine requirement vs current.
```
Step 20/27 : RUN npm ci
---> Running in 9ad2a2efac6c
[91mnpm[0m[91m WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@tacc/core-cms@4.1.0',
npm WARN EBADENGINE   required: { node: '^16.14.0', npm: '^8.3.0' },
npm WARN EBADENGINE   current: { node: 'v18.18.2', npm: '9.8.1' }
npm WARN EBADENGINE }
[91mnpm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
```
None.
- **changed** engine specificity
1. Build.
2. Verify no "Unsupported engine" warning.
```
Step 20/27 : RUN npm ci
---> Running in 42e651060693
[91mnpm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
```
> fix: node engine requriement more flexible

- Dockerfile
- Makefile
Allow the UI demo to be optional in a full build.
- [WI-76](https://jira.tacc.utexas.edu/browse/WI-76)
- **added** `NEEDS_DEMO` variable to Makefile and passed it to Docker build command
- **changed** Dockerfile to run different commands depending on value of `NEEDS_DEMO`
1. Build with no UI demo.
1. Verify UI demo does **not** build.
<details>
You should **not** see this:
```
> @tacc/core-cms@4.1.0 build:ui-demo
> cd taccsite_ui && fractal build
+ Included Core-CMS stylesheets
/assets/core-styles.cms.css
/../../static/site_cms/css/build/core-cms.css
✔ Build started...
⚑ Exported 1 of 552 items
[2K[1A[2K[G⚑ Exported 2 of 552 items
...
```
</details>
1. Build with a UI demo.
1. Verify UI demo **does** build.
<details>
You should see this:
```
> @tacc/core-cms@4.1.0 build:ui-demo
> cd …
```
> feat: wi-76 make UI demo optional

- taccsite_cms/settings_custom.example.py
Setting paths `example-cms` should be `example_cms`.
<details><summary>Background</summary>
Migration Django 4 → Core-CMS 3.12 replaced Python names' "-" with "_".
The incorrect path makes Core-CMS-Resources example assets fail to load.
</details>
None.
- **change** example customs settings asset paths from `example_cms` to `example_cms`
1. Load app using `settings.custom.py` with **`example-cms`** asset paths (`v4.1.0` tag).
2. Open CMS website.
3. Verify logos do **not** load.
4. Load app using `settings.custom.py` with **`example_cms`** asset paths (this branch).
5. Refresh CMS website.
6. Verify logos **do** load.
| - | - |
| ![before](https://github.com/TACC/Core-CMS/assets/62723358/e39e9724-3150-4cbe-87d1-81ef136f63a7) | …
> hotfix: setting paths `example-cms` should be `example_cms`

- taccsite_cms/settings_custom.example.py
[Creating new post via `example_cms` causes error because of missing `urls.py` tweak.](https://github.com/nephila/djangocms-blog/issues/81#issuecomment-1819497693)
- coupled to https://github.com/TACC/Core-CMS-Resources/pull/195
- **added** import of `example_cms`'s new `urls.py` to example settings
Skipped. Familiar mistake. Easy fix.
> hotfix(example_cms): missing urls.py

- package-lock.json
- package.json
- taccsite_cms/static/site_cms/css/src/_imports/components/c-button.css
Fix miscellaneous bugs in #742.
- fixes #742
- coupled with https://github.com/TACC/tup-ui/pull/384
- Django CMS form button is uppercase.
- TACC footer buttons match production (or look better).
| test | screenshot |
| - | - |
| form button | ![form button](https://github.com/TACC/Core-CMS/assets/62723358/cafb2071-a993-405e-911f-713b801b9e78) |
| footer buttons | ![before](https://github.com/TACC/tup-ui/assets/62723358/0f769433-7c71-4ff8-8b7c-82a3f93a9f22) / ![after](https://github.com/TACC/tup-ui/assets/62723358/4ee78494-3891-4127-8c4e-0df41a2cbd22)
> feat: update core-styles from v2.11 to v2.22 - misc bugs

- README.md
- docs/develop-custom-project.md
- docs/develop-project.md
1. Update docs since #741 altered local development.
2. Minor improvements to docs.
- caused by #741
- coupled to https://github.com/TACC/Core-CMS-Resources/pull/196
I author from recent memory of repeat actions done often during development and testing.
N/A
> docs: update docs since TACC/Core-CMS#741

- taccsite_cms/templates/cms_menu.html
Adds role='button' to a-tags in dropdown.
[TUP-573](https://jira.tacc.utexas.edu/browse/TUP-573)
Adds role='button' to a-tags in dropdown.
1. Follow https://github.com/TACC/Core-CMS/wiki/Locally-Develop-CMS-and-TUP-CMS to test changes in this on tup-ui
2. Check for a-tag roles on dropdowns (role='button')
> Sub-Task/TUP-573 Add accessibility role(button) to dropdown a-tags

- taccsite_cms/templates/cms_menu.html
Added `id="navbarDropdown` to `a` tag. Unsure if any styles should be associated with id tag. Couldn't find any previous uses of this, other than `aria-labelledby="navbarDropdown"` in the dropdown-menu underneath it.
- [TUP-579](https://jira.tacc.utexas.edu/browse/TUP-579)
Added `id="navbarDropdown` to `a` tag. 
1. Create image with this change
2. Test on TUP-UI for id attribute
| id applied |
| - |
| <img width="2560" alt="Screenshot 2023-12-04 at 1 00 35 PM" src="https://github.com/TACC/Core-CMS/assets/63771558/00f72306-8c9c-4c49-99da-4d330d5975e5"> |
> sub-task/tup-579 Added navbarDropdown id to a tag

- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.page.css
The left- and right-aligned images were missing the margin-bottom that a center-aligned image had.
_@wesleyboar found no reason for this._
- requires TACC/Core-Styles/pull/278
- **removed** unset of margin-bottom
0. Have a CMS with Blog/News.
1. Load a blog article with left-aligned, center-aligned, and right-aligned image.
| left | center | right |
| - | - | - |
| ![left](https://github.com/TACC/Core-CMS/assets/62723358/23f24094-a3ec-4a2f-891e-804d67c06d06) | ![center](https://github.com/TACC/Core-CMS/assets/62723358/610a50ea-be4e-4b34-9807-95b350b5df43) | ![right](https://github.com/TACC/Core-CMS/assets/62723358/4a9cafa8-e27c-46fc-a888-93a62fdb569b) |
> hotfix: restore margin-bottom for narrow-screen blog images

- taccsite_cms/templates/cms_menu.html
Use unique IDs for nav dropdowns.
- [TUP-662](https://tacc-main.atlassian.net/browse/TUP-662)
- **changed** link `id` and menu `aria-labelledby` values
- **added** menu `id`
- **added** link `aria-controls`
> [!NOTE]
> You may test on https://dev.tup.tacc.utexas.edu/.
1. Have a CMS with nav dropdowns in CMS navigation menu.
2. Verify values of dropdown's link `id` and menu `aria-labelledby`:
- are unique
- match per dropdown
3. Verify values of dropdown's menu `id` and link `aria-controls`:
- are unique
- match per dropdown
4. Verify Accessibility details are accurate.
I followed [MDN: Accessibility: "menu_role"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menu_role), except I did not use `aria-label`, because **(A)** there are already `<span class="sr-only">` …
> fix: tup 662 nav dropdown id not unique

- taccsite_cms/templates/cms_menu.html
Various accessibility fixes.
- [TUP-595](https://tacc-main.atlassian.net/browse/TUP-595)
- should be included in https://github.com/TACC/tup-ui/pull/394
- #758 
- #757
- #762
> fix: tup 595 accessibility

- taccsite_cms/settings.py
- taccsite_cms/templates/djangocms_blog/includes/blog_meta.html
Removes published verbiage when not editing.
- [TUP-551](https://tacc-main.atlassian.net/browse/TUP-551)
- https://github.com/TACC/tup-ui/pull/395
Simple. When not editing, the published verbiage is hidden. When editing the published verbiage appears.
1. On Core-CMS, adjust the `TACC_BLOG_SHOW_PUB_TEXT` value in the `settings.py` file
2. Test that it disappears when false, and appears when true
| editing (`TACC_BLOG_SHOW_PUB_TEXT = True`) |
| - |
| <img width="599" alt="Screenshot 2023-12-13 at 3 49 51 PM" src="https://github.com/TACC/Core-CMS/assets/63771558/c4d2f030-ba23-4080-8043-48dff7045eb1"> |
| not editing (`TACC_BLOG_SHOW_PUB_TEXT = False`) |
| - |
| <img width="770" alt="Screenshot 2023-12-13 at 3 50 16 PM" src="https://github.com/TACC/Core-CMS/assets/63771558/3bb8cd7d-4493-4f77-b …
> task/tup551 Hide published text unless editing

- taccsite_cms/settings.py
- taccsite_cms/templates/djangocms_blog/includes/blog_meta.html
Reverts TACC/Core-CMS#763
_After chatting and thing since https://github.com/TACC/tup-ui/pull/395, this has proven to be an unnecessary setting. There is an easier solution: delete the "Published" text (that I had added long ago, as custom text)._
> Revert "task/tup551 Hide published text unless editing"

- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.css
Remove excess whitespace under social media icons.
- replaces #768
- **added** CSS to remove whitespace
1. Verify size of social media icon links is the size of the social media icons.
| `<a>` | `<svg>` |
| - | - |
| ![a](https://github.com/TACC/Core-CMS/assets/62723358/dce0cbea-5a50-48ac-8d68-1563cdb989c6) | ![svg](https://github.com/TACC/Core-CMS/assets/62723358/688059e0-a3f9-4586-a43f-85db84bcaae7) |
> fix: social media icons excess whitespace

- taccsite_cms/locale/en/LC_MESSAGES/django.po
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.css
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.item.css
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.page.css
- taccsite_cms/templates/djangocms_blog/includes/blog_meta.html
Redesign the date for news articles.
- [TUP-568](https://tacc-main.atlassian.net/browse/TUP-568)
- **changed** date style on article page
- **changed** byline and date layout
- **changed** byline and dates markup — moved dates to their own list
1. Open News article and News list.
2. Verify that the date on both pages:
- has the same style
3. Verify that the byline on **list** page:
- (unchanged) is left-aligned underneath category
4. Verify that the byline on **article** page:
- (new location) is left-aligned to the right of category
| list page | article page |
| - | - |
| ![list](https://github.com/TACC/Core-CMS/assets/62723358/7e39ac4b-8cea-4315-81f4-e2fbe9f89212) | ![page](https://github.com/TACC/Core-CMS/assets/62723358/7bb5a371-798a-4c00-ab5b-e3dc85313f42) |
| list page - grid | …
> feat: TUP-568 redesign news article date

- .gitmodules
- README.md
- docs/develop-custom-project.md
- docs/develop-project.md
- package-lock.json
- package.json
- taccsite_cms/django/contrib/staticfiles_custom/apps.py
- taccsite_cms/settings.py
- taccsite_cms/static/djangocms_text_ckeditor/ckeditor/contents.css
Edit CSS so that Django and Vite do not use it unexpectedly.
> [!WARNING]
> This change causes errors collecting them as static files, so all `collectstatic` commands have had `--ignore` param added to avoid the error. This is intended to be a **temporary** workaround.
- [TUP-677](https://tacc-main.atlassian.net/browse/TUP-677)
<details><summary>Pull Requests</summary>
- https://github.com/TACC/tup-ui/pull/400 requires:
- https://github.com/TACC/Core-Styles/pull/285
- https://github.com/TACC/Core-CMS/pull/778 requires:
- https://github.com/TACC/Core-CMS-Resources/pull/197
- https://github.com/TACC/Core-Styles/pull/285
</details>
- **refactored** comments that suggest to `@import` code
- **refactored** absolute `/static` paths to be relative
- **changed** core-styles version
- **added** …
> chore: tup-677 css/django/vite interoperability

- .gitmodules
- README.md
- docs/develop-custom-project.md
- docs/develop-project.md
- package-lock.json
- package.json
- taccsite_cms/django/contrib/staticfiles_custom/apps.py
- taccsite_cms/settings.py
- taccsite_cms/static/djangocms_text_ckeditor/ckeditor/contents.css
This reverts commit 8610b2c558e504887d24d63c8e9e89daa15766b8.
The Core-CMS and Core-CMS-Resources `tup-677 css/django/vite interoperability` branches are not ready to be merged. The Core-CMS-Resources changes break deploy of Frontera (and probably all CMS's).
> Revert "chore: tup-677 css/django/vite interoperability (#778)"

- package-lock.json
- package.json
Update Core-Styles to remove padding from a `c-button--as-link` on CMS.
- caused by #782
- requires https://github.com/TACC/Core-Styles/pull/298
- **changed** core-styles version
0. Install [TACC/Core-Styles#298](https://github.com/TACC/Core-Styles/pull/298) into a CMS.
1. Create/Edit a page.
2. Add Text plugin instance with Source code for three types of buttons:
```html
<p><button class="c-button c-button--primary">Button</button></p>
<p><button class="c-button c-button--as-link">Button as a Link</button></p>
<p><a class="c-button c-button--primary" href="#">Link as a Button</a></p>
```
3. Verify "Button" looks like [a primary button](https://tacc.utexas.edu/static/ui/components/detail/c-button--primary.html) using a `<button>`.
4. Verify "Button as a Link" looks like [a link using a …
> fix: CMS c-button--as-link has button padding

- taccsite_cms/settings.py
- taccsite_cms/templates/assets_custom.html
- taccsite_cms/templates/header_logo.html
Change prefixes on renamed settings.
| - | - |
| `TACC_FAVICON`</br>`TACC_LOGO` | `PORTAL_FAVICON`</br>`PORTAL_LOGO` |
- [TV3-181](https://tacc-main.atlassian.net/browse/TV3-181)
- [CMD-79](https://tacc-main.atlassian.net/browse/CMD-79)
- changes prefix from https://github.com/TACC/Core-CMS/pull/783/
0. [x] [Build new CMS image.](https://jenkins01.tacc.utexas.edu/job/Core_CMS_Build/1373)
1. [x] [Update Core-Portal-Deployments to use new prefix for PTDataX.](https://github.com/TACC/Core-Portal-Deployments/commit/a744485)
2. [x] [Deploy PTDataX Pre-Prod.](https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/3783/)
3. [x] [Verify logo and favicon are unchanged / still work.](https://pprd.ptdatax.tacc.utexas.edu/)
> feat: TV3-181/cmd-79 change FAVICON & LOGO prefix

- Makefile
This PR adds a new variable to the `Makefile` context: `DOCKER_IMAGE_BRANCH`
This variable will correspond to the git tag for the commit if it exists, else the branch name for the commit, with special characters replaced with `-`.
> Quick: Update Makefile to support git branches

- taccsite_cms/static/site_cms/js/modules/setTargetForExternalLinks.js
Prevent banner links from opening in new windows.
- [TUP-703](https://tacc-main.atlassian.net/browse/TUP-703)
Changes what is considered an external link. Looks for the host name with or without www., then opens in new window if it isn't matching to the document's host.
A) If you'd like to troubleshoot in TUP-UI Repo:
1. Comment out code on Core CMS
2. Follow https://github.com/TACC/Core-CMS/wiki/Locally-Develop-CMS-and-TUP-CMS
3. Make snippet with code in TUP -> look at attachment for example
4. Add snippet to Django and import it in the footer
B) If you'd like to just test these changes in TUP-UI using Core_CMS
1. Follow https://github.com/TACC/Core-CMS/wiki/Locally-Develop-CMS-and-TUP-CMS
…
The `shouldForceSetTarget` function below:
```
const shouldForceSetTarget = …
```
> TUP-703 TACC Home Banner Links Open in New Window

- taccsite_cms/static/site_cms/js/modules/setTargetForExternalLinks.js
Fix error with `setTargetForExternalLinks.js` change from #805
> Uncaught ReferenceError: scopeElement is not defined
>     at findLinksAndSetTargets (setTargetForExternalLinks.js:11:17)
>     at software-list/:928:3
- fixes #805
- **replaced** `scopeElement` with `document`
1. Copy edited script to https://github.com/TACC/tup-ui clone at `/apps/tup-cms/src/taccsite_cms/static/site_cms/js/modules/setTargetForExternalLinks.js`.
2. On TUP-UI clone, ran `npx nx build tup-cms`.
3. On TUP-UI clone, ran `npx nx serve tup-cms`.
4. On TUP-UI clone, ran `docker exec -it tup_cms sh -c "python manage.py collectstatic --no-input --clear --ignore assets/*/font*.css"`.
| - | - |
| <img width="960" alt="before" src="https://github.com/TACC/Core-CMS/assets/62723358/749051ef-7bb7-4582-94 …
> hotfix: setTargetForExternalLinks missing scopeElement

- package-lock.json
- package.json
Update to newer release of https://github.com/TACC/Core-Styles.
- https://github.com/TACC/Core-Styles/releases
- table redesign
- button fix
- tag padding tweak
- `<hr>` fixes
1. View/Add a table. View on narrow screen. Verify it looks [CMS table](https://github.com/TACC/Core-Styles/pull/127).
<details><summary>Sample Markup</summary>
```html
<table>
<thead>
<tr>
<th>Sample</th>
<th>Table</th>
</tr>
</thead>
<tbody>
<tr>
<td>and</td>
<td>some</td>
</tr>
<tr>
<td>sample</td>
<td>data</td>
</tr>
</tbody>
</table>
```
</details>
2. View/Add a button with less text and wide width. Verify text is centered.
<details><summary>Sample Markup</summary>
```html
<button class="c-button c-button--type-primary c-button--width-long">Button</button>
```
</details>
3. View/Add a tag. Verify it has …
> feat: @tacc/core-styles v2.25

- taccsite_cms/static/site_cms/js/modules/setTargetForExternalLinks.js
Cleanup `setTargetForExternalLinks.js` script.
- polishes:
- #803
- #805
- #808
- re-indent
- rename vars
- remove cruft
Skipped.
> style: setTargetForExternalLinks polish

- taccsite_cms/static/site_cms/js/modules/setTargetForExternalLinks.js
Make `setTargetForExternalLinks` also change link URL to relative if it is absolute yet on same host.
- fixes [TUP-694](https://tacc-main.atlassian.net/browse/TUP-694)
- **added** feature to script `setTargetForExternalLinks`
Set up:
1. Check out branch `fix/tup-694-absolute-urls-to-same-domain-should-be-relative`.
2. Update local CMS with new code (e.g. rebuild or "collectstatic").
<details><summary>Commands</summary>
- **either** `make stop && make build && make start`
-  **or** `docker-compose -f ./docker-compose.dev.yml up --detach && docker exec -it core_cms sh -c "python manage.py collectstatic --no-input"`
</details>
3. Open CMS e.g. http://localhost:8000/.
Test fix:
4. Create/Identify a link that **both** is to a different page on the same host **and** uses an absolute URL.
5. …
> fix: tup-694 abs URLs to same domain should be rel

- taccsite_cms/templates/share_on_social.html
Re-order share platforms.
- part of closed [TUP-667](https://tacc-main.atlassian.net/browse/TUP-667)
- untracked task of [TUP-584](https://tacc-main.atlassian.net/browse/TUP-584)
- **changed** social media share platform order to match order of items in setting list
0. Add to `settings_local.py`:
```
TACC_SOCIAL_SHARE_PLATFORMS = ['instagram', 'facebook', 'email']
```
1. Create news article.
2. Open news article.
3. Verify icons are present and working and in this order:
1. instagram
2. facebook
3. email
| - | - |
| <img width="1194" alt="before" src="https://github.com/TACC/Core-CMS/assets/62723358/9b45516a-689c-425a-ac77-477bf3cb56b0"> | <img width="1194" alt="after" src="https://github.com/TACC/Core-CMS/assets/62723358/a0f59e95-702f-4165-8355-900b26c2e748"> |
> feat: tup-584 re-order share platforms

- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.css
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.item.css
Redesign social media share links.
- [TUP-590](https://tacc-main.atlassian.net/browse/TUP-590)
- **added** color change on hover
- **added** different size icons for "touch" vs **not** "touch"
- **changed** layout of share links
1. Create news article.
2. Open news article.
3. Review share links style and layout.
4. Open developer tools.
5. Change to view page as if on mobile (touch) or desktop (touch).
6. Review share links size.
| - | - |
| <img width="1155" alt="page before" src="https://github.com/TACC/Core-CMS/assets/62723358/ebe16116-7adb-4aeb-ba63-994c23d04ead"> | <img width="1155" alt="page after - desktop" src="https://github.com/TACC/Core-CMS/assets/62723358/3f1ee52b-418b-4fb3-a42e-d3158f23c62a"> |
| Mouse<br /><sup>e.g. typical Desktop</sup> | Touch<br …
> feat: tup 590 change position and style of social media

- taccsite_cms/contrib/taccsite_blockquote/cms_plugins.py
Removes blockquote plugin from text editor
[CMD-73](https://tacc-main.atlassian.net/browse/CMD-73)
Changes `taccsite_cms/contrib/taccsite_blockquote/cms_plugins.py` -> `text-enabled = True` to `text-enabled = False`
1. Create a text plugin
2. In the plugin, there's a cms plugin dropdown
3. Make sure there is no Blockquote plugin under TACC Site
> CMD-73 Remove Taccsite Blockquote Plugin from Text Editor

- taccsite_cms/templates/djangocms_blog/post_list.html
The News header should match the title of the page. Not just be the word "News".
https://tacc-main.atlassian.net/browse/CMD-107
Changes the template from hard-coding, only using "News" to using the page title.
1. Create a news section
2. Navigate to page settings under the Page menu
3. Select Page Settings
4. Change the Page Title
5. Make sure the heading of the page changes in correlation to the Page Title
| --- | --- |
| <img width="2560" alt="Screenshot 2024-03-19 at 5 41 57 PM" src="https://github.com/TACC/Core-CMS/assets/63771558/030f2397-9dcc-47e9-9b75-e5333de64d22"> | <img width="2560" alt="Screenshot 2024-03-19 at 5 42 55 PM" src="https://github.com/TACC/Core-CMS/assets/63771558/57b17d9a-bc66-4ec3-a44c-029681ffdf87"> |
> CMD-107 News Feed Main Page Should Use Page Title

- taccsite_cms/settings.py
Make Core-Styles v2 be the default for new client websites.
N/A
- **changed** version of `TACC_CORE_STYLES_VERSION`
1. Be on `main` with default settings.
2. `make build && make start`
3. Load website.
4. See old `site…css` stylesheets loaded.
1. Be on `feat/core-styles-v2-by-default` with default settings.
2. `make build && make start`
3. Load website.
4. See new `core-styles…css` stylesheets loaded.
| v0 | v2 |
| - | - |
| <img width="1194" alt="Core-Styles v0" src="https://github.com/TACC/Core-CMS/assets/62723358/df6eddcc-09c1-4468-9f54-710122c0d484"> | <img width="1194" alt="Core-Styles v2" src="https://github.com/TACC/Core-CMS/assets/62723358/582aef22-08bb-4f0a-8553-35111c8439ae"> |
> feat: core-styles v2 by default

- taccsite_cms/management/commands/group_perms/media_editor_advanced.py
- taccsite_cms/management/commands/group_perms/text_editor_advanced.py
Do not let editors publish by default.
<details>The permission to publish must only be given via "Page Publisher" group, so it is obvious who has publishing, the most dangerous permission.</details>
_P.S. News Editor can still publish, because publishing articles is really just editing a boolean option on the article; thus, for News, edit article equals publish article._
N/A. I just noticed this while testing publish permission for a user that mysteriously already had permission.
- **deleted** publish permission form editor perm. scripts
1. Create CMS without these groups.
2. Add these groups via script.
3. Create a test staff user assigned to these groups.
4. Give this group permission to publish only the home page.
5. Verify staff user cannot publish.
4. Add "Publish page" permission to …
> hotfix: do not let editors publish by default

- common_apps/email_management/apps.py
- taccsite_cms/settings.py
Move the `mail_management` app to a new (temporary) location for Core-CMS common apps.
<details><summary>Temporary? What's the Plan? Why not do it right now?</summary>
- Yes, temporary; until the WI team has more time to suffer the side effects of the plan.
- Plan is to:
1. Rename `apps` to `/custom_apps` or `apps/custom`.
2. Update client apps accordingly.
3. (Maybe) Move `email_management` to `/apps`.
- Not now, because [TACC/Core-CMS-Custom](https://github.com/TACC/Core-CMS-Custom) and [TACC/tup-ui](https://github.com/TACC/tup-ui) (and maybe even [TACC/Camino](https://github.com/TACC/Camino)) need to change to not break on rename of a directory that docker-compose files depend on.
</details>
- [CMD-141](https://tacc-main.atlassian.net/browse/CMD-141)
- affects …
> refactor: CMD-141 move email_management app

- taccsite_cms/static/site_cms/js/modules/setTargetForExternalLinks.js
Use `link.getAttribute('href')` not `link.href`, so `isAbsolute` is not `true` for News list "Previous" and "Next" links.
- [TUP-714](https://tacc-main.atlassian.net/browse/TUP-714)
- **changed** `link.getAttribute('href')` not `link.href` in `setTargetForExternalLinks.js`
1. Use the new file on a news page with pagination.
- **A.** Load a page with News on which you've added enough articles.
<sup>To create less articles, set pagination threshold to be very small.</sup>
- **B.** Edit same file on `tup_cms` container directly while running https://github.com/TACC/tup-ui.
2. Verify "Previous" or "Next" links work.
| Script | Page |
| - | - |
| ![file](https://github.com/TACC/Core-CMS/assets/62723358/0d346248-9f1f-4f82-af90-6b0d9de74212) | …
> hotfix: TUP-714 news list page links not working

- taccsite_cms/_settings/auth.py
Document that LDAP Auth is not supported without a full portal.
Verified by @taoteg, today.
> docs(auth): LDAP not supported sans Portal

- taccsite_cms/_settings/search.py
- taccsite_cms/settings.py
Allow a project to disable ElasticSearch.
- [WP-582](https://tacc-main.atlassian.net/browse/WP-582)
- [CMD-155](https://tacc-main.atlassian.net/browse/CMD-155)
- **added** setting `PORTAL_ES_ENABLED`
- **moved** search settings to `_settings/search.py`
- **changed** search settings to require `PORTAL_ES_ENABLED`
1. Create new CMS-only Portal.
2. Deploy.
3. Create homepage.
4. Verify homepage is created (no 500 error).
| Ref. | Link |
| - | - |
| Image | [`taccwma/core-cms/feat-support-disabling-elasticsearch`](https://hub.docker.com/layers/taccwma/core-cms/feat-support-disabling-elasticsearch/images/sha256-4ed2a5a3f77e3ebe2594b05c6fa073ad6f569b8d487ac8c674863846960eab09?context=explore) |
| Deploy | [Core_Portal_Deploy#405](https://jenkins.portals.tacc.utexas.edu/job/Core_Portal_Deploy/405 …
> feat: support disabling elasticsearch

- taccsite_cms/settings.py
- taccsite_cms/templates/header.html
Allow user to set custom nav width (Bootstrap-based).
- to introduce via #792
- **added** `PORTAL_NAV_WIDTH` (`sm`, `md`, `lg`, `xl`, default `False`)
1. Have working CMS.
2. Set `PORTAL_NAV_WIDTH` to `sm`.
3. Open website at different window widths.
4. Navigation should not collapse until width is very narrow.
https://github.com/TACC/Core-CMS/assets/62723358/b5d91b63-5fc4-4e1d-927f-afb7e4d8d86e
> feat: custom nav width via PORTAL_NAV_WIDTH

- taccsite_cms/templates/nav_cms_breadcrumbs.html
Disable 2nd-level breadcrumbs (because they always redirects to 3rd-level).
<details><summary><strong>Details</strong></summary>
**TL;DR**: Server-side menu node properties to programmatically disable links (remove `href`) are blank, so we use JavaScript to force-disable 2nd-level breadcrumbs. The styles merely tweak disabled breadcrumb appearance.
---
In Django CMS, a page added such that it appears in the navigation. On that page, the page will appear in the breadcrumbs as text, not a link, because it is the current page. _Server-side code performs that._ A parent page can be added such that it appears in the navigation as a dropdown link. The link only opens the menu of child pages; it does not navigate user to a page. _Server-side code performs that_. If one visits a child page, the …
> fix: CMD-162 disable 2nd-level CMS breadcrumbs

- taccsite_cms/static/site_cms/js/modules/setTargetForExternalLinks.js
Change `aria-description` to `aria-label` for links that open in new window.
- [TUP-725](https://tacc-main.atlassian.net/browse/TUP-725)
- **changed** an attribute in a script
Skipped.
> fix: TUP-725 wrong a11y attribute for links

- common_apps/email_management/apps.py
Support `{form_name}` in `PORTAL_CONF_EMAIL_TEXT` and `PORTAL_CONF_EMAIL_HTML`.
- [CMD-112](https://tacc-main.atlassian.net/browse/CMD-112)
- mirrors https://github.com/TACC/Core-CMS/pull/846
- required by https://github.com/TACC/tup-ui/pull/448
- **added** another text replacement
https://github.com/TACC/tup-ui/pull/448
| | | |
| - | - | - |
| <img width="664" alt="1" src="https://github.com/TACC/Core-CMS/assets/62723358/aa2a0d1b-70d5-47ef-ba52-66a40f2ea81f"> | <img width="664" alt="2" src="https://github.com/TACC/Core-CMS/assets/62723358/4a259c06-6937-415b-9b7a-05a5ff7cb0ff"> | <img width="664" alt="3" src="https://github.com/TACC/Core-CMS/assets/62723358/dcc67848-8c2b-4c01-9879-adff42acb12e"> |
> feat: CMD-112 `form_name` in custom email message — off v4.10.2

- common_apps/email_management/apps.py
Support `{form_name}` in `PORTAL_CONF_EMAIL_TEXT` and `PORTAL_CONF_EMAIL_HTML`.
- [CMD-112](https://tacc-main.atlassian.net/browse/CMD-112)
- mirrored by https://github.com/TACC/Core-CMS/pull/847
- required by https://github.com/TACC/tup-ui/pull/448
- **added** another text replacement
https://github.com/TACC/Core-CMS/pull/847
> feat: CMD-112 `form_name` in custom email message

- apps/custom_example/urls.py
- apps/custom_example/views.py
- taccsite_cms/urls.py
- Rename custom example app view to more familiar pattern.
- **Log error from any custom app urls.**
- helped me debug while working on [TUP-706](https://tacc-main.atlassian.net/browse/TUP-706)
- **renamed** custom example app view
- **added** logging for custom app urls
0. Have CMS and custom example app working.
1. Make any obvious error in the custom example app code.
2. Verify log shows the error.
Skipped.
> fix: custom app with custom url is difficult to debug

- taccsite_cms/urls.py
Simplify code that allows debugging custom url failure.
- simplifies #851
- mimics #485
- **removed** logging from `urls.py`
- **changed** an `ImportError` to `ModuleNotFoundError`
1. Have CMS and custom example app working.
2. Make any obvious error in the custom example app code.
3. Verify log shows the error.
Skipped.
> refactor: simplify custom url debugging

- poetry.lock
- pyproject.toml
Fix third-party bug preventing creation and edit of containers.
- [WP-407](https://tacc-main.atlassian.net/browse/WP-407)
- requires https://github.com/django-cms/djangocms-bootstrap4/pull/164
Installed [`master` branch commit](https://github.com/django-cms/djangocms-bootstrap4/compare/3.0.1...master) of `djangocms-bootstrap4` @ 3.0.1+ (`49983f4`)
1. Create a Container.
2. Edit a Container.
https://github.com/user-attachments/assets/231bc832-f244-4c84-80ec-88a451d7b409
https://github.com/user-attachments/assets/c8208d55-4786-4291-b419-dc26fc266329
> fix: WP-407 unable to edit nor create container

- taccsite_cms/templates/nav_cms_breadcrumbs.html
Do not try to remove 2nd-level breadcrumb link if it does not exist.
- [CMD-162](https://tacc-main.atlassian.net/browse/CMD-162)
- fixes #838
- **add** checks for element existence before accessing
1. Open a page whose only parent page is home.
<sup>E.g. https://pprd.frontera-portal.tacc.utexas.edu/system/</sup>
2. Verify no error in console.
<sup>E.g. `Cannot read properties of null (reading 'removeAttribute')`</sup>
| - | - |
| <img width="618" alt="CMD-162 before" src="https://github.com/user-attachments/assets/778eda5c-0d15-49b8-979e-3c8de65825e8"> | <img width="618" alt="CMD-162 after" src="https://github.com/user-attachments/assets/37b44a95-a158-45ae-8201-13cb5b302d67"> |
> fix: CMD-162 error if no second breadcrumb

- Makefile
- README.md
Docker v2 has different command for `docker compose`. Adjust Makefile to handle both based on availability.
- [WP-602](https://tacc-main.atlassian.net/browse/WP-602)
- mimics https://github.com/TACC/Core-CMS-Custom/pull/295
- similar to https://github.com/TACC/Core-CMS-Custom/pull/301
- **added** conditional `docker compose` command to Makefile
- **changed** `docker-compose` to `docker compose` in README
1. `make build` — no error firing command from Makefile
2. `make start` — no error firing command from Makefile
Skipped.
> fix: WP-602 `docker compose` with and without dash

- Makefile
- docs/upgrade-project.md
Prepare developers to not use `docker-compose`.
Deprecate `docker-compose` (to be removed in v5).
- https://github.com/TACC/Core-CMS/pull/858#issuecomment-2274214435
- **added** v4.14 upgrade step
N/A
See [`upgrade-project.md` at from v4.N to v4.14](https://github.com/TACC/Core-CMS/blob/docs/deprecate-docker-compose-v1-command/docs/upgrade-project.md#from-v4n-to-v414).
> docs: deprecate docker-compose

- Makefile
- README.md
Assume anyone running `make start` is developing locally.
<details>Our deploy process uses its own docker-compose files and Dockerfiles.</details>
- mimics https://github.com/TACC/Core-Portal/blob/v3.7.0/Makefile#L29-L39
- **changed** Makefile to use dev compose files
- **changed** README to assume reader is a developer
1. `make build`
2. `make start`
3. change any code
4. verify change is synced to docker compose
1. Read ["Getting Started"](https://github.com/TACC/Core-CMS/blob/chore/assume-anyone-running-make-start-within-repo-is-developing/README.md#getting-started) (specifically, "3. Build & …").
5. Read ["Update Project"](https://github.com/TACC/Core-CMS/blob/chore/assume-anyone-running-make-start-within-repo-is-developing/README.md#update-project) (specifically, "▶ Advanced").
> enhance: assume local development

- package-lock.json
- package.json
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.page.css
Add `s-drop-cap` support via code to Core instead of snippet on TUP.
- [TUP-730](https://tacc-main.atlassian.net/browse/TUP-730)
- **required by** https://github.com/TACC/tup-ui/pull/477
- **updated** to [Core-Styles v2.31.0](https://github.com/TACC/Core-Styles/releases/v2.31.0)
See https://github.com/TACC/tup-ui/pull/477.
> fix: tup 730 news drop cap should work even if no caption

- package-lock.json
- package.json
- taccsite_cms/static/site_cms/css/src/_imports/generics/pseudo-elements.css
Add and use design tokens.
- [CMD-182](https://tacc-main.atlassian.net/browse/CMD-182)
- requires https://github.com/TACC/Core-Styles/pull/372
- requires https://github.com/TACC/Core-CMS-Resources/pull/200
- required by https://github.com/TACC/tup-ui/pull/476
- **updates** Core-Styles version
- **removes** `--global-color-…-rgb` CSS vars
<sup>affects few clients, fixed in https://github.com/TACC/Core-CMS-Resources/pull/200</sup>
- **removes** deprecated CSS vars
<sup>affects tup, fixed in https://github.com/TACC/tup-ui/pull/476</sup>
- https://dev.cep.tacc.utexas.edu/ colors are unchanged
<sup>(inc. home page `s-hero-banner` bg. color)</sup>
- see https://github.com/TACC/Core-CMS-Resources/pull/200
- see https://github.com/TACC/tup-ui/pull/476
> enhance: CMD-182 design tokens

- .gitignore
- README.md
- taccsite_cms/secrets.example.py
- taccsite_cms/settings_local.example.py
Create a `secrets.example.py`.
- similar to https://github.com/TACC/Core-CMS/pull/577
- similar to [Core-Portal's `settings_secret.example.py`](https://github.com/TACC/Core-Portal/blob/v3.7.0/server/portal/settings/settings_secret.example.py)
- **added** `secrets.example.py`
- **documented** creation of `secrets.py`
- **documented** creation of `settings_custom.py`
N/A
> feat: secrets.example.py

- package-lock.json
- package.json
Update to Core-Styles [v2.33.0](https://github.com/TACC/Core-Styles/releases/tag/v2.33.0) to get `s-footer` enhancements.
- https://github.com/TACC/tup-ui/pull/476
> deps: s-footer updates via core-styles 2.33.0

- package-lock.json
- package.json
Update to Core-Styles v2.33.1, which restores v2 Portal message styles.
See https://github.com/TACC/tup-ui/pull/476 at "Portal Message Style is Unchanged".
> deps: core-styles v2.33.1

- taccsite_cms/urls_custom.example.py
Ensure `custom_example` app will render.
This bug kept confusing me when I use the app as reference but it does not work.
- **changed** path syntax for url
1. In `custom_app_settings.py`, add `custom_example` app e.g.
```py
CUSTOM_APPS = ['apps.custom_example']
```
2. In `urls_custom.py`, add `custom_example` app e.g.
```py
re_path(r'^custom_test/', include('apps.custom_example.urls', namespace='custom_test')),
```
3. Open https://localhost:8000/custom_test.
4. See "CUSTOM APP" page rendered.
> fix: custom_example app not working

- taccsite_cms/templates/header_branding.html
Be able to hide branding bar just by setting `PORAL_BRANDING` to false.
- achieves documented promise/lie in #841
- **changed** template logic `else` to an `elif`
1. Set `PORTAL_BRANDING = False`.
2. Load website.
3. Verify branding bar markup is not rendered.
<sup>(Best to test on a site that is **not** hiding branding bar via CSS.)</sup>
| - | - |
| <img width="919" alt="BEFORE" src="https://github.com/user-attachments/assets/61222c14-efcb-41b7-8a15-9453c4dd63e1"> | <img width="919" alt="AFTER" src="https://github.com/user-attachments/assets/16581e9c-0df3-4865-afd5-ff30f828dd9f"> |
> [!NOTE]
> This site hides branding bar via CSS, so I test for markup presence.
> fix: do not show branding if setting is false-y

- taccsite_cms/settings.py
Add "Muted" sections to Container drop-down.
- fixes #431
- **added** item to list
1. Add Container.
2. Choose "Muted" option.
3. Verify muted section is added.
> fix: add muted section to container dropdown

- taccsite_cms/templates/nav_search.html
Injecting the TACC search bar is not affected by the presence of Bootstrap, so don't load markup inside the custom element.
- fixes bug in #856
- mirrored by https://github.com/TACC/Core-Portal/pull/971
- **removed** cloning of markup that loads Bootstrap stylesheet
1. Verify Bootstrap markup being cloned has no effect on UI and UX.
https://github.com/user-attachments/assets/73444042-05fb-4c27-858d-fe0a54b0ca13
https://github.com/user-attachments/assets/f5f392b8-6861-49b8-a30d-7844a85d2fb4
**Why?** This may have had a purpose, and better CSS made that purpose moot. This may have had a theoretical-only purpose.
> chore: do not clone bootstrap for `tacc-search-bar`

- taccsite_cms/custom_app_settings.example.py
- taccsite_cms/settings_custom.example.py
- taccsite_cms/urls_custom.example.py
Simplify blog installation steps by 100% using example settings in appropriate files.
- CTRN News (coming soon)
- [WTCS News](https://prod.wtcs.tacc.utexas.edu/news/latest-news/)
- **moved** blog settings to relevant customization example files
1. [Use these settings on a website.](https://github.com/TACC/Core-Portal-Deployments/compare/19cbc93...320934a)
2. Deploy that website.
3. [Verify blog is installed.](https://prod.wtcs.tacc.utexas.edu/news/latest-news/)
Skipped.
> fix: blog install steps are outdated

- taccsite_cms/settings.py
- taccsite_cms/static/site_cms/img/guides/README.md
- taccsite_cms/templates/guides/README.md
Retire deprecated templates (that will still work).
- [CMD-143](https://tacc-main.atlassian.net/browse/CMD-143)
- quick n’ safe version of #854
- **deleted** "Guide" templates from default choices
**None.** If template is already set to one of these, it will still work. Pages simply cannot be newly set (nor re-set) to these templates.
Skipped.
> chore: CMD-143 retire deprecated templates

- taccsite_cms/settings.py
Add "Section" (no color) to Container options.
- assists with [WP-588](https://tacc-main.atlassian.net/browse/WP-588)
- **changed** `DJANGOCMS_BOOTSTRAP4_GRID_CONTAINERS` setting
1. Create a "Container + Section (…)".
<sup>i.e. `container o-section`</sup>
2. Create a "Fluid container + Section (…)".
<sup>i.e. `container-fluid o-section`</sup>
3. Create a "Section (…)".
<sup>i.e. `o-section`</sup>
4. Verify each is created with expected classes.
| render | select |
| - | - |
| <img width="845" alt="PR 891" src="https://github.com/user-attachments/assets/53a7f27e-080b-4604-871c-54a7f611480f"> | <img width="845" alt="PR 891 dropdown" src="https://github.com/user-attachments/assets/ef9a7336-335d-4629-83ae-c68102092d5e"> |
> enhance: transparent/margin section via Container

- taccsite_cms/static/site_cms/js/modules/importHTML.js
Fix bug of rendering `null` above header on Portal if CMS has no header branding.
Noticed on https://pprd.lccf-portal.tacc.utexas.edu/workbench.
- **changed** JavaScript logic
0. Ensure `null` is rendered on a full Portal (after login).
1. Deploy CMS with image from this branch onto that portal.
2. Verify `null` does not show on that portal (after login).
| - | - |
| <img width="845" alt="before" src="https://github.com/user-attachments/assets/94313b4f-1ca4-4742-b629-cddd0539a499"> | <img width="845" alt="after" src="https://github.com/user-attachments/assets/3122ea62-99d2-4350-8802-53eb24d424d5"> |
> fix: importHTML.replaceFromURL can return null

- taccsite_cms/management/commands/group_perms/media_editor_advanced.py
A "Media Editor (Advanced)" did not have "use directory listing" nor "view folders" permissions, yet a "Media Editor (Basic)" did.
None. I found this bug while preparing permission set for WTCS.
- **added** permissions to "Media Editor (Advanced)"
Skipped.
> fix: media editor adv unable to view/use folders

- taccsite_cms/settings.py
Restore ability to add a container that has no classes.
- WeTeach CS website
- **changed** value in a setting
- **added** values to a setting
1. Verify Container select menu has changed (see settings diff).
Skipped.
> fix: restore empty Container

- taccsite_cms/settings.py
Reorder the options for the "Type:" or a "Container" plugin.
- follow-up to #897
- **changes** setting values
1. Verify options for "Type:" of Container have changed.
| - | - |
| <img width="920" alt="before" src="https://github.com/user-attachments/assets/030bfebb-b2e0-4c5e-992d-c15e6aec8791"> | <img width="920" alt="after" src="https://github.com/user-attachments/assets/38e84f4f-c666-4d82-9eef-768162892abb"> |
> refactor: reorder Container type options

- taccsite_cms/static/site_cms/js/modules/setTargetForExternalLinks.js
Allow `findLinksAndSetTargets` to be performed on given links.
- [CMD-193](https://tacc-main.atlassian.net/browse/CMD-193)
- **added** parameter `links` to `findLinksAndSetTargets()`
1. <details><summary>Load on a Core-CMS website.</summary>
1. Login as admin to website.
2. Create a snippet:
```html
<script type="module">
/* TODO: After deploy of Core-CMS version that has https://github.com/TACC/Core-CMS/pull/902, change this snippet to load `/static/site_cms/js/modules/setTargetForExternalLinks.js` */
import findLinksAndSetTargets from 'https://cdn.jsdelivr.net/gh/TACC/Core-CMS@582f626e/taccsite_cms/static/site_cms/js/modules/setTargetForExternalLinks.js';
const links = document.querySelectorAll(
'a[href*="/core/internal-docs/"]'
);
findLinksAndSetTargets( links, {
shouldDebug: …
```
> feat: CMD-193 custom links for findLinksAndSetTargets

- README.md
- taccsite_cms/secrets.example.py
- taccsite_cms/settings_local.example.py
Tweaks to support https://github.com/TACC/Core-Portal/pull/1034.
* [feat: CMD-194 enable portal nav by default](https://github.com/TACC/Core-CMS/commit/abcbcfb929d77a27a09242eb6f0a28950429383f)
* [docs: CMD-194 expand CMS database content notice](https://github.com/TACC/Core-CMS/commit/5ea38029e3bf4c40585c552a1f3a343a321819de)
1. Load up CMS.
2. Verify CMS nav menu loads.
3. Verify Portal nav menu is absent.
<sup>It is enabled, but there is no menu available, so CMS shows nothing.</sup>
| CMS Settings |
| - |
| <img width="960" alt="CMD-194" src="https://github.com/user-attachments/assets/28d5ff42-a2b9-4e0f-9bd0-5f5fe0b0fb50"> |
> feat: cmd-194 enable portal nav by default

- .gitignore
- taccsite_cms/settings.py
- taccsite_cms/settings_default.example.py
- taccsite_cms/settings_default.py
Support default CMS customization in Core-Portal.
- [CMD-194](https://tacc-main.atlassian.net/browse/CMD-194)
- required by https://github.com/TACC/Core-Portal/pull/1034
- **added** `settings_default.py`
- Have a running local CMS.
- Verify **no** `settings_*.py` file has `PORTAL_HAS_SEARCH = True`.
1. Verify search bar is **visible** in header.
2. `make stop`
3. `cp taccsite_cms/settings_default.example.py taccsite_cms/settings_default.py`
4. `echo "PORTAL_HAS_SEARCH = False" >> taccsite_cms/settings_default.py`
5. `make start`
6. Verify search bar is **absent** in header.
https://github.com/user-attachments/assets/736bfeed-8617-4c0c-91db-bade4e6841b0
> feat: default custom settings `settings_default`

- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.picture.css
Missing ` img` in a selector.
- noticed during https://github.com/TACC/Core-CMS-Custom/pull/416[^1]
[^1]: While testing retrofitting this code for a Core-Styles v0 Core-CMS site, I noticed this code has this bug.</sup>
> fix: typo in our djangocms-picture css selector

- poetry.lock
- pyproject.toml
Needed for TUP-- this is a diff that passes additional information into the form signal handler.
https://github.com/avryhof/djangocms-forms/commit/088a30b42bca2e5c814fed72e7d773cf20b4099b
- testing via https://github.com/TACC/tup-ui/pull/499
> [TUP] Update djangocms-forms dependency

- taccsite_cms/templates/assets_core_delayed.html
The jQuery form plugin used by djangocms-forms is **not** compatible with jQuery slim (see: https://github.com/jquery-form/form). This diff replaces jquery-slim with the full-fat version, which includes the required ajax config.
- fixes bug in https://github.com/TACC/tup-ui/pull/499 [^1]
- caused by #901 [^1]
[^1]: Note by @wesleyboar
> Quick: Use non-slim jQuery dep to fix djangocms-forms incompatibility

- taccsite_cms/templates/nav_portal.html
Make Bootstrap5-powered portal nav still work on CMS which uses Bootstrap4.
- [WP-895](https://tacc-main.atlassian.net/browse/WP-895)
- **added** JavaScript to repair menu
1. Run Core-Portal with this Core-CMS.
2. Open CMS page.
3. Verify portal nav dropdown menu location is underneath its toggle.
https://github.com/user-attachments/assets/80a93d74-b1ef-4510-8306-4128bfda9a3f
https://github.com/user-attachments/assets/cfcaf3e3-6e7f-4b9e-9aec-1bf2bb7fdb94
> fix: WP-895 portal nav with bootstrap5 does not open

- taccsite_cms/management/commands/group_perms/grid_editor_advanced.py
- taccsite_cms/management/commands/group_perms/grid_editor_basic.py
- taccsite_cms/management/commands/group_perms/media_editor_advanced.py
- taccsite_cms/management/commands/group_perms/media_editor_basic.py
- taccsite_cms/management/commands/group_perms/news_writer_advanced.py
- taccsite_cms/management/commands/group_perms/news_writer_basic.py
- taccsite_cms/management/commands/group_perms/text_editor_advanced.py
- taccsite_cms/management/commands/group_perms/text_editor_basic.py
- taccsite_cms/management/commands/util.py
Rename a utility function.
- supports #915
- **renamed** `let_view_and_change_page_structure` to `let_view_page_and_structure`
Skipped.
N/A
- Goal is to not mislead developers when a new group has only this perm.
- A user with only this permission can not edit content.
- A user that will edit content must have this permission.
> refactor: rename a group perm utility function

- taccsite_cms/management/commands/group_perms/unpublished_page_viewer.py
Add group "Unpublished Page Viewer".
- supported by #914
- documented by [Django CMS - Developer Guide - Permissions & Groups](https://tacc-main.atlassian.net/wiki/x/egtv?atlOrigin=eyJpIjoiYzM1NTRlNzkwOWQ0NDI5ZmFjMzlkMWVkYjU2ZmY3MDUiLCJwIjoiYyJ9)
- **added** new group
> [!NOTE]
> I tested manually on TUP prod, which uses this permission set for "Unpublished Page Viewer".
0. Create/Find ["Unpublished Page Viewer" Group](https://tacc.utexas.edu/admin/auth/group/38/change/).
1. Add Page global permission for that Group that "Can edit" (and optionally "View restricted").
2. To that Group, add permissions of `let_view_page_and_structure`.
3. Give a User that group, and only that Group.
4. Create [an unpublished page](https://tacc.utexas.edu/tacc-user-portal/hetdex-access-request/?edit).
5. …
> feat: unpublished page viewer group

- package-lock.json
- package.json
Update Core-Styles to swap header font from Benton to Roboto.
- caused by https://github.com/TACC/Core-Styles/pull/470
- used by https://github.com/TACC/Core-Portal/pull/1068
> deps: core-styles v2.39.4 (header font swap)

- taccsite_cms/templates/nav_portal.html
Portal nav menu alignment fixed for Portal Bootstrap 5 broke it for CMS Bootstrap 4.
- [WP-894](https://tacc-main.atlassian.net/browse/WP-894)
- caused by:
- https://github.com/TACC/Core-Portal/pull/1073
- https://github.com/TACC/Core-Portal/pull/1066
- **adds** script to swap JavaScript class
1. Open Core-CMS that is served via Core-Portal.
2. Verify portal nav dropdown menu is aligned so it is not off-screen.
https://github.com/user-attachments/assets/db7e344a-0f09-4b39-80d2-15e87a0a2ee0
> fix: wp-894 portal nav dropdown menu alignment

- package-lock.json
- package.json
Update Core-Styles.
- **adds** Bootstrap 4 Pagination
- **refactors** `c-page`
- **refactors** Django CMS Pagination
> [!WARNING]
> **Skipped.** I rely on Core-Styles promise of backwards-compatibility.
1. Verify a CMS with a blog (e.g. [CTRN](https://ctrn-web.tacc.utexas.edu/)) has same pagination styles.
2. Verify a CMS using pagination (.e.g [APCD](https://github.com/TACC/Core-CMS-Custom/tree/main/apcd_cms)) on a CMS page can rely on CMS styles.
> deps: core-styles v2.40

- package-lock.json
- package.json
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.css
Fix styles for pagination on Blog/News page.
- fixes #919
- **changes** which pagination stylesheet is loaded
https://github.com/user-attachments/assets/ecda5ac6-4dd2-4fcd-96d2-7501ddcedb1c
https://github.com/user-attachments/assets/5b344f15-2664-4e98-a400-92a526603850
> [!NOTE]
> The "Next" link gets closer to "Page X of Y" text. That's fine.[^1]
[^1]: The Django CMS Blog pagination styles were always "do our best with what we got, cuz we don't have real pagination". But a font-size change was an actual bug.
> fix: django-cms-blog pagination font too small

- CHANGELOG.md
Maintaining `CHANGELOG.md` is a chore. I'm not doing that. I can revive it (with missed entries) when it is automated off of GitHub Releases.
- **changed** "unreleased" to "Releases Since 4.25.4"
- **deleted** `CHANGELOG` expectations from release guide
- #921
> docs: retire changelog for now

- pyproject.toml
https://jenkins.portals.tacc.utexas.edu/job/Core_CMS_Build/236/console
Python project property `package-mode` defaults to `false`, but that breaks Docker.
<details>
Docker installs Python dependencies, including this project itself; but this project itself is **not** a _proper_ Python package (because it does not need to be, because we share it via Docker instead of via Python, because we weren't Python-package-savvy enough "back in the day").
</details>
- fixes bug from #908
- **restored** `package-mode = false`
1. `make build && make start`
2. No error.
Skipped.
> fix: package-mode breaks Jenkins build

- taccsite_cms/migrations/0002_remove_old_system_monitor_table.py
The migration `0002` must depend on migration `0001`.
- fixes bug from #908
- **added** dependency to system monitor migration
1. `make start`
2. `docker exec -it core_cms python manage.py migrate`
3. no error
> [!CAUTION]
> ```log
> docker exec -it core_cms python manage.py migrate
> /usr/local/lib/python3.11/site-packages/cms/apphook_pool.py:97: UserWarning: No registered apphook "'SearchPageApphook'" found
>   warnings.warn(_('No registered apphook "%r" found') % app_name)
> CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0001_add_groups, 0002_remove_old_system_monitor_table in taccsite_cms).
> To fix them run 'python manage.py makemigrations --merge'
> ```
> [!TIP]
> ```log
> docker exec -it core_cms python manage.py migrate
> …
```
> fix: migration without dependency

- taccsite_cms/templates/base.html
Remove `data-page-id` attribute, because it is unused — we use `#page-…`.[^1]
Also, removed `data-page-template` accidentally added in #944.
[^1]: I searched https://github.com/TACC/Core-CMS, https://github.com/TACC/Core-CMS-Resources, and https://github.com/TACC/tup-ui.
> refactor: retire `data-page-id`

- taccsite_cms/templates/base.html
Do not allow `id="page-None"` in `<html>` tag.
- fixes #944
- failed in #944
1. Do **not** set **Id** (`reverse_id`) for Home page.
2. Visit http://localhost:8000/.
3. Verify `<html id lang="en" class>`.
4. **Do** set **Id** (`reverse_id`) for Home page.
5. Visit http://localhost:8000/.
6. Verify `<html id="page-home" lang="en" class>`.
| not set | set id | has id |
| - | - | - |
| <img width="283" alt="no id" src="https://github.com/user-attachments/assets/18ea3050-dbc2-465c-99b4-c91c16576725" /> | <img width="283" alt="set id" src="https://github.com/user-attachments/assets/57e8b2dd-e140-49d3-abeb-382024c88272" /> | <img width="283" alt="has id" src="https://github.com/user-attachments/assets/52a3f3e8-5834-4336-bc03-cc11c6debf28" /> |
> fix: do not allow `id="page-None"`

- taccsite_cms/templates/base.html
**Add `data-page-template` to `<html>`**, so stylesheets can target pages with specific template e.g. `[data-page-template="…"] { /* ... */ }`.
- replaces #880
- supports https://github.com/TACC/Core-CMS-Custom/pull/293
1. Open http://localhost:8000/.
2. Verify `<html>` has `data-page-template="standard">`.
> feat: data-page-template

- taccsite_cms/templates/base.html
Always use template name, never `INHERIT`.
- fixes #946
- **changes** function/property used to get template
1. Open page that directly uses Standard template.
2. Verify `<html>` tag has `data-page-template="standard"`.
3. Open child page that inherits template.
4. Verify `<html>` tag has `data-page-template="standard"`.
| - | - |
| <img width="469" alt="parent before and after" src="https://github.com/user-attachments/assets/b1103f72-9230-490d-a62f-95ad6f25395f" /> | <img width="469" alt="parent before and after" src="https://github.com/user-attachments/assets/b1103f72-9230-490d-a62f-95ad6f25395f" /> |
| - | - |
| <img width="469" alt="inherit before" src="https://github.com/user-attachments/assets/0556451b-3167-42cf-ae34-c4e6a2c3fd38" /> | <img …
> fix: data-page-template should not be "INHERIT"

- taccsite_cms/templates/analytics.html
Checking for delta between `main` and dev branch.
…
Added nonce for analytics requests.
1. Build and deploy Core-CMS in prod.cep to verify that analytics are still being tracked properly. 
2. Will have to either:
2A. Find the logging from ITS scans being run against the host to see if the flagged issue has been resolved in the security scans.
2B. Find a way to validate the nonce directly (some kind of bash check I suspect).
None.
> added nonce to analytics

- README.md
Documentation for:
- https://github.com/TACC/Core-CMS/pull/933
> docs: programmatic CMS setup

- taccsite_cms/templates/assets_core.html
- taccsite_cms/templates/assets_core_delayed.html
- taccsite_cms/templates/assets_site.html
- taccsite_cms/templates/assets_site_delayed.html
- Bootstrap v4.0.0 → v4.6.2
- jQuery v3.2.1 → v3.5.1
- match how new & old sites load Bootstrap
- emergency security requirement
1. Deploy on an old site e.g. https://frontera-portal.tacc.utexas.edu/.
2. <details open><summary>Verify any Bootstrap scripted UX works:</summary>
**Portal Dropdown:**
1. Log in.
2. Return to homepage.
3. Test portal nav dropdown.
</details>
2. <details open><summary>Verify any Bootstrap UI looks the same:</summary>
- header
- …
</details>
> [!IMPORTANT]
> There might be nothing more to test. I can't think of any other Bootstrap scripted UX on any **old** site.[^1]
[^1]: New sites' Bootstrap version does not change. And, even if it did, the only **new** site I know with Bootstrap scripted UX is https://tacc.utexas.edu/use-tacc/software-list/, click "Version …
> fix: update bootstrap on older websites

- taccsite_cms/management/commands/README.md
- taccsite_cms/management/commands/list_page_templates.py
Add a command that lists all pages using each template in the CMS, along with their full URLs.
- help admins locate pages using [Texascale deprecated templates](https://github.com/TACC/Core-Portal-Deployments/blob/e7d2496/texascale/camino/cms.settings_custom.py#L18-L25)
- help admins refactor or test page templates
- **adds** management command
- **documents** new command
- **improves** documentation for management commands
0. (if you have no instance) `make setup`
1. `make start`
2. `docker exec -it core_cms sh -c "python manage.py list_page_templates"`
3. (optional) test with multisite
<sup>see https://github.com/TACC/Core-CMS/pull/873</sup>
```log
docker exec -it core_cms sh -c "python manage.py list_page_templates"
TEMPLATE: "fullwidth.html"
PAGES:
- Home (https://localhost:8000/)
- …
```
> feat: command to list pages that use each template

- README.md
Improve clarity in Readme "Getting Started".
- mimics https://github.com/TACC/Core-CMS-Template/pull/8
- do **not** tell reader to clone repo
<sup>Some assumptions should be made of reader skill level.</sup>
- tell reader to enter `cms` directory
- tell reader `make clean` is optional
- tell reader "Manual Setup" is a fallback
- tell reader adding content is part of either method
- simplify manual setup steps
- rearrange link aliases
> docs(readme): clarify "Getting Started" steps

- Dockerfile
Update Dockerfile base.
- tested Debian "bullseye" via [jenkins:Core_CMS_Build#322](https://jenkins.portals.tacc.utexas.edu/job/Core_CMS_Build/322/)
- tested Debian "bookworm" via https://github.com/TACC/Core-CMS/pull/490
- tested Debian "bookworm" via https://github.com/TACC/Texascale-CMS/pull/13
Changed Docker base from Python on Debian Buster to Pythonon Debian Bullseye ([like Portal](https://github.com/TACC/Core-Portal/blob/0353772fef26688b7b99426feb1ba49a88e8a83d/server/conf/docker/Dockerfile)).
1. Build.
2. No fail.
3. **No errors in log.**
<sub>Build can succeed yet fail; only visible in log.</sub>
> deps: upgrade debian from buster to bullseye

- taccsite_cms/djangocms_picture/extend.py
Fix validation logic error in "Zoom image" templates.
- fixes #968
- **fixes** parent plugin comparison
- **deletes** unused variables
1. Open https://dev.cep.tacc.utexas.edu/test/image-picture-block/?edit (or similar test page).
2. Edit and save Image at "Template: `zoom_effect` • External image: 🚫 • Within a Link: ✅": "[in a **Link**] Attrs"
- Save should have **no** validation error.
- Image should zoom on hover.
3. Edit and save Image at "Template: `zoom_effect_no_link_to_ext_image` • External image: 🚫 • Within a Link: ✅": "[in a **Link**] Attrs"
- Save should have **no** validation error.
- Image should zoom on hover.
https://github.com/user-attachments/assets/e520007a-21f8-43e8-9a22-60749230fd3d
https://github.com/user-attachments/assets/31b11caf-2c05-4a2a-938c-3c9aebd49f1c …
> fix: u-image-zoom validation

- package-lock.json
- package.json
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.page.css
There should **not** be space under an image that is within a `.u-zoom-image` element.
- required by https://github.com/TACC/Core-Styles/pull/536
- **adds** space below aligned blog article images
<sup>migrated from Core-Styles</sup>
- **updates** Core-Styles version
1. Verify blog article images have space below them.
2. Verify **no** extra space under an image wrapped in a `<span class="u-image-zoom--on-hover">`.
Skipped.
> fix: space under span.u-image-zoom img

- poetry.lock
- pyproject.toml
Pin DjangoCMS Bootstrap 4 dependency to a version not a commit.
The [only release since](https://github.com/django-cms/djangocms-bootstrap4/compare/49983f4...3.0.2) is a "Prepare release" commit.
1. Deploy on existing (staging) site.
2. Verify container options are still available.
3. Verify container options are still working.
https://github.com/user-attachments/assets/e68ca30c-7c65-420c-95fd-4fd5893ba7e2
> deps: djangocms-bootstrap4 v3

- taccsite_cms/settings.py
Allow a custom site (e.g. [Texascale-CMS](https://github.com/TACC/Texascale-CMS)) to overwrite third-party app template (e.g. `djangocms_bootstrap4/tabs/default/tabs.html`)
- required by https://github.com/TACC/Texascale-CMS/pull/22
- tested via https://github.com/TACC/Texascale-CMS/pull/24
- **adds** `taccsite_custom/templates` as a new available template dir
- **documents** `taccsite_custom` itself should not serve as a template dir
1. **Texascale**: https://github.com/TACC/Texascale-CMS/pull/24
2. **Core**: Deployed to dev.cep. No change.
Skipped.
> feat: let custom sites overwrite app templates

- pyproject.toml
- taccsite_cms/templates/snippets/news/open-external-articles.html
- taccsite_cms/templates/snippets/news/redirect-external-article.html
- Add redirect snippet ([#973](https://github.com/TACC/Core-CMS/pull/973)).
- Do **not** add Image Zoom feature.
- Do **not** refactor `djangocms_picture`.
- mimics #973
- skips v4.36.N
- **ports** https://github.com/TACC/Core-CMS/pull/973 to v4.35
- **documents** CMS as v4.35.1
Same as #973.
https://github.com/user-attachments/assets/053e5a49-556c-41b2-821d-05e75fa385d3
https://github.com/user-attachments/assets/9cd43ee1-27a5-4e46-a53d-e3cfc58be5db
> hotfix: v4.35.1 add missing redirect snippet but not image zoom

- poetry.lock
- pyproject.toml
- taccsite_cms/settings.py
- taccsite_cms/static/site_cms/img/icons/cortal.json
- taccsite_cms/static/site_cms/img/icons/logos.json
- taccsite_cms/templates/admin/djangocms_icon/includes/assets.html
Fix icon set icons not appearing if icon set is changed.
- still has known issue https://github.com/django-cms/djangocms-icon/issues/9
- update djangocms-icon to latest
- document requirement for custom icons
- **SET SAME PROPERTIES FOR EVERY ICON SET**
- update cortal icon set
1. Add icon.
2. Select icon for Cortal icon set.
3. Change to Logo SVG set.
4. Change back to Cortal icon set.
5. Verify Cortal icons all visible in icon picker.
https://github.com/user-attachments/assets/267c0f7e-24f2-4583-b6bb-c78b9952a309
<details><summary>
</summary>
Latest version of `djangocms-icon` (years later) did **not** fix problem for me. My solution was to ensure any value set in one custom icon set is also set in every other custom icon set.
Why? The values in different icon sets are not cleared upon …
> fix: djangocms-icon picker not showing Cortal icons
