- .gitignore
- Makefile
- Updated the .gitignore to disregard the docker_repo.var file in the codebase. 
- Edited the Makefile to reflect the correct filename in the assignment block to docker_repo.var.
> Camino-deployment-setup

- README.md
Clarify steps for updating submodule (use case: setting up new brand/project, like ProTX).
* (any ProTX CMS dev ticket)
- __New__: Add "(as necessary)" steps to "Required" section.
N/A
See rendering: https://github.com/TACC/CORE-cms/blob/quick/clarify-submodule-setup-in-readme/README.md
> Quick: Clarify submodule setup/update in README.md

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
Testing the default templates included in GitHub.
> Update Issue Templates

- package-lock.json
- package.json
- yarn.lock
Update dependency lock files.
> The generated file change as a result of running:
> - [`npm audit`](https://docs.npmjs.com/cli/v7/commands/npm-audit)` fix`
> - [`yarn install`](https://classic.yarnpkg.com/en/docs/cli/install/)
> Quick: Run npm audit fix && yarn install

- .gitmodules
From `cms-site-resources` to `Core-CMS-Resources`.
> Quick: Update for taccsite_custom repo rename

- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-portal-nav.css
Add commit that I forgot I had not pushed for recently merged https://github.com/TACC/Core-CMS/pull/237.
> GH-101: Portal Nav (Load with Transition / Animation) - Bug Fixes / Missing Commit

- taccsite_cms/contrib/helpers.py
Revert untested change from hasty hotfix, https://github.com/TACC/Core-CMS/pull/268.
_The rest of the hotfix was good._
> Hotfix: GH-93: 7c49db5d But Do It Right

- CHANGELOG.md
- package.json
- Set version.
- Add changelog.
- __New__: Add `CHANGELOG.md`
- _Minor_: Update `package.json` version.
- [discussion about version](https://tacc-team.slack.com/archives/GMERCL6P2/p1623697380030300)
- [TACC/Core-Portal releases](https://github.com/TACC/Core-Portal/releases) (reference)
- [TACC/Core-Portal `CHANGELOG.md`](https://github.com/TACC/Core-Portal/blob/main/CHANGELOG.md) (reference)
> Quick: Set Version & Add Changelog

- taccsite_cms/static/site_cms/css/src/site.css
Mention a new ticket in comments of relevant code so that we are reminded that there is a ticket for a better way.
Mentions GH-302.
- Add comments to a file.
N/A
> GH-302: Mention this ticket in comments

- taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
Add a comment about approved CSS that I wrote but about which I have reservations.
- Add a `HELP` comment.
- Add a `SEE` comment to reference [CSS - Organization - Caveats](https://confluence.tacc.utexas.edu/x/DyUFDg).
N/A
> Quick: Add note and doc ref for `.o-section… a`

- taccsite_cms/static/site_cms/css/src/site.header.css
- taccsite_cms/templates/assets_site.html
Clarify font load caveats and intended manner of loading on Portal & Docs.
- improve two existing comments
- add comment in template (that loads fonts) about how to load on Portal and Docs
N/A
> Noop: Improve comments about font load

- taccsite_cms/templates/cms_menu.html
Simplify a verbose comment.
- None
- Shorten comment to one line.
N/A
N/A
> Noop: Reduce verbosity of nested dropdown comment

- CHANGELOG.md
Add [v3.3.0](https://github.com/TACC/Core-CMS/releases/tag/v3.3.0) to changelog.
> Add v3.3.0 to CHANGELOG

- docker-compose.dev.yml
- package.json
- taccsite_cms/static/site_cms/css/src/_themes/theme.default.json
- taccsite_cms/static/site_cms/css/src/_themes/theme.has-dark-logo.json
Reduce the diff of https://github.com/TACC/Core-CMS/pull/402/files by making some noop changes in isolation.
> Noop: Linting to reduce diff of task/COOKS-108

- CHANGELOG.md
Add v3.5.0 to changelog.
[Testing](https://confluence.tacc.utexas.edu/x/fobtDg) did not reveal anything that should block deploy.
> Quick/Add v3.5.0 to Changelog

- CHANGELOG.md
Release [v3.5.1](https://github.com/TACC/Core-CMS/releases/edit/untagged-ac189f46f5e11cdfccb0).
> Quick: v3.5.1 Changelog

- CHANGELOG.md
Release [v3.12.1](https://github.com/TACC/Core-CMS/releases/edit/untagged-ac189f46f5e11cdfccb0).
> Quick: v3.12.1 Changelog

- taccsite_cms/static/site_cms/css/src/_imports/trumps/s-document.css
- taccsite_cms/templates/guides/getting_started.html
Update Getting Started page to address:
- creating account for non-UT users
- requesting access before login
* [FP-1435](https://jira.tacc.utexas.edu/browse/FP-1435)
1. In "Creating an Account", clarify two methods.
2. Add section "Requesting Access" for possible pre-login step.
- Adds an icon that looks like an image.
3. In "Logging In for the First Time", fix incomplete sentence.
4. In "Onboarding Your Account" ▸ "Requesting Access", note user may already have access.
> ⚠️ The wording in this render has been improved slightly since 8dc64ed, e1e21d0, ...
[annotations on render of edited Getting Started page](https://user-images.githubusercontent.com/62723358/149414643-5784dd03-4592-4827-a944-b3080da6dbd4.jpeg)
> remote testing: https://3dem-staging.tacc.utexas.edu/help/getting-started/ …
> FP-1435: Updates on Getting Started page

- CHANGELOG.md
> v3.14.0 Changelog

- CHANGELOG.md
Update change log for https://github.com/TACC/Core-CMS/releases/tag/v3.15.0.
> Quick: v3.15.0 Changelog

- README.md
Polish the readme based on changes from #442.
This should reduce the diff of #442, also.
> Noop: Polish README

- README.md
- taccsite_cms/static/site_cms/css/README.md
- taccsite_cms/static/site_cms/css/build/README.md
- taccsite_cms/static/site_cms/css/src/README.md
Tweaks to last Noop README update PR, #450. And other tiny changes to other READMEs.
> Noop: Tweak README Polish

- taccsite_cms/settings_custom.example.py
Polish the file `setting_sutom.example.py`.
- None
- No manual line wrapping.
- Slimmer prose in introduction.
- Highlight the walkthrough example.
- Add more examples.
N/A
> Noop: Polish settings_custom.example.py

- package-lock.json
- package.json
- taccsite_cms/settings_custom.example.py
- requires https://github.com/TACC/Core-CMS-Resources/pull/128
- requires https://github.com/TACC/Core-Styles/pull/4
> BM-29/30: Brainmap Logo Tweaks (SGCI/UTHSCSA)

- taccsite_cms/settings.py
- taccsite_cms/settings_custom.example.py
Add headings for TACC-specific settings.
N/A
- Update main settings.
- Update example settings.
- Update pre-project settings.
N/A
> chore(settings): add tacc comment headings

- taccsite_cms/static/site_cms/css/src/site.css
- taccsite_cms/static/site_cms/css/src/site.header.docs.css
Improves legibility of CSS imports of CMS stylesheets.
- [TUP-231](https://jira.tacc.utexas.edu/browse/TUP-231)
- requires https://github.com/TACC/Core-CMS/pull/482
N/A
N/A
> chore(tup-231): re-order and reduce comments

- taccsite_cms/settings.py
Comments for settings like [django-cms-quickstart](https://github.com/django-cms/django-cms-quickstart/blob/main/backend/settings.py#L28).
- clean up before [FP-1652](https://jira.tacc.utexas.edu/browse/FP-1652)
- shorten existing comments
- add comments
- move one app in the INSTALLED_APPS list
Testing / Screenshots
> chore(settings): add/edit comments, mostly apps

- .npmrc
- README.md
- author Release Workflow in README
- do not let `npm version ...` auto-commit
None
> chore: author release process

- CHANGELOG.md
- package-lock.json
- package.json
> chore: v3.8.0

- README.md
- bin/build-css.js
- taccsite_cms/templates/snippets/manual-pattern-library/README.md
Fix miscellaneous inaccuracies in docs and comments since recent updates.
- similar to https://github.com/TACC/tup-ui/pull/44
- similar to https://github.com/TACC/Core-Styles/pull/38
N/A
> chore(css): update docs & comments

- taccsite_cms/_settings/email.py
- taccsite_cms/_settings/form_plugin.py
- taccsite_cms/settings.py
Allow forms to send an e-mail.
_Remote server needs access to an SMTP server. Direction I can provide is to override settings for specific server (like APCD). Reference: [Django docs for email settings](https://docs.djangoproject.com/en/2.1/ref/settings/#email-backend)._
- [FP-1736](https://jira.tacc.utexas.edu/browse/FP-1736)
- required by https://github.com/TACC/Core-CMS-Custom/pull/4
- add e-mail settings
- note another known issue with forms (not related to e-mail)
- update form fields to show email feature
- add [developer guide for cms e-mail](https://confluence.tacc.utexas.edu/x/coR9E)
- import e-mail settings
<details><summary>Run and test production and staging e-mail settings and TACC mail server.</summary>
1. Be an admin on https://apcd-qa.tacc.utexas.edu/.
2. Open …
> feat: fp-1736 allow form to send email

- Dockerfile
- poetry.lock
- pyproject.toml
- taccsite_cms/utils/rt.py
Adding the RT package to Core CMS so we can automatically submit tickets from the CMS.
- [FP-1854](https://jira.tacc.utexas.edu/browse/FP-1854)
- required by https://github.com/TACC/Core-CMS/pull/558
- Added RT @ ~~^3.0.0~~  [^2.2]
- Updated Poetry install in Dockerfile
> Task/FP-1854 - Add RT package and update poetry version

- package-lock.json
- package.json
Update Core-Styles & Core-CMS-Resources pins.
- https://github.com/TACC/Core-Styles/pull/48
- https://github.com/TACC/Core-CMS/pull/531
- https://github.com/TACC/Core-CMS-Resources/pull/158
> chore: latest core-cms-resources & core-styles v0.9.0

- package-lock.json
- package.json
Point to Core-Styles `main` latest which is an update Core-Styles dependencies.
- [TUP-239](https://jira.tacc.utexas.edu/browse/TUP-239)
- requires https://github.com/TACC/Core-Styles/pull/50
- similar to https://github.com/TACC/tup-ui/pull/64
See https://github.com/TACC/Core-Styles/pull/50
> chore(core-styles): tup-293 dependency updates

- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.forms.css
Support `demdata-cms` on old build system until new build system problems are resolved.
- requires https://github.com/TACC/Core-CMS-Resources/pull/168
- alternative https://github.com/TACC/Core-CMS-Custom/pull/41
- feat(taccsite_custom): add demdata-cms
Build: https://jenkins01.tacc.utexas.edu/job/Core_CMS_Build/846
Deploy: https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/2129
Server: https://pprd.democratizing-site.tacc.utexas.edu/
CMS loads.
N/A
> feat(taccsite-cms): demdata-cms, old build solution

- package-lock.json
- package.json
Update to use https://github.com/TACC/Core-Styles/releases/tag/v0.10.0.
Many previous PRs testing relevant changes up to this version.
Skipped.
<sup>This is done incrementally for relevant changes up to v0.10.0.</sup>
> feat(core-styles): v0.10.0

- package-lock.json
- package.json
Downstream regression test of https://github.com/TACC/Core-Styles/pull/102.
- https://github.com/TACC/Core-Styles/pull/102
> feat(core-styles): base, cms, docs, portal re-org

- package-lock.json
- package.json
Table styles updates from Core-Styles.
- requires https://github.com/TACC/Core-Styles/pull/127
- required by https://github.com/TACC/tup-ui/pull/145
See https://github.com/TACC/Core-Styles/pull/127.
> chore(core-styles): tup-cms table updates

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
Prepare to release v3.10.0.
- follow release steps
- improve release steps
> feat: v3.10.0

- CHANGELOG.md
- package-lock.json
- package.json
> fix: v3.10.1

- CHANGELOG.md
- package-lock.json
- package.json
> fix: v3.9.3

- CHANGELOG.md
- package-lock.json
- package.json
> fix: v3.10.2

- CHANGELOG.md
- package-lock.json
- package.json
> feat: v3.11.0

- CHANGELOG.md
- package-lock.json
- package.json
> fix: v3.11.1

- CHANGELOG.md
- package-lock.json
- package.json
> fix: v3.11.4

- CHANGELOG.md
- package-lock.json
- package.json
Prepare v3.12.0-alpha.12 for release.
> chore: v3.12.0-alpha.12

- docs/develop-project.md
- taccsite_cms/locale/en/LC_MESSAGES/README.md
To improve documentation about how to customize Admin UI text:
- Added missing step.
- Fixed broken link.
- Removed unnecessary PR reference.
- inspired while working on #693
N/A
> docs: fix broken link (customize admin ui text)

- CHANGELOG.md
- package-lock.json
- package.json
> fix(taccsite_custom): wrong pointer in v3.11.3 (#668)

- CHANGELOG.md
- package-lock.json
- package.json
Prepare for v3.11.6 release.
- mimics/fixes #698
> chore: v3.11.6

- CHANGELOG.md
- package-lock.json
- package.json
Prepare for v3.12.0-beta.1 release.
> chore: v3.12.0-beta.1

- CHANGELOG.md
- package-lock.json
- package.json
Prepare for v3.12.0-beta.2 release.
> chore: v3.11.0-beta.2

- package-lock.json
- package.json
Accurately label our dependencies as `dependencies`, not `devDependencies`.
N/A
- rename `devDependencies` to `dependencies`
Skipped.
> fix: our dev dependencies are actually for prod

- CHANGELOG.md
- package-lock.json
- package.json
Prepare for v3.12.0-beta.3 release.
> chore: v3.12.0-beta.3

- CHANGELOG.md
- package-lock.json
- package.json
Prepare for v3.12.0-beta.4 release.
> chore: v3.12.0-beta.4

- CHANGELOG.md
- README.md
- docs/upgrade-project.md
- package-lock.json
- package.json
1. Prepare for release of v4.0.0.
2. Change changelog syntax to use asterisks.
3. Document CMS update and upgrade.
- promotes https://github.com/TACC/Core-CMS/releases/v3.12.0-beta.4
N/A
> feat: v4.0.0

- CHANGELOG.md
- package-lock.json
- package.json
> chore: v4.1.0

- README.md
- docs/develop-custom-project.md
- docs/develop-project.md
- Change "Start Project" to "Getting Started", and improve it.
- Update "Prerequisites" to be simpler and up-to-date.
- Change "Project Customization" to "Develop a Custom Project", and move it.
None.
1. Open [the `README.md` at this branch](https://github.com/TACC/Core-CMS/blob/docs/readme-getting-started-and-custom-project/README.md).
2. Review [changes](https://github.com/TACC/Core-CMS/pull/733/files) as they appear on document preview.
3. Via Table of Contents, navigate to:
- Getting Started
- Develop a Custom Project
4. Offer any feedback.
> docs(README): Getting Started & Custom Project

- CHANGELOG.md
- package-lock.json
- package.json
> chore: v4.2.0

- CHANGELOG.md
- package-lock.json
- package.json
- taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.blog.app.page.css
> chore: v4.2.1

- CHANGELOG.md
- package-lock.json
- package.json
> chore: v4.3.0

- CHANGELOG.md
- package-lock.json
- package.json
> chore: v4.4.0

- CHANGELOG.md
- package-lock.json
- package.json
> chore: v4.4.1

- CHANGELOG.md
- package-lock.json
- package.json
> chore: v4.5.0

- CHANGELOG.md
- package-lock.json
- package.json
> chore: v4.6.0

- CHANGELOG.md
- package-lock.json
- package.json
> chore: v4.7.1

- taccsite_cms/settings.py
- taccsite_cms/settings_custom.example.py
Change example settings to support #795.
- fix local setup after #795
- **fixes** examples settings
Skipped.
> fix: example settings for favicon and logo

- docs/upgrade-project.md
Document v4.7.N new favicon and logo settings for future upgrades.
- documents #783
- documents #795
- **documents** settings / upgrade to v4.7.N
https://github.com/TACC/Core-CMS/blob/49f0963/docs/upgrade-project.md
> docs: new favicon & logo settings

- CHANGELOG.md
- package-lock.json
- package.json
> chore: v4.7.2

- CHANGELOG.md
- package-lock.json
- package.json
> chore: v4.8.1

- CHANGELOG.md
- package-lock.json
- package.json
> chore: v4.8.3

- CHANGELOG.md
- package-lock.json
- package.json
> chore: v4.10.2

- package-lock.json
- package.json
Do not let tall navbar be hidden by short header.
- https://github.com/TACC/Core-Styles/releases/v2.25.2
Occurs on [PTDataX](https://ptdatax.tacc.utexas.edu/). (Reported in Slack by external stakeholder.)
> fix: expanded navbar can overflow header

- package-lock.json
- package.json
Update Core-Styles to v2.35.1.
> deps: core-styles v2.35.1

- package-lock.json
- package.json
Get muted and dark bootstrap columns from [Core-Styles v2.36.0](https://github.com/TACC/Core-Styles/releases/tag/v2.36.0).
> feat: muted bootstrap cols / deps: core-styles v2.36.0

- taccsite_cms/settings.py
Add choices to Bootstrap4 Columns:
- Dark column (`col col-dark`)
- Muted column (`col col-muted`)
- follow up to #888
1. Create/Edit a Column.
2. Set "Column type" to "Dark column".
3. Verify column is dark.
4. Set "Column type" to "Muted column".
5. Verify column is gray.
> feat(settings): bootstrap4 column choices

- taccsite_cms/templates/assets_core.html
- taccsite_cms/templates/assets_core_delayed.html
Addressing issues mentioned in UT security scan attached to JIRA. The main issues are updating Bootstrap and jQuery.
- [WI-212](https://tacc-main.atlassian.net/browse/WI-212)
- tested by https://github.com/TACC/tup-ui/pull/494
Updated bootstrap from 4.0.0 to 4.6.2 and jQuery from 3.2.1 to 3.5.1
1. Generally click around the CMS and make sure that you don't see any obvious styling problems.
2. Deploy and test on [pre-prod LCCF](https://pprd.lccf-portal.tacc.utexas.edu/) and [dev.TACC](https://dev.tup.tacc.utexas.edu/).
None
> task/WI-212: Updating to address UT security scan.

- package-lock.json
- package.json
- test https://github.com/TACC/Core-Styles/pull/427
- required by https://github.com/TACC/Core-CMS-Custom/pull/410
| LCCF Custom `header.css` | Core-Styles `…header.css` |
| - | - |
| <img width="960" alt="lccf custom header css content" src="https://github.com/user-attachments/assets/12c87860-5bce-4b86-a976-4bb285613901" /> | <img width="960" alt="core-styles header css content" src="https://github.com/user-attachments/assets/fade952f-b2f2-4880-a10a-a2308f30b0ed" /> |
| <img width="960" alt="lccf custom header css url" src="https://github.com/user-attachments/assets/90e8da91-71a1-4f9b-9ba7-d9313b5c2b1e" /> | <img width="960" alt="core-styles header css url" src="https://github.com/user-attachments/assets/ac071de0-f245-4a4b-9870-86ed33c88bba" /> |
| mobile view |
| - |
| <img width="960" …
> fix(core-styles): header nav-link alignment

- package-lock.json
- package.json
Bump Core-Styles.
- gets
- https://github.com/TACC/Core-Styles/pull/462
- https://github.com/TACC/Core-Styles/pull/464
- https://github.com/TACC/Core-Styles/pull/467
- for https://github.com/TACC/Core-Portal/pull/1068
> deps: core-styles v2.39.x

- package-lock.json
- package.json
Update Core-Styles.
- support https://github.com/TACC/Core-CMS-Custom/pull/444
**Skipped.** Already tested on client use cases ([details](https://github.com/TACC/Core-Styles/pull/490)).
> deps: core-styles v2.41.1

- package-lock.json
- package.json
Update [Core-Styles to v2.42](https://github.com/TACC/Core-Styles/releases/tag/v2.42.0).
> deps: core-styles v2.42

- package-lock.json
- package.json
- pyproject.toml
Update [Core-Styles to v2.43](https://github.com/TACC/Core-Styles/releases/tag/v2.43.0).
> deps: core-cms 4.28.0-alpha.3 core-styles v2.43.0

- package-lock.json
- package.json
- pyproject.toml
Update [Core-Styles to v2.43.1](https://github.com/TACC/Core-Styles/releases/tag/v2.43.1).
> deps: core-cms 4.28.0-alpha.4 core-styles v2.43.1

- package-lock.json
- package.json
- pyproject.toml
Update [Core-Styles to v2.43.2](https://github.com/TACC/Core-Styles/releases/tag/v2.43.2).
> deps: core-cms 4.28.0-alpha.5 core-styles v2.43.2

- .github/pull_request_template.md
- README.md
- docs/develop-custom-project.md
- taccsite_cms/static/site_cms/css/README.md
* Document https://github.com/TACC/Core-CMS-Template.
* Retire or update references to:
- https://github.com/TACC/Core-CMS-Resources
- https://github.com/TACC/Core-CMS-Custom
Skipped.
> docs: core-cms-template

- package-lock.json
- package.json
[Core-Styles v2.45.0](https://github.com/TACC/Core-Styles/releases/tag/v2.45.0)
- required by https://github.com/TACC/Core-Portal/pull/1127
No change to:
- header CMS nav dropdown
- header Portal nav dropdown
Tested on https://pprd.digitalrocks.tacc.utexas.edu/ on 2025-07-03 at 19:00 CST.
> deps: core-styles v2.45

- taccsite_cms/static/site_cms/css/src/_imports/settings/font.css
Delete Texascale project form Core-CMS-Resources (`taccsite_custom`).
- requires https://github.com/TACC/Core-CMS-Resources/pull/209
> chore: delete texascale from git submodule
